### ISSUE TITLE
Support masking operation without timeband

### ISSUE THREAD

**Issue by Jaapel** [Open-EO/openeo-geopyspark-driver#122]
I am trying to mask my datacube (without `t` dimension) using a mask that also does not have a `t` dimension.
Resulting error is: `OpenEoApiError('[500] unknown: Geotrellis backend does not yet support masking datacube without time dimension.')`
Using `.add_dimension(label=f"my_label", name="t", type="temporal")` also does not fix this issue.

**Comment by jdries** [comment]
Seems like a simple case, will add it!

**Comment by jdries** [comment]
@Jaapel  could you perhaps try again on openeo-dev.vito.be?

**Comment by Jaapel** [comment]
@jdries works 👍

**Comment by jdries** [comment]
Thanks!
