### ISSUE TITLE
improve error message for unsupported sar_backscatter options for Sentinel Hub

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#132]
Users are wondering why e.g. some backscatter coefficients are not supported even though they are advertised in the docs:
```openeo_driver.errors.FeatureUnsupportedException: sar_backscatter: coefficient sigma0-terrain is not supported```

We can avoid this confusion by specifying that this particular collection doesn't support it + include collection-specific details in the error message, for example a link to the processing options for the "sentinel-1-grd" collection: https://docs.sentinel-hub.com/api/latest/data/sentinel-1-grd/#processing-options

**Comment by soxofaan** [comment]
>  advertised in the docs

which docs? Because there should be a note there as well that some coefficients might be not supported on some back-ends

**Comment by bossie** [comment]
The description of the "coefficient" argument at https://openeo.org/documentation/1.0/processes.html#sar_backscatter as well as https://open-eo.github.io/openeo-python-client/api.html#openeo.rest.datacube.DataCube.sar_backscatter.

> Note that backscatter computation may require instrument specific metadata that is tightly coupled to the original SAR products. As a result, this process may only work in combination with loading data from specific collections, not with general data cubes.

So they can't expect that "sar_backscatter" works with every collection, but they might expect that once they have a "sar_backscatter"-compatible collection, they can obtain every coefficient from it, which is not the case.
