### ISSUE TITLE
log sentinelhub batch job usage in job metadata

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#151]

**Comment by bossie** [comment]
Is this done? (https://github.com/Open-EO/openeo-geotrellis-extensions/issues/41 + https://jira.vito.be/browse/FD-5241)

**Comment by jdries** [comment]
This one was about the batch jobs, like card4l backscatter. Do we already track that?

**Comment by bossie** [comment]
TODO: ask if there is an exact value after the batch process completes.

**Comment by bossie** [comment]
Response from Daniel:

> unfortunately there is currently no way for you to obtain the exact amount of PUs for a batch job. This is something planned for the future but there is no exact timeline so we need to continue using a workaround for now.  In our SH openEO backend we use an estimate that is slightly more accurate than what you use (see below) and what I would recommend you to use for now. As you can see it has a security margin so the estimate always covers the actually resources spent.

    default_temporal_interval = 3
    estimate_secure_factor = 2

    # Note that the cost estimate does not take the multiplication factor of 1/3
    # for batch processing into account.
    # The actual costs will be 3 times lower than the estimate.
    # https://docs.sentinel-hub.com/api/latest/api/batch/#cost-estimate
    actual_pu_to_estimate_ratio = 1 / 3

    # multiply by 2 to be on the safe side
    estimate_secure_factor = actual_pu_to_estimate_ratio * 2

    p = Process(process, access_token=g.user.sh_access_token)
    temporal_interval = p.get_temporal_interval(in_days=True)

    if temporal_interval is None:
        temporal_interval = default_temporal_interval

    estimated_pu = estimate_secure_factor * batch_request.value_estimate * default_temporal_interval / temporal_interval
    return estimated_pu

**Comment by bossie** [comment]
Batch process usage is added to the sync usage (processing units): https://github.com/Open-EO/openeo-geopyspark-driver/blob/17e7c8e60985a60a5c7eb8e8884afcfb75163087/openeogeotrellis/job_tracker.py#L143-L155
