### ISSUE TITLE
Correctness & performance of reduce_dimension over time

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#152]
Copy of [EP-3726](https://jira.vito.be/browse/EP-3726).
There's two important issues with doing a reduce_dimension on the temporal dimension.

[C](https://discuss.eodc.eu/t/which-is-the-right-function-to-apply-sd/349)
![image](https://user-images.githubusercontent.com/5937096/166097327-96610573-4493-479e-a1da-6e15e5de6bd2.png)

> 
> Simple reduction over time, for instance for sum or mean, can be implemented more efficient for commutative associative operators.
> The current implementation does a full grouping by date, which is rather unnecessary.
> It also does a default conversion to float, which is not needed for all types/reducers.
> 
> The culprit is this implementation:
> openeogeotrellis.geopysparkdatacube.GeopysparkDataCube.reduce
> which also relies on numpy. I would suggest using the more generic Scala 'OpenEOProcessScriptBuilder' approach to tackle this, as it reduces the number of custom code paths, and will be more efficient.
>

**Comment by jdries** [comment]
Implement using:

```
return self._apply_to_levels_geotrellis_rdd(
                        lambda rdd, level: pysc._jvm.org.openeo.geotrellis.OpenEOProcesses().applyTimeDimension(rdd,process.builder,context if isinstance(context,dict) else {}))
```

**Comment by JeroenVerstraelen** [comment]
https://github.com/Open-EO/openeo-geotrellis-extensions/commit/0393fa019c1fd26b2862cb11c0e72c9313883525
