### ISSUE TITLE
support merge_cubes(2Dcube, 3Dcube)

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#158]
geopyspark driver supports merge_cubes(3Dcube, 2Dcube) but not the other way around

see https://github.com/openEOPlatform/architecture-docs/issues/224#issuecomment-1123904193

> `W * RAT_VH ` translates to something like `merge_cubes(W, RAT_VH, overlap_resolver="multiply")` with W being a 2D (x-y) cube and RAT_VH a 3D (x-y-t) cube. Apparently this is not supported on VITO backend.
> 
> But the other way around seems to be supported: `RAT_VH * W` translates to something like `merge_cubes(RAT_VH, W, overlap_resolver="multiply")`

**Comment by jdries** [comment]
closing this one, it seems to be supported in the code, and original forum issue is also resolved
