### ISSUE TITLE
Travis build is failing since 4 months

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#16]
all travis builds from last 4 months failed:
https://travis-ci.org/Open-EO/openeo-geopyspark-driver/builds

**Comment by soxofaan** [comment]
Latest failures are because openeo-geopyspark-driver depends on openeo-python-driver, and travis takes latest version available from https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple/openeo-driver/  which is currently `0.0.1.20190705.2`.  This is quite an old version, and some recent PRs would fix some things I think.

**Comment by soxofaan** [comment]
possible solutions:

- bump version of openeo-python-driver, e.g. to `0.0.2`, create new release  and require that in geopyspark driver
- in geopyspark travis:  install openeo-python-driver directly from latest github master 

what do you think @jdries ?

**Comment by jdries** [comment]
it seems that is now failing on some java issue, possibly because it tries to run on java 11

**Comment by jdries** [comment]
java issue seems to be solved again now, so it's back to basic python issues

**Comment by soxofaan** [comment]
strange error now, pytest doesn't seem to find `openeogeotrellis`  module
```
_________________ ERROR collecting tests/test_apply_process.py _________________
ImportError while importing test module '/home/travis/build/Open-EO/openeo-geopyspark-driver/tests/test_apply_process.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_apply_process.py:15: in <module>
    from openeogeotrellis.GeotrellisImageCollection import GeotrellisTimeSeriesImageCollection
E   ModuleNotFoundError: No module named 'openeogeotrellis'
```

**Comment by soxofaan** [comment]
pushed dfbcda4 and now at least the tests run

however there are failing tests which I can not reproduce locally

      ========= 6 failed, 30 passed, 1 skipped, 7 warnings in 25.43 seconds ==========

**Comment by jdries** [comment]
Travis build fixed, good teamwork!
