### ISSUE TITLE
array_labels in reduce_dimension not supported

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-geopyspark-driver#166]
I'd like to run the following reducer, but I get an error that array_labels is not supported:

```r
reducer = function(data, context = NULL) {
	labels = p$array_labels(data = data)
	order = p$order(data = data, asc = FALSE)
	labels_sorted = p$rearrange(order = order, data = labels)
	return(p$first(data = labels_sorted))
}
datacube1 = p$reduce_dimension(reducer = reducer, dimension = "t", data = data)
```

Issue came up in the forum due to a user request: https://discuss.eodc.eu/t/month-of-the-maximum-ndvi/377

**Comment by jdries** [comment]
This use case behind this issue can be solved in a better way:
replace reduce_dimension with apply_dimension

In the callback:
- find max value (this replaces order + rearrange)
- do an array_apply with an if process that only retains values equal to the max

The resulting datacube will now contain both the desired dates and corresponding max values, and can be used in further processing.

Supporting the original proposal is a lot more effort, not really feasible in the short term.
