### ISSUE TITLE
New rate limiting approach by Sentinel Hub

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-geopyspark-driver#175]
We've got notified that the rate limiting approach is going to change soon. 

The endpoints used by Rate Limiting Guard sadly won't be available anymore, so it will probably have to be retired.

Instead, the responses will include an improved version of `X-Retry-After` header. This already exists, but is arguable not very usable, so the improved version aims to make it more useful, it will be responding to the behaviour of the client and will implement exponential backoff. 

Additionally, there will be `X-Remaining-Capacity` header (it's a working name), which will contain the information about remaining available concurrent requests.

This will now be also available for collections on `us-west-2` and `creodias` (currently it's only on ` eu-central-1`).

So the implementation will have to change to simply retry requests after `X-Retry-After` seconds in case they got rate limited. 

What could be an issue is the ramp-up limits, as there is a limit of requests that can be started simultaneously. 429 handling should take care of that, but it would be possible to avoid hitting some 429s by ramping up requests slower in case there are lots of them.

This is coming to `us-west-2` (for example, Landsat collections are hosted there) in a matter of weeks.

@soxofaan @jdries @dthiex

**Comment by bossie** [comment]
When exactly are the endpoints used by RLGuard going to become unavailable?

**Comment by Ardweaden** [comment]
@bossie 
I think the exact date is not determined yet, however they "are not in a hurry" to remove them.

**Comment by bossie** [comment]
@Ardweaden : I'm not seeing these headers (Retry-After nor X-Retry-After); I've tried the eu-central-1 and us-west-2 endpoints. :thinking:

**Comment by Ardweaden** [comment]
> @Ardweaden : I'm not seeing these headers (Retry-After nor X-Retry-After); I've tried the eu-central-1 and us-west-2 endpoints. 🤔

It works fine for me. Are you sure you hit HTTP 429 errors?

Here is a small script I wrote that creates a bunch of workers and makes requests, and then each worker sleeps upon hitting 429s, if that helps: https://raw.githubusercontent.com/Ardweaden/Custom-scripts/master/test_rate_limiting.py

`headers["Authorization"]` must be replaced with a valid Sentinel Hub access token, the one in the script has probably expired.

**Comment by bossie** [comment]
Right, my mistake. :+1:

**Comment by Ardweaden** [comment]
@bossie 
Sentinel Hub plans to retire the old rate limiting endpoints in a week, by when rate limiting guard won't work anymore. Is that ok for you?

**Comment by jdries** [comment]
@Ardweaden  That's very fast, the announcement came 2 months ago, but our developers have been away for 3 weeks in that period. @bossie  will implement this now, but we hoped to still have some overlap in which we can see if the new setup actually works? We also want to test on develop first for a few weeks before pushing into production.

**Comment by Ardweaden** [comment]
@jdries I talked to the team that manages rate limiting and they said they can keep the endpoints used by rate limiting guard alive "for a while".
It won't get updated, but iiuc that just means the data won't be available for new users, or if the limits of your account change. However, that's not an issue for you.

**Comment by Ardweaden** [comment]
@jdries Did you notice any weird behaviour regarding the rate limits in the last week, e.g. higher rate of 429s?
Turns out one of the endpoints used by rate limiting guard, that returns the current remaining requests and processing units has stopped being updated a week ago (so the values returned should always be the same).

**Comment by bossie** [comment]
Calling into withoutGuardedRateLimiting instead of withGuardedRateLimiting will disable RLGuard-based rate limiting and enable retry-after rate limiting: https://github.com/Open-EO/openeo-geopyspark-driver/blob/8e21eea21e314918bdc96ca81294266069a5722f/openeogeotrellis/layercatalog.py#L431
