### ISSUE TITLE
broken `COPERNICUS_30` collection

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#180]

**Comment by soxofaan** [comment]
https://discuss.eodc.eu/t/dem-copernicus-30-missing-data/404

A simple download of the COPERNICUS_30 collection looks broken: lot of missing data, horizontal/vertical strips, "observation dates" that are completely empty ,...

**Comment by soxofaan** [comment]
Example of NetCDF downloads of
```
con.load_collection(
        "COPERNICUS_30",
        temporal_extent=["2000-01-01", "2030-12-31"],
        spatial_extent=spatial_extent,
    )
```
for a couple of spatial extents:
![Screenshot from 2022-06-17 19-42-25](https://user-images.githubusercontent.com/44946/174350796-98438230-f0d2-4985-90ad-2227e9f76390.png)

note:
- multiple observation dates (while there should only be one)
- lot of NaN (white)
- the saturated yellow is value 9.9692100e+36  (or something else extreme)
- horizontal and vertical lines of this extreme value

**Comment by jdries** [comment]
The catalog actual returns 'observations' with different dates:
https://services.terrascope.be/catalogue/products?collection=urn%3Aeop%3AVITO%3ACOP_DEM_GLO_30M_COG&bbox=5.5%2C50.5%2C6.5%2C51.5&sortKeys=title&startIndex=1&accessedFrom=MEP&clientId=&start=2000-01-01T00%3A00%3A00Z&end=2030-01-01T23%3A59%3A59.999999999Z

**Comment by jdries** [comment]
The output to netcdf also returns more data than necessessary (known issue), but we can now avoid that by enabling strict cropping:

`cube.max_time().download(path,options={"strict_cropping":True})`

After doing that, we already get more normal output, except for one horizontal line of empty pixels.
This line resembles internal issue EP-3928, which seems to have been resolved by using a gdal raster source.

**Comment by jdries** [comment]
Fix committed: merge of neighbouring tiles was not working for this data, because the geotiffs do not declare NaN to be nodata value.
I now do a conversion to default nodata value if a nodata value is not set.

**Comment by soxofaan** [comment]
I just checked my notebook against openeo-dev.vito.be where the fixed is deployed and the nodata related issue is indeed resolved. There is still the issue with multiple "observation dates" but that is apparently because the source data is annotated as such. It is therefore recommended to use temporal reduction with e.g. `cube.max_time()`  to flatten the time dimension.
Result looks much better now:

![Screenshot from 2022-06-24 14-26-22](https://user-images.githubusercontent.com/44946/175536212-1f22da77-df41-48e8-b535-a99c4346f7d8.png)
