### ISSUE TITLE
openeo-dev batch jobs seem to run with wrong user

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#189]
Perhaps due to job tracker work, but batch jobs on openeo-dev do not seem to pick up the right user.

**Comment by bossie** [comment]
It's not specific to dev as the problem also manifests itself on prod, for batch jobs with OIDC authentication that are started from the web API as well as from an async_task.

I can see that my proxy_user falls back to "openeo" (probav-mep.py) which suggests the issue lies with the interfacing with Keycloak.

**Comment by bossie** [comment]
Thomas Cassaert is looking into it.

**Comment by bossie** [comment]
The lines in question that make the application fall back to user "openeo" in case Keycloak returns an error: https://git.vito.be/projects/BIGGEO/repos/openeo-deploy/browse/mep/probav-mep.py?at=bd8a8947ada2252a146034440f1cd47f7f0e55a0#124-130

Keycloak seems to be returning this response to our token exchange requests:
> 400 Bad Request: {"error":"invalid_token","error_description":"invalid token"}

Warning logs for these errors are in Kibana: https://kibana-infra.vgt.vito.be/app/kibana#/discover/b2357890-50ee-11ec-8cc4-3747d5233c59?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-3d,to:now))&_a=(columns:!(message,thread,file,timestamp,levelname,job_id,filename,user_id),filters:!((%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:%2701193f20-eafd-11ec-8cc4-3747d5233c59%27,key:tags,negate:!f,params:(query:openeo-driver),type:phrase),query:(match:(tags:(query:openeo-driver,type:phrase)))),(%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:%2701193f20-eafd-11ec-8cc4-3747d5233c59%27,key:filename,negate:!f,params:(query:probav-mep.py),type:phrase),query:(match:(filename:(query:probav-mep.py,type:phrase)))),(%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:%2701193f20-eafd-11ec-8cc4-3747d5233c59%27,key:levelname,negate:!f,params:(query:WARNING),type:phrase),query:(match:(levelname:(query:WARNING,type:phrase))))),index:%2701193f20-eafd-11ec-8cc4-3747d5233c59%27,interval:auto,query:(language:lucene,query:%27%27),sort:!(!(%27@timestamp%27,desc)))

**Comment by bossie** [comment]
Screenshot shows correct mapping of EGI to Terrascope user for batch job on openeo-dev:

![egi_to_terrascope_user_mapping](https://user-images.githubusercontent.com/1032518/189345974-8ab7c3cb-7904-4819-96e0-3c0a48464605.png)
