### ISSUE TITLE
PG producing wrong results

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-geopyspark-driver#190]
Testing a few settings below process graph always returns "wrong" results.

### PG to replicate
```
{
  "process_graph": {
    "1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "properties": {},
        "spatial_extent": {
          "west": 14.510936603443803,
          "east": 14.515831906845039,
          "south": 46.04838627516747,
          "north": 46.05080123932379
        },
        "temporal_extent": [
          "2022-03-26T00:00:00Z",
          "2022-03-30T00:00:00Z"
        ],
        "bands": [
          "B04",
          "B03"
        ]
      }
    },
    "3": {
      "process_id": "reduce_dimension",
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "1": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      }
    },
    "4": {
      "process_id": "apply",
      "arguments": {
        "data": {
          "from_node": "3"
        },
        "process": {
          "process_graph": {
            "1": {
              "arguments": {
                "inputMax": 1,
                "inputMin": 0,
                "outputMax": 255,
                "x": {
                  "from_parameter": "x"
                }
              },
              "process_id": "linear_scale_range",
              "result": true
            }
          }
        }
      }
    },
    "5": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "4"
        },
        "format": "PNG"
      },
      "result": true
    }
  },
  "parameters": []
}
```

**Comment by soxofaan** [comment]
SENTINEL2_L2A_SENTINELHUB has digital numbers ranging in thousands which doesn't play well with  `linear_scale_range` 's `inputMax: 1`: everything is clipped to 1 (or 255 in the output PNG)

**Comment by soxofaan** [comment]
I also notice you have just two input layers B04 and B03 (instead of just one for grayscale or three for RGB), I'm not sure how that will be stored in PNG

**Comment by dthiex** [comment]
> SENTINEL2_L2A_SENTINELHUB has digital numbers ranging in thousands which doesn't play well with linear_scale_range 's inputMax: 1: everything is clipped to 1 (or 255 in the output PNG)

🤦‍♂️ Thanks for the pointer! With all the testing on our backend lately I forgot that you request the data as DN and not like we as reflectance (which has 0-0.4 value range). Scaling to the right range, I get correct results.

> I also notice you have just two input layers B04 and B03 (instead of just one for grayscale or three for RGB), I'm not sure how that will be stored in PNG

This was what I originally actually wanted to test. The implementation looks consistent as you cut of the 2nd band in such a case (same as you have it implemented for >3 bands where you also cut of all additional bands).
