### ISSUE TITLE
Paths in capabilities should not include the base URL of the API

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-geopyspark-driver#2]
Today I tried to include this backend in the openEO Hub, but the crawling process failed because the crawler didn't recognise the backend as supporting any features. This happened because the `path`s in the [capability document](http://openeo.vgt.vito.be/openeo/0.3.0/)'s `endpoints` attribute include the base URL of the API (e.g. `/openeo/0.3.0/collections` instead of `/collections`), so [the js-client's `hasFeature` method](https://github.com/Open-EO/openeo-js-client/blob/master/openeo.js#L544) couldn't detect any endpoints that it is familiar with.

The [corresponding API spec entry](https://open-eo.github.io/openeo-api/v/0.3.1/apireference/#tag/Capabilities/paths/~1/get) says that the `path`s should be the "Path to the endpoint, starting from the base url of the API" -- I see that this can be understood one or the other way, but it's meant to be "starting *after* the base url of the API". [Matthias just made this clearer in the docs](https://github.com/Open-EO/openeo-api/commit/90a3713).

**Comment by jdries** [comment]
Fixed and deployed new version, could you try again?

**Comment by christophfriedrich** [comment]
Yes, this fixed this issue :+1: However I came across a few more incompatibilities that caused the crawling to fail, I'll post them in another issue.
