### ISSUE TITLE
test biomass with experimental flag

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#210]
biomass now uses a 1px tilesize, we should try removing this, and setting the 'experimental' feature flag itself.
This should enable reprojection at load time, which allows to immediately read the coarse resolution agera5 data in the right projection.
nextland/src/nextland_services/biomassproduction.py:126
openeo-geopyspark-driver/openeogeotrellis/layercatalog.py:198

**Comment by soxofaan** [comment]
I've been testing to add the experimental featureflag, and now my test job did not fail after 45 minutes (as I tried this morning), but is still running after 4 hours. Not sure what is going on, because I see little activity in the Spark application overview UI at the moment.

**Comment by soxofaan** [comment]
first attempt failed at 
```
4:12:40 Job 'j-136bad1004f24dd2a3f149abedbba8a1': running (progress N/A)
4:13:40 Job 'j-136bad1004f24dd2a3f149abedbba8a1': error (progress N/A)
```

next  attempt failed at
```
1:10:07 Job 'j-ab2c12a5f58c423aba0e903a75c43513': error (progress N/A)
```

**Comment by soxofaan** [comment]
I still seem to find "java.lang.OutOfMemoryError: Java heap space" errors in the executor logs

**Comment by jdries** [comment]
It seems that the 1px tilesize is still in there somewhere:
Loading  with params DataCubeParameters(1, {}, FloatingLayoutScheme, ByDay, 8, None) and bands dewpoint-temperature;precipitation-flux;solar-radiation-flux;temperature-max;temperature-mean;temperature-min;vapour-pressure;wind-speed

Can you try and remove this setting in the nextland code? I believe it happens close to the agera5 load_collection call.

**Comment by soxofaan** [comment]
ok, apparently  I should have *replaced*  featureflag `"tilesize":1` with `"experimental": true` instead of appending the latter. I will fix and see where that gets us

**Comment by soxofaan** [comment]
after feature flag update, job still fails. e.g. job id

the error is however different, I think this is the relevant bit:
```
Job aborted due to stage failure: Task 0 in stage 48.0 failed 4 times, most recent failure: Lost task 0.3 in stage 48.0 (TID 1183) (epod125.vgt.vito.be executor 5):
java.lang.IllegalArgumentException: Encountered NaN during a refinement step: (NaN / 1.5289402263559785E7). Input Extent(5.102454840495947, -2498.7374886200123, 2565.1024548404957, 61.2625113799877) is likely not in source projection.
at geotrellis.vector.reproject.Reproject$.refine$1(Reproject.scala:104)
at geotrellis.vector.reproject.Reproject$.reprojectExtentAsPolygon(Reproject.scala:115)
at geotrellis.vector.reproject.Implicits$ReprojectExtent.reprojectAsPolygon(Implicits.scala:61)
at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:44)
at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:89)
at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:92)
at geotrellis.spark.reproject.TileRDDReproject$.$anonfun$matchReprojectRasterExtent$5(TileRDDReproject.scala:366)
at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
at scala.collection.Iterator.foreach(Iterator.scala:941)
at scala.collection.Iterator.foreach$(Iterator.scala:941)
```

**Comment by jdries** [comment]
The extent looks incorrect: 5.102454840495947, -2498.7374886200123, 2565.1024548404957, 61.2625113799877
(It's not valid lat/lon nor utm)
The logs print received extents in a couple of places, need to trace back where it starts being like this.

**Comment by jdries** [comment]
The creation of agera5 cube results in correct extent in metadata, but wrong extent in LayoutDefinition:
`
Created cube for  with metadata TileLayerMetadata(float32ud4.294967296E9,LayoutDefinition(Extent(5.102454840495947, -2498.7374886200123, 2565.1024548404957, 61.2625113799877),CellSize(10.0,10.0),1x1 tiles,256x256 pixels),Extent(5.102454840495947, 51.2625113799877, 5.105548444181807, 51.264331072605565),EPSG:4326,KeyBounds(SpaceTimeKey(0,0,1580947200000),SpaceTimeKey(0,0,1598572800000))) and partitioner Some(SpacePartitioner(KeyBounds(SpaceTimeKey(0,0,1580947200000),SpaceTimeKey(0,0,1598572800000))))`

**Comment by jdries** [comment]
required an additional fix to properly deal with auto:42001 projection used by utm layers
