### ISSUE TITLE
expose spark.task.cpus in job options

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#220]
Goal of spark.task.cpus is to increase the number of cpus available for a single spark task. This can speed up working with libraries like tensorflow.

**Comment by bossie** [comment]
Specify e.g. job_options:

```json
{"task-cpus": 3, "executor-cores": 3}
```
![task-cpus](https://user-images.githubusercontent.com/1032518/192259506-26eb18f5-97b5-4820-9952-4fb24ffaf732.png)


executor-cores has to be >= task-cpus, otherwise Spark returns an error:
> The number of cores per executor (=1) has to be >= the number of cpus per task = 3.
