### ISSUE TITLE
S1_GRD_SIGMA0_ASCENDING returns no data but viewer shows it

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-geopyspark-driver#221]
I'm trying to run this simple process graph. The WMTS viewer shows me that there is data available for the area I'm interested in:

![image](https://user-images.githubusercontent.com/31700619/190587513-adc73cf9-57ec-4cc0-a720-511de1245ee3.png)

but the back-end is not able to find it:

`Could not find data for your load_collection request with catalog ID "urn:eop:VITO:CGS_S1_GRD_SIGMA0_L1". The catalog query had correlation ID "c-3ff71ef89d824de7a153f153e2bf420e" and returned 0 results.`

Process graph:

```
{
  "process_graph": {
    "load1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "S1_GRD_SIGMA0_ASCENDING",
        "spatial_extent": {
          "west": 11.43021520978765,
          "east": 11.43389977728051,
          "south": 46.52941908750711,
          "north": 46.53229652592112
        },
        "temporal_extent": [
          "2021-03-01T00:00:00Z",
          "2021-11-30T00:00:00Z"
        ],
        "bands": [
          "VH",
          "VV"
        ]
      }
    },
    "save1": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "load1"
        },
        "format": "NETCDF"
      },
      "result": true
    }
  },
  "parameters": []
}
```

Note: aggregator and VITO back-end give the same error.

**Comment by soxofaan** [comment]
This was probably because of a data loss issue at VITO side (https://terrascope.be/en/news-events/restoring-missing-data)
I think the data has been restored by now. 
Can you retry?

**Comment by soxofaan** [comment]
ah ok I see, your bbox falls outside of the region we cover with S1_GRD_SIGMA0_ASCENDING

**Comment by soxofaan** [comment]
We should probably improve the error message, it currently looks very generic like an unexpected error

> OpenEoApiError: [400] BadRequest: Could not find data for your load_collection request with catalog ID "urn:eop:VITO:CGS_S1_GRD_SIGMA0_L1". The catalog query had correlation ID "c-b0b86f1c040045b1bc21f6db29f0e8c1" and returned 0 results. 

I remember we discussed a specific error code we should return in such a case, but I can't immediately find it

**Comment by soxofaan** [comment]
> Then the question is: why does the WMTS service show data for the area I'm interested in?

I think the viewer shows both ascending and descending.  Both collections `S1_GRD_SIGMA0_ASCENDING` and `S1_GRD_SIGMA0_DESCENDING`  link to the same WMTS service and layer.
If request the same process graph with `S1_GRD_SIGMA0_DESCENDING` you do get a result I think

**Comment by soxofaan** [comment]
> I remember we discussed a specific error code we should return in such a case (load empty data cube), but I can't immediately find it

@m-mohr do you remember or can find the ticket were we discussed this?

**Comment by clausmichele** [comment]
Yeah that's the issue! I can confirm:
![image](https://user-images.githubusercontent.com/31700619/191979791-9b47c2df-4768-453e-b547-5fd46d5dc3b6.png)

**Comment by m-mohr** [comment]
@soxofaan Not sure, this one? https://github.com/Open-EO/openeo-processes/blob/draft/load_collection.json#L226
