### ISSUE TITLE
Sentinelhub batch processing returns incorrect results for large areas

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#226]
When loading the SENTINEL2_L2A_SENTINELHUB collection with an area larger than 50x50 km² several issues arise.

- Incorrect dates
  * Dates are introduced that do not exist for that area in the [eo-browser](https://apps.sentinel-hub.com/eo-browser/?zoom=7&lat=4.58738&lng=-75.10254&themeId=DEFAULT-THEME)
  * These extra dates cause subsequent dates in the netCDF to be offset
  * E.g. when looking at three dates in a netCDF:
    * netCDF = 2021-04-28, eo-browser = 2021-04-28 (correct)
    * netCDF = 2021-04-30, eo-browser = 2021-05-03 (non-existent)
    * netCDF = 2021-05-03, eo-browser = 2021-05-08 (offset)
- Swath edge tiles seem to consist out of a combination of RDDs from different dates 
  * E.g. The third tile from the left here is on the edge of a swath and it appears to contain data from three different dates.
  ![Screenshot from 2022-09-28 15-18-01](https://user-images.githubusercontent.com/3028262/192990560-4baf3aff-1b27-4bdd-b22c-cd7bfc19b7a7.png)
- NetCDF shows data on the same date from two swaths taken at different dates.
  * Looking at the image above the data on the leftmost tile is likely taken at a different date compared to the data on the rightmost tile.
  * Since the swath ends at the third tile from the left, there should be no data in the rightmost tile.

The cause for the issue can be found on this line:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/backend.py#L1492

Short-term circumventions can be done in two ways:
1. Avoiding sentinelhub batch processing:
  `job_options={"sentinel-hub": {"input": "sync"}}`
2. Avoid processing areas larger than 50x50 km²:
  Use backend openeocloud.vito.be + `job_options = { "tile_grid": "utm-40km" } `

Smallest example that reproduces the issue (includes images):
https://gist.github.com/JeroenVerstraelen/dfcf979640ffcdce6f4454d271faabec

**Comment by soxofaan** [comment]
originally raised here: https://discuss.eodc.eu/t/job-splitting/467

**Comment by bossie** [comment]
Fixed; both sentinel-hub-s2l2a-cache and sentinel-hub-s1grd-cache indices have been dropped and recreated because they contained bad tiles.
