### ISSUE TITLE
k8s: manage job results directly on object storage

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#232]
Current k8s backend downloads results to a local disk, so they're lost upon restart. It makes more sense to keep them on object storage and  stream files from there as needed.
openeo-geopyspark-driver/openeogeotrellis/job_tracker.py:100

Code that returns data to the user will need to be adjusted to read from object storage directly:
openeo-python-driver/openeo_driver/views.py:998

job metadata lookup will need to be specialized for object storage:
openeogeotrellis.backend.GpsBatchJobs.get_results_metadata

**Comment by jdries** [comment]
job_metadata:

`{"geometry": {"type": "Polygon", "coordinates": [[[-3.72094148493, 41.5479759281], [-3.72094148493, 41.72972578481], [-3.47865906078, 41.72972578481], [-3.47865906078, 41.5479759281], [-3.72094148493, 41.5479759281]]]}, "bbox": [-3.72094148493, 41.5479759281, -3.47865906078, 41.72972578481], "area": {"value": 407487294.17255104, "unit": "square meter"}, "start_datetime": "2021-03-15T00:00:00Z", "end_datetime": "2021-10-31T00:00:00Z", "links": [], "assets": {"openEO.tif": {"href": "/batch_jobs/0146abc4-cf51-46da-9f4c-853781c563aa/openEO.tif", "type": "image/tiff; application=geotiff", "roles": ["data"], "bands": [], "nodata": NaN, "datetime": null}}, "epsg": 32630, "instruments": [], "processing:facility": "VITO - SPARK", "processing:software": "openeo-geotrellis-0.6.3a1", "unique_process_ids": ["array_modify", "arccos", "power", "subtract", "mask_scl_dilation", "save_result", "median", "predict_catboost", "divide", "aggregate_temporal", "reduce_dimension", "load_ml_model", "filter_bands", "apply_dimension", "resample_cube_spatial", "linear_scale_range", "sd", "sar_backscatter", "array_create", "rename_labels", "filter_bbox", "load_collection", "add", "sqrt", "if", "multiply", "mean", "merge_cubes", "array_interpolate_linear", "array_concat", "array_element", "clip", "quantiles", "apply", "is_nodata", "log"]}`

**Comment by soxofaan** [comment]
This issue was closed (indirectly?) by merging Open-EO/openeo-python-driver#157, which is not intended I think, as #280 is still open.

**Comment by JohanKJSchreurs** [comment]
> This issue was closed (indirectly?) by merging [Open-EO/openeo-python-driver#157](https://github.com/Open-EO/openeo-python-driver/pull/157), which is not intended I think, as #280 is still open.

My mistake. I linked both pull requests of the two code bases to this issue, but then closing either PR apparently closes the ticket, which is not what we want.
