### ISSUE TITLE
k8s: async job tracker

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#235]
Job tracker is a micro service for batch job management. On K8S, job tracker tasks are still part of the main web service. 
We need to see how this can be deployed separately, and if that requires a nifi instance.

**Comment by bossie** [comment]
As discussed:

- cron job should be a matter of writing a YAML file and specifying the Docker image;
- reporting usage to Marketplace is analogous to what we do in Nifi.

**Comment by bossie** [comment]
Added a job-tracker CronJob to the spark-jobs namespace.

A workaround for the OpenEO web app relying on the JobTracker having downloaded the job results to disk (this assumption no longer holds because they run in different containers) is in place until #232 is implemented.

**Comment by bossie** [comment]
Usage reporting, relying on an ETL API, is being tackled in a different ticket.
