### ISSUE TITLE
r-udf: add package dependencies for r4openeo use cases

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-geopyspark-driver#253]
@soxofaan, @jdries,
we are working on the use cases for r4openeo currently and are quite done with preparing the process graphs and udfs (https://github.com/Open-EO/r4openeo-usecases). We have them running on the eurac backend. In order to run them on VITO dev we'd need some more packages installed in R:
- caret (ML framework)
- bfast (break detection)

Would it be possible for you to install them? (I know that customization of packages is always a nightmare in UDF)

created specific issue from here: https://github.com/Open-EO/openeo-geopyspark-driver/issues/183

**Comment by soxofaan** [comment]
do you have an idea of how much additional dependencies and libraries this would drag in?

**Comment by jdries** [comment]
Note that I made an attempt to build the required additional packages, to see if this could be a quick thing, but there was a failure, hence will anyways require a bit more work.

**Comment by przell** [comment]
> do you have an idea of how much additional dependencies and libraries this would drag in?

bfast should be relatively light: https://cran.r-project.org/web/packages/bfast/bfast.pdf

> Depends R (>= 3.0.0), strucchangeRcpp
> Imports graphics, stats, zoo, forecast, Rcpp (>= 0.12.7), Rdpack (>=
> 0.7)
> Suggests MASS, sfsmisc, stlplus, raster
> 

caret is R's most famous ML framework, it will be heavier (but also serves a lot of potential use cases): https://cran.r-project.org/web/packages/caret/caret.pdf

> Depends ggplot2, lattice (>= 0.20), R (>= 3.2.0)
> Imports e1071, foreach, grDevices, methods, ModelMetrics (>= 1.2.2.2),
> nlme, plyr, pROC, recipes (>= 0.1.10), reshape2, stats, stats4,
> utils, withr (>= 2.0.0)
> Suggests BradleyTerry2, covr, Cubist, dplyr, earth (>= 2.2-3),
> ellipse, fastICA, gam (>= 1.15), ipred, kernlab, klaR, knitr,
> MASS, Matrix, mda, mgcv, mlbench, MLmetrics, nnet, pamr, party
> (>= 0.9-99992), pls, proxy, randomForest, RANN, rmarkdown,
> rpart, spls, subselect, superpc, testthat (>= 0.9.1), themis
> (>= 0.1.3)

**Comment by przell** [comment]
If you need more input or if there's something we could help with, let us know.

**Comment by przell** [comment]
@jdries, @soxofaan, 
would there be a rough time line that you could give us when you can squeeze in to work on this? We're also closing out the r4openeo project and need to plan our deliverables accordingly (I know there's SRR4 coming up for you, so you're probably busy with that currently)

**Comment by jdries** [comment]
I tried again, but again failed. Problem is I need to rebuild GDAL, but that now also fails due to some other dependency issue...
I basically need to get a hold of already 'compiled' versions of these R packages, and then I can put them somewhere on our cluster so they can be imported from there.
For timing, it really doesn't look good as SRR4 is taking up the next 2 weeks completely.

**Comment by przell** [comment]
@jdries, thanks a lot Jeroen for trying!
If you'd point us to the docker file you are currently using, could we compile the packages we want and share them with you? @edzer, what do you think?

**Comment by jdries** [comment]
We got lucky, and had some progress, the caret package came through, bfast not yet. We're also hoping that it doesn't blow up our image size too much.

**Comment by basu26** [comment]
@jdries we tried to run the R-UDF as a test with the caret package but got the error that there is no package called ‘ggplot2’ which is a dependency of the caret package itself. The job ID is j-787361a21a6e4b1396f4e3df7f11c7b5.

**Comment by jdries** [comment]
ggplot2 added, can you try again on openeo-dev?

**Comment by przell** [comment]
Hi @jdries, 
seems we're getting into a dependency swirl. @basu26 has tested again and received: 
`there is no package called ‘scales’`

I checked up on `ggplot2` - it imports `scales` and some other packages. (https://cran.r-project.org/web/packages/ggplot2/ggplot2.pdf)

There's the option to install with `dependencies = TRUE`, that would circumvent these problems. I'm not sure though how this aligns with the way you are making the packages available to your docker container.

**Comment by m-mohr** [comment]
Thanks @jdries for scales. I've tried again, now it's missing "vctrs". With the number of dependencies in all the packages, I assume we need another couple of rounds here...

**Comment by jdries** [comment]
seems indeed that caret has quite a lot of dependencies, so I ran R in the docker image manually and installed a number of dependencies. However, now I'm stuck again at the 'recipes' package, which has a build error just like bfast. 
I'll see if that can be fixed.

**Comment by m-mohr** [comment]
I think most dependencies come in from ggplot, which we likely don't need as we don't do plotting in UDFs anyway. Bummer that caret is requiring it anyway. 
What's the issue with recipes? Maybe @edzer can help here?

**Comment by jdries** [comment]
The issue with recipes is purely in our build system, I've requested a colleague to check it out.

**Comment by jdries** [comment]
It seems that we managed to build and install all  dependencies. I can at least import caret and bfast. Should be on our dev instance by tomorrow.
To test our docker image directly, you can use:
https://artifactory.vgt.vito.be/webapp/#/artifacts/browse/tree/General/vito-docker/almalinux8.5-spark-py-openeo/3.2.0

I do see some warnings related to running in a docker container:
```
> library(caret)
Loading required package: ggplot2
Loading required package: lattice
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
Warning message:
In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1

```

**Comment by edzer** [comment]
Great! The warnings come from docker images (on purpose) not having systemd and timedatectl; they go away if you pass on TZ to the docker image like is done [here](https://github.com/edzer/sdsr#readme), it has been fixed in the [next R release](https://bugs.r-project.org/show_bug.cgi?id=17421).

**Comment by m-mohr** [comment]
It's weird that these packages ask for all these things although we don't actually need them. We won't do any database-related work so I'm wondering whether these packages should only throw errors when the functionality is actually needed...

**Comment by edzer** [comment]
> We won't do any database-related work

package `DBI` doesn't do any database related work, and has no dependencies.

**Comment by m-mohr** [comment]
Oh, CRAN said something like "database interface" and good that it has no dependencies, but this was also meant more generally. The same applies for ggplot which has a lot of dependencies, but we don't really plot anything in UDFs.

**Comment by jdries** [comment]
@basu26  next deploy should also support sf. Basically any top level package that you try to import may have this problem, so you can also give me your list of imports, then I can test.
Of course, the lists will hopefully start getting shorter, as we'll probably have most commonly used libraries installed at some point.

Also agree with @m-mohr that the list of hard dependencies seems overly long, ggplot indeed being the best example, but I guess that's not easy to solve. If R does support more lazy loading of libraries, then it may indeed help to start raising awareness when the occasion arises.

**Comment by jdries** [comment]
closing issue, assuming that it now works.

**Comment by przell** [comment]
@jdries, sorry for not testing for some days. Thanks for continuously installing dependencies!
We have run the 2 use cases again on your dev backend (openeo-dev.vito.be). Unfortunately, it seems that the packages mentioned above are still missing.

*ML Use Case*
JobID: j-94a0a4f447ef4f33b8978b7e9705a6be
Error:
```
[...] Error: package or namespace load failed for ‘sf’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘DBI’[...]
```

*Bfast Use Case*
JobID: j-e2357c14e4b142dbb24480e0e1c2f7a2
Error:
```
[...] rpy2.rinterface_lib.embedded.RRuntimeError: Error: package or namespace load failed for ‘sf’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘DBI’ at [...]
```

cc @basu26
