### ISSUE TITLE
driver stderr logs spammed with 404 stack traces

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#256]
Looks like something is hitting nginx on epod-openeo-1 and epod-openeo-2 (see access logs) with requests (HEAD /); they're being forwarded to tsservice and logged as 404 responses in /var/log/openeo/openeo-driver-*.stderr.

Modifying the gatekeeper configuration to only forward requests for /internal, /v1.0 and /v1.1 and dropping the rest seemed to have some effect on  the access logs but 404s are still being added to the logs so what's up with that?

**Comment by bossie** [comment]
Looks like nginx is able to prevent the HEAD requests from reaching tsservice now: they're in the access logs but not in OpenEO's stderr log.

**Comment by bossie** [comment]
For future reference, the fix (for epod-openeo-1): https://git.vito.be/projects/PUPTAP/repos/hiera-resenv/browse/resenv_generic_prd/nodes/epod-openeo-1.vgt.vito.be.yaml?at=6051ffaec41309bb6faee277b23d27b920166e83#134

**Comment by soxofaan** [comment]
also for future reference/lookup, the stack traces looked like this:
```
javax.ws.rs.NotFoundException: HTTP 404 Not Found
 at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
 at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
```
