### ISSUE TITLE
allow setting log level for batch jobs, set default to INFO

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#258]
Users have a hard time finding relevant logs.
Now all jobs log at 'DEBUG' log level, generating quite a bit of unnecessary logs. It makes more sense to make this configurable, and log at INFO level by default.

**Comment by soxofaan** [comment]
Is this about the level to use when doing a log write from a job
or about setting the threshold level when requesting a log listing?

Because the former option will not change the problem of "generating quite a bit of unnecessary logs."

**Comment by bossie** [comment]
I agree that `/jobs/{job_id}/logs` should support a threshold level.

> Because the former option will not change the problem of "generating quite a bit of unnecessary logs."

What do you mean @soxofaan ?

**Comment by jdries** [comment]
The original issue is about configuring logging inside the jobs themselves, so that we indeed generate fewer logs by default and can still have more detailed logs if we want it.

**Comment by soxofaan** [comment]
> >    Because the former option will not change the problem of "generating quite a bit of unnecessary logs."
>
> What do you mean @soxofaan ?

Just changing the log level at log write time will not change the  volume of logs returned when the user requests the log listing, because there is indeed no filter option in the log listing request itself (the user or client like web editor still can do post-process-style filtering)

**Comment by soxofaan** [comment]
I guess we're talking about different parts of the logging life cycle.

>  I agree that /jobs/{job_id}/logs should support a threshold level.

So you mean an option to  filter at  time of requesting the logs @bossie ?

> The original issue is about configuring logging inside the jobs themselves, so that we indeed generate fewer logs by default and can still have more detailed logs if we want it.

Do I understand correctly that you want this to be a job option, so that e.g. debug logs are not done/stored in the first place?

**Comment by bossie** [comment]
> 
> > I agree that /jobs/{job_id}/logs should support a threshold level.
> 
> So you mean an option to filter at time of requesting the logs @bossie ?

Right.

Then again, isn't this already solved by client-side filtering? Why can't they use the OpenEO Web Editor to filter their logs?

**Comment by bossie** [comment]
As discussed: storage is a concern so don't write DEBUG logs at all unless explicitly asked. Drawback is that users will have to re-run their job to include said DEBUG logs.

**Comment by bossie** [comment]
As discussed: make an exception for DEBUG logs originating from calls to `openeo.udf.debug.inspect(..., level="debug")`.

Reasoning: a user that adds these debug inspect calls to his UDF will be surprised to _not_ find them in his logs (because we don't store them by default).

**Comment by bossie** [comment]
Logging threshold for a batch job can be set by means of the "logging-threshold" job_option, e.g.

```python
job_options={
    "logging-threshold": "warning"
}

```
It accepts the log levels as defined in the OpenEO API: "debug", "info", "warning" and "error" and defaults to "info".

Internally they are converted to:
- the Java system property `openeo.logging.threshold`, used in batch_job_log4j.properties (Terrascope) and log4j.properties (Creo);
- the environment variable `OPENEO_LOGGING_THRESHOLD`, used in batch_job.py.

`inspect` logs are unaffected by this threshold (see above).

**Comment by soxofaan** [comment]
I would put that documentation snippet in a new "job_options.md" doc under https://github.com/Open-EO/openeo-geopyspark-driver/tree/master/docs
