### ISSUE TITLE
Problems with "spatial_extent" parameter in `load_collection` process

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-geopyspark-driver#26]
I just tried to recreate the [min evi example](https://openeo.org/openeo/news/2019/03/07/openeo-api-040.html) with the r-client and got an error in load_collection:

`Invalid Extent: ymin must be less than ymax (ymin=48.6, ymax=16.6)`

I have used the order west, east, north, south in that case. Changing it to xmin, xmax, ymin, ymax solved my problem for now, but regarding the process description this was not documented nor is this part of the core processes definition.

**Comment by soxofaan** [comment]
Isn't this an issue for the R client?

The geopyspark driver just receives these bounding box limits under explicit "west", "east", ... keys as specified by the openEO API spec.

**Comment by flahn** [comment]
I gave it another try. The issue #27 occurs now. Anyhow, the response message came from the VITO back-end, but as I cannot replicate it anymore, I will close this issue.
