### ISSUE TITLE
log collection timeout

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#266]
Sometimes not all logs can be retrieved via Python client:

Log collection failed: ConnectionTimeout(\'TIMEOUT\', "HTTPSConnectionPool(host=\'es-infra.vgt.vito.be\', port=443): Read timed out. (read timeout=10)", ReadTimeoutError("HTTPSConnectionPool(host=\'es-infra.vgt.vito.be\', port=443): Read timed out. (read timeout=10)"))'}]

**Comment by soxofaan** [comment]
I think I've also seen integration tests fail because of this

**Comment by bossie** [comment]
Increased read timeout to 60 seconds in the context of https://github.com/Open-EO/openeo-python-driver/issues/151.
