### ISSUE TITLE
support reading geoparquet into vectorcube

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#271]
When working with vector cubes, we need to have file formats that are still manageable when the number of geometries becomes large.
GeoJSON encoding can result in large files.
SHP files are binary, but requires multiple separate files.

GeoParquet is based on Parquet, which is designed for these larger use cases. It can be read by Spark directly, so does not require new libraries. Geometry is encoded as wkb, which is supported by Geotrellis.

GeoPandas can read this format (via gdal), so we could do a first implementation that still reads everything in memory instead of directly to spark rdd. This avoids a larger refactoring of vector cubes.

**Comment by jdries** [comment]
Partially implemented, needs testing

**Comment by jdries** [comment]
@Pratichhya  loading from parquet file now seems to work better (on openeo-dev), can you also try running your sample again?

**Comment by Pratichhya** [comment]
> @Pratichhya loading from parquet file now seems to work better (on openeo-dev), can you also try running your sample again?

@jdries I tested it again over the previous large data that gave the same error, whereas when used with a newly generated sample, it is unable to recognize as a parquet file(I am not sure if it is due to how I generated the file)

**Comment by jdries** [comment]
@Pratichhya do you have a job or request id for that failed test?

**Comment by Pratichhya** [comment]
Yes, when used sample data job id = j-99413a787d6f4da4abf175dfde8b550e and when used previously provided data job id = j-56269673225342a1bee4508f47a15732

**Comment by jdries** [comment]
Is it possible that you tested on production? Can you try on openeo-dev.vito.be?

Jeroen Dries
TAP - Centre for Remote Sensing and Earth Observation Processes
VITO NV | Boeretang 200 | 2400 Mol
tel. +32 14 33 55 11 | ***@***.***<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=mailto%3avoornaam.naam%40vito.be>
***@***.******@***.******@***.******@***.***<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=https%3a%2f%2fwww.facebook.com%2fVITObelgium>
________________________________

**Comment by Pratichhya** [comment]
By openeo-dev.vito.be you mean openeo-0.15.0a1? If so, yes I tested with this version of openeo and geopandas 0.12.2 (i realised that older version does not have read parquet feature)

**Comment by jdries** [comment]
I believe that is the client version, but the fix depends on the backend version, so the url you connect to should be openeo-dev.vito.be?

Jeroen Dries
TAP - Centre for Remote Sensing and Earth Observation Processes
VITO NV | Boeretang 200 | 2400 Mol
tel. +32 14 33 55 11 | ***@***.***<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=mailto%3avoornaam.naam%40vito.be>
***@***.******@***.******@***.******@***.***<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=https%3a%2f%2fwww.facebook.com%2fVITObelgium>
________________________________

**Comment by Pratichhya** [comment]
I guess now I am using openeo-dev.vito.be to connect to the backend, but I still get an error which is different than the previous one for large datasets but for sample data it is the same error.

For previously provided large data job id = j-715aba609adb471c9587c7071f776ec9
For sample data job id = j-db99e4fee66e4a3e96179c8dc183dddb

**Comment by jdries** [comment]
seems to work now!
