### ISSUE TITLE
reporting of credit usage in batch jobs

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#272]
we now log resource usage in marketplace, can we retrieve the resulting credit usage from the marketplace and record it in batch job metadata?
If we use ETL api, the API will return amount of credits when we log resources, so that could be the solution.

**Comment by bossie** [comment]
ETL API description including `/addedvalue` and `/resources` endpoint: https://etl.terrascope.be/docs/

**Comment by bossie** [comment]
- [ ] POST YARN metrics to /resources
- [ ] for each unique process ID, if [allowed](https://nifi-prod-01.vgt.vito.be:8443/nifi/?processGroupId=c227262b-0183-1000-0000-00004d1cec2c&componentIds=fa81ffed-fad5-3d65-be89-b8f98bff3510), POST to /addedvalue
- [ ] if Sentinel Hub costs, POST "shpu" to /resources

**Comment by bossie** [comment]
The effect of these requests can be witnessed in [Kibana](https://kibana-apps.vgt.vito.be/app/kibana#/discover?_g=(filters:!())&_a=(columns:!(type,value,cost,duration),filters:!(),index:ccab6f80-a758-11eb-bc45-753cf0cde572,interval:auto,query:(language:kuery,query:'jobId:%20j-c9df97f8fea046e0ba08705e0fbd9b3b'),sort:!(!(date,desc)))).

**Comment by bossie** [comment]
Implementing retries with `requests`: https://github.com/Open-EO/openeo-python-client/issues/365#issuecomment-1398142616
