### ISSUE TITLE
make k8s batch job yaml template configurable

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#284]
Batch jobs have a number of settings in the yaml file that are fairly static, but may need to be different for entirely new deployments, like we have in C-Scale.

The easiest solution is to allow overriding this file:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/deploy/sparkapplication.yaml.j2
The downside is that it will be harder for other deployments to keep in sync, but it is certainly easier to allow for testing changes to batch job settings.

We can also consider making it a job option, allowing us to change the template in a very quick manner without redeploys.

https://github.com/c-scale-community/use-case-aquamonitor/issues/25

**Comment by soxofaan** [comment]
Tip: jinja2  has this "template inheritance" feature (https://jinja.palletsprojects.com/en/3.1.x/templates/#template-inheritance)  which would allow to override small subsections (instead of the complete template) 
This would minimize the problem of
> will be harder for other deployments to keep in sync,

**Comment by JeroenVerstraelen** [comment]
The template blocks could definitely work, but I wonder what the granularity should be. I could create a separate block for everything one level under root, and then everything one level under spec:
```
{% block metadata %}{% endblock %}
{% block spec %}
...
{% block arguments %}{% endblock %}
{% block dynamicAllocation %}{% endblock %}
{% block sparkConf %}{% endblock %}
{% block volumes %}{% endblock %}
{% block envVars %}{% endblock %}
...
{% endblock %}
```

Then users could replace entire blocks with:
```
{% extends "sparkapplication.yaml.j2" %}
{% block envVars %}
        NEW_ENV_VAR: "TRUE"
{% endblock %}
```
Or extend them with:
```
{% extends "sparkapplication.yaml.j2" %}
{% block envVars %}
{{ super() }}
        NEW_ENV_VAR: "TRUE"
{% endblock %}
```

**Comment by soxofaan** [comment]
For single key-value pairs I think it makes more sense to work with template variables or looping (`{% for ... %}`) through lists (provided as template variable)

I'd use the blocks for a larger granularity level.

**Comment by JeroenVerstraelen** [comment]
I was thinking the same thing at first, but I'm not sure if template variables also allow for default values. I'll double check the docs.

**Comment by JeroenVerstraelen** [comment]
Issue is done.

The sparkapplication.yaml.j2 file now only contains this line by default:
```{% extends "sparkapplication_template.yaml.j2" %}```

Any backend implementation can extend the original template by changing the contents of sparkapplication.yaml.j2 file to e.g.:
```
{% extends "sparkapplication.yaml.j2" %}
{% block driver_envVars %}
        {{ super() }}
        HELLO: "TRUE"
        SOMEVAR: {{ some_var }}
{% endblock %}
```

This means they can also introduce their own template variables.

**Comment by JeroenVerstraelen** [comment]
Correction, it should be {% extends "sparkapplication_template.yaml.j2" %}' instead of {% extends "sparkapplication.yaml.j2" %}.
