### ISSUE TITLE
Start using real config files

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#285]
For some time we are using `ConfigParams` for configuration in the geopyspark driver:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/ec12323cec6c5c2d75d343fdcee883b15a412c5f/openeogeotrellis/configparams.py#L6-L30

This is basically a fairly thin wrapper around environment variables (typically set from private openeo-deploy project).

Using  env vars as a configuration vehicle is a popular, low-cost solution, but it also comes with disadvantages:

- env vars tend to be sprinkled all over the place (jenkins files, docker files, shell scripts, different repo's, ...), making it hard to have an overview and keep track of which value is in use and where it is defined 
- hard to compare dev vs prod config
- limited to strings, no standardized way to work with ints, lists, dicts, nested constructs, etc
- no standardized way or central place to define default/fallback values
- etc

I think we should consider a file based configuration system, where we can load a desired config for: prod, dev, integration tests, creo, ...

**Comment by soxofaan** [comment]
Important aspect to consider is what format: YAML, JSON, INI-style, TOML, ... ?  

FYI: in the aggregator I chose just Python as config format (inspired by comparable options in [flask](https://flask.palletsprojects.com/en/2.2.x/config/#configuring-from-python-files) and [gunicorn](https://docs.gunicorn.org/en/stable/configure.html#configuration-file) ), for example: https://github.com/Open-EO/openeo-aggregator/blob/master/conf/aggregator.dev.py
One can debate that static text config files are conceptually cleaner, compared to dynamic options like a python file. But very often in practice you need some kind of dynamic configuration anyway, and then it gets ugly easily with static config (template layers that generate or interpolate YAML ...). With for example Python you can keep it simple and to the point:
- out of the box data structures as desired (strings, lists, dicts, nesting, enums, ...)
- you still can extract configs from env vars where useful
- allow reuse of common config parts between dev and prod

**Comment by soxofaan** [comment]
FYI: I was pondering about this while working on the elastic job tracker https://github.com/Open-EO/openeo-python-driver/issues/153 , which requires quite a bit of configs, and currently it's quite tedious with env vars in various, non-obvious places

**Comment by JohanKJSchreurs** [comment]
Two ideas I would like to mention:

- ".env" files (AKA the DotEnv format)
- Some people use Pydantic to for configuration

Maybe a `.env` file may gives some of the benefits of both environment variables while keeping everything together in a file (or separate files for prod, testing etc.) It could be a middle ground, or a way to transition to more solid system. 

Though it may have limited support for dynamic config, it has variable expansion at least. And I don't know if it validates and converts strings to the desired type and such. 
One option to process .env files : https://pypi.org/project/python-dotenv/  


However, Pydantic's whole reason of existing is data / input validation. 
It just happens to also be useful for configuration. And it looks like it supports env vars, and .env files among other things.
https://docs.pydantic.dev/usage/settings/


Python code can off course do anything dynamic you could think of. That may however come with a risk of potential security issues. Not sure how big that risk is, but it something to be aware of.

**Comment by soxofaan** [comment]
basics are there now
and documented a bit at https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/docs/configuration.md

closing for now
