### ISSUE TITLE
Make band filtering more consistent

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#29]
Implementation of band filtering and handling is confusing at the moment

in `GeoPySparkLayerCatalog.load_collection`: 
- `s3_jp2_pyramid`, `file_pyramid`, and some others do handle band filtering immediately, while `accumulo_pyramid` and `s3_pyramid` do not
- at the end there is an additional `image_collection.band_filter(band_indices)`, which will probably fail for the cases where band filtering already happened

in `GeotrellisTimeSeriesImageCollection`:
- there is  some stuff going on with `_band_index` which only considers the first band of the list, this is probably a temp hack that has to be eliminated
- `band_filter` does a special case for source type "file", but that is probably not correct anymore (now that that there are multiple source types that handle band filtering up front)

**Comment by jdries** [comment]
In GeotrellisTimeSeriesImageCollection:
* _band_index got removed, now see what tests tell us

**Comment by jdries** [comment]
Also cleaned up layercatalog a bit. The idea is now that the pyramidFactories are responsible for applying the band filter directly.

**Comment by soxofaan** [comment]
great, thanks
