### ISSUE TITLE
k8s: cancel job before delete

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#290]
When deleting a running job on creo, the job gets deleted, but not on the cluster, so continues to run.
Cancel the job before deleting it.
Clean up any resources in object storage upon delete?

**Comment by JeroenVerstraelen** [comment]
Also ensure that cancelled jobs are still stored somewhere and not completely removed. (JobTracker)

**Comment by JeroenVerstraelen** [comment]
Delete job now also deletes the job on the cluster.

A call to delete job should already delete the batch job directory on s3 object storage:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/ee339a58555ed43373870bc64127c33e4bbff9f3/openeogeotrellis/backend.py#L2188

While a call to cancel/stop job will leave the batch job directory on s3 object storage as is, with the intention that old directories will be cleaned up by some cron job.

When testing delete_job I did notice that the batch job directory remains on s3 object storage (it still contains job_specification.json). I'm looking further into it.

**Comment by JeroenVerstraelen** [comment]
The call to delete was specifically for sentinelhub object storage.

https://github.com/Open-EO/openeo-geopyspark-driver/commit/2cc659dbb43506d334cebc8aeea55626b4a7f520
Should now also delete the batch job dir on Creodias.

**Comment by bossie** [comment]
FYI, SHub batch _process_ (≠ OpenEO batch _job_): https://docs.sentinel-hub.com/api/latest/api/batch/

It also makes use of S3 storage so that makes it extra confusing. :upside_down_face:
