### ISSUE TITLE
allow custom asset names

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#291]
for tiff, assets are now named openEO.tif, forcing the user to rename the assets when running many jobs.
If the asset name includes the job title, (if it is set), we can avoid this.

**Comment by soxofaan** [comment]
or include (part of) the job id in the asset name (too).


@m-mohr  do you think there is room for asset naming recommendations on the level of API here?

**Comment by m-mohr** [comment]
No, I don't think so as this has nothing to do with the API and is usually file format specific. Also the file names shouldn't matter too much (as long as they are not always the same) as they can be explored from the STAC metadata...

**Comment by soxofaan** [comment]
I was thinking about this bit of the spec about job result asset key:

>  The keys MAY be used by clients as file names.

and adding something like "so it is RECOMMENDED to use keys that make meaningful file names". But maybe that is kind of implied for the attentive reader.

Side-question: is it allowed to have special characters like `/` in the asset key or should the spec limit that?

(FYI: the python client blindly uses the asset keys as filename at the moment unless user explicitly sets a file name)

**Comment by m-mohr** [comment]
In STAC itself the key doesn't have a meaning and is not limited in characters. So STAC lients get the filenames from the href (or `file:local_path`). 

Adding this sentence above to the spec might now have been the wisest decision. Having a slash is allowed though and should probably not be restricted as there are file formats that are structured in folders (zarr, geopackage?)

**Comment by jdries** [comment]
Pointers to where asset names are currently set (a bit all over the place):

https://github.com/Open-EO/openeo-geotrellis-extensions/blob/develop/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala#L126
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/develop/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala#L418
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/geopysparkdatacube.py#L1634
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/geopysparkdatacube.py#L1711

Note that we can now save multiple results, so it may make sense to be able to control asset name in the arguments of the save_result call (so format options).

**Comment by EmileSonneveld** [comment]
Work in progress...
For `openeo-geotrellis-extensions`, it was already possible to specify something in the filename by passing the `sampleNames` argument in `saveSamples`.
For `saveRDDTemporal`, I added a field to `GTiffOptions` to pass a name.
I'll go over `openeo-geopyspark-driver` once I set up my dev environment here...
