### ISSUE TITLE
support writing multiple results

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#295]
See: https://github.com/Open-EO/openeo-api/issues/427
We are getting requests to have one job write multiple assets, for instance results of intermediate steps. This means supporting multiple 'save_result' nodes in the same process graph.

**Comment by GriffinBabe** [comment]
In the cropclass project, one of my current tickets ask me to save preprocessed features before performing classification in the inference workflow. 

I think that the feature proposed in this issue is necessary to implement this ticket efficiently
