### ISSUE TITLE
API spec incompatibilities

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-geopyspark-driver#3]
This list became a bit extensive, I just wrote down everything that I spotted, hope it helps :)

---

Most important to get the Hub working:

- [x] `GET /collections` doesn't wrap the collections array into a `collections` property and misses `links` property. Output should be like this:

````
{
    "collections": [
        <array here as you already output it>
    ],
    "links": [
        <required, but can be empty>
    ]
}
````

- [x] `GET /processes`: same as above: array that is currently returned should be wrapped into `processes` property and required `links` property is missing

(The links are not really needed by the Hub, but I mentioned that here since while you're at it you can just add them too.)

---

Nice to add more content to the Hub:

- [x] `GET /output_formats` and `GET service_types` are not listed in `/`'s `endpoints` array

Those endpoints exist and are spec-compliant (:+1:), but not added to the Hub yet because they're not listed in the capabilities :(

---

Needed to display collections correctly:

- [x] The second collections in `GET /collections` looks alright-ish, but the others contain less properties. Can they all look the same?

From now I'm referring to what the second collection looks like.

- [x] Non-spec `data_id` and `product_id` are present (which is okay), but not the required `name` property (which is *really* needed!)
- [x] `extent` property should be object with two sub-properties `spatial` and `temporal`
- [x] that `spatial` property needs a bounding box in array form
- [x] that `temporal` property should contain what is currently in `time`

That should get the rendering working.

For completeness (the Hub doesn't really care about those properties (yet), but FYI):

- [x] required `license` property missing
- [x] required `links` property missing

---

Needed to display processes correctly:

- [x] process identifier should be named `name` instead of `process_id`
- [x] required `returns` property is missing

**Comment by jdries** [comment]
Deployed a new version containing the most urgent fixes!

**Comment by christophfriedrich** [comment]
Thanks, the processes are already looking good!

The `/collections` endpoint returns `{"message": "Expecting ',' delimiter: line 15 column 7 (char 473)"}` -- maybe an invalid metadata input file?

**Comment by jdries** [comment]
Oops, I redeployed, can you try again?

**Comment by christophfriedrich** [comment]
At first I had no luck:
> "An error occurred while calling o980.seqToIterable. Trace:\npy4j.Py4JException: Method seqToIterable([class geotrellis.spark.LayerId]) does not exist\n\tat py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)\n\tat py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)\n\tat py4j.Gateway.invoke(Gateway.java:274)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\n\n"

But then I tried again and I received a response (the server response took fairly long though :thinking:).

-> The Hub can now principally import the backend!

Processes, output formats and service types are displayed well; rendering of the collections fails because for that to work *all* items must have the compatible structure, not just one. The version is not shown either, but I think that error is linked to the collections issue (the Hub's post-processing of backend metadata comes after the collections, so when failing at collections the rest fails too).

Spotted: `extent.spatial` is supposed to be an array of numbers, not an object.

Showcase of current state (processes collapsed because they are too long to fit on the screenshot; collections are expanded but not shown due to rendering errors due to incompatible structure of some items):

![grafik](https://user-images.githubusercontent.com/17781682/50974915-966bdf00-14ec-11e9-8712-c6c450c2c9f3.png)

**Comment by jdries** [comment]
I updated all layer metadata, please try again!
