### ISSUE TITLE
Eleminate service registry and WMTS dependencies from GeotrellisTimeSeriesImageCollection

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#30]
GeotrellisTimeSeriesImageCollection has a dependency on InMemoryServiceRegistry and WMTS/tms details

```python

class GeotrellisTimeSeriesImageCollection(ImageCollection):

    def __init__(self, pyramid: Pyramid, service_registry: InMemoryServiceRegistry, metadata: CollectionMetadata = None):
        # ...
        self.tms = None
        self._service_registry = service_registry
```

all this baggage is there just for a single method `tiled_viewing_service`, which seems a bit backward. I think it would be cleaner to refactor these details out of the GeotrellisTimeSeriesImageCollection class

**Comment by jdries** [comment]
Agreed, the design would be more modular if the viewing service support is moved to a separate class. This would make it easier to reuse those components separate from each other.

**Comment by jdries** [comment]
This was fixed here:
https://github.com/Open-EO/openeo-geopyspark-driver/commit/3f52e9272b74360a683cd6cb6ad9607fc54ce1d9
