### ISSUE TITLE
filter_temporal should be left-closed

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#34]
@lforesta  noted that `filter_temporal` (and the related argument in `load_collection`) on the VITO backend does not exclude the end date of the data selection as specified in the process specification https://open-eo.github.io/openeo-api/processreference/#filter_temporal:

> extent
> Left-closed temporal interval, i.e. an array with exactly two elements:
>  1.    The first element is the start of the date and/or time interval. The specified instance in time is included in the interval.
>  2.  The second element is the end of the date and/or time interval. The specified instance in time is excluded from the interval.

**Comment by soxofaan** [comment]
example:

![Screenshot from 2020-01-23 10-46-56](https://user-images.githubusercontent.com/44946/72973534-b86d9200-3dcd-11ea-846d-dde44e281eaf.png)

**Comment by bossie** [comment]
Pending a final solution, this is worked around in some places e.g. https://github.com/Open-EO/openeo-geotrellis-extensions/blob/9ce404a57dea9b0d60d9b9a5d559d096317fac29/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/OpenSearch.scala#L33-L38

**Comment by soxofaan** [comment]
This issue (VITO implementation using left+right closing temporal intervals) came up again in dev telco, e.g. see https://github.com/Open-EO/openeo-processes/issues/331 and https://github.com/Open-EO/openeo-processes/pull/394

**Comment by soxofaan** [comment]
I think we should address this, because apparently all other back-end implementations follow the spec (left closed intervals), so this will start giving portability issues

**Comment by jdries** [comment]
In catalog clients:
if start and end date are the same => modify end date to be at end of day
in oscars client, there is an additional filter  after loading features, this needs to respect the left-closed behaviour

**Comment by jdries** [comment]
Started a branch:
https://github.com/Open-EO/openeo-opensearch-client/tree/left_closed

**Comment by bossie** [comment]
Shouldn't this test (and others) have started failing since these changes?

https://github.com/Open-EO/openeo-geopyspark-integrationtests/blob/f7dc85a8ebbb717e48776df265c210941da88600/tests/test_integration.py#L175

**Comment by jdries** [comment]
No, to prevent all-out failure of cases where start and end date is the same, we treat this as a special case.
