### ISSUE TITLE
rasterio dependency

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#340]
https://github.com/Open-EO/openeo-geopyspark-driver/blob/b4b65f50b3a92b38c6e5821b889fcef21476cae1/setup.py#L63

The only place `rasterio` is used in main project is at https://github.com/Open-EO/openeo-geopyspark-driver/blob/b4b65f50b3a92b38c6e5821b889fcef21476cae1/openeogeotrellis/geopysparkdatacube.py#L2022-L2025

But as far as I can see, this `_save_stitched_tiled` is not used anymore (last usage removed in 8e3652f3c70ef09e5cba67dad3f9c260e516104f ?)

rasterio is however used in a couple of unit tests

So I think we can just drop rasterio as `install_requires` dependency and move it to the test dependencies

**Comment by soxofaan** [comment]
@jdries  ok to drop rasterio as `install_requires` dependency, and remove `_save_stitched_tiled`?

**Comment by soxofaan** [comment]
cc @EmileSonneveld

**Comment by EmileSonneveld** [comment]
My problem with rasterio got fixed by switching from Python 3.10 to 3.8.

**Comment by jdries** [comment]
Ok as proposed!

**Comment by soxofaan** [comment]
hmm apparently rasterio is an undeclared dependency of geopyspark

will revert

**Comment by soxofaan** [comment]
related:
- https://github.com/locationtech-labs/geopyspark/issues/683
- https://github.com/locationtech-labs/geopyspark/pull/706

**Comment by soxofaan** [comment]
fixed for now

ideally we fix the dependency declaration bug in our custom fork https://github.com/Open-EO/geopyspark , but that's probably not worth the effort for now
