### ISSUE TITLE
move oidc providers into config file

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#344]
OIDC providers are now hard-coded here:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/backend.py#L386
This needs to be moved into a config file so that we can configure a backend with one oidc provider.

**Comment by soxofaan** [comment]
depends/relates to #285

**Comment by soxofaan** [comment]
still waiting for a successful integration test run to double check latest tweaks 

in mean time, wrote some initial documentation about this: https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/docs/configuration.md#config-files

**Comment by soxofaan** [comment]
seems to work for the terrascope deploy, but also has to be handled for kube/creodias deploys. 
Still struggling to properly understand how this kube config stuff works though

**Comment by JeroenVerstraelen** [comment]
Created the `backend-config` configMap with data:
```
  data = {
    "backendconfig.py" = file(var.backend_config_file)
  }
```
Where backend_config_file is set to `backendconfig_dev.py` or backendconfig_prod.py depending on the type of deployment.

The configMap is mounted at /opt/backend_config/backendconfig.py and the OPENEO_BACKEND_CONFIG environment variable points to this path.

Result:
https://openeo-dev.creo.vito.be/openeo/1.1/credentials/oidc now shows the oidc providers defined in the backendconfig_dev.py file. 

The config files can be edited on the os_creodias_openeo_k8s bitbucket repository under:
`os_creodias_openeo_k8s/browse/kube_resources/applications/openeo/backendconfig_dev.py`

**Comment by soxofaan** [comment]
nice!
thanks
