### ISSUE TITLE
improve handling of error "Requested band '...' is not present in Sentinel 1 tile ..."

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#350]
Users keep asking what the deal is with this error:

> Your openEO batch job failed during Spark execution: 'Sentinel Hub returned an error\nresponse: HTTP/1.1 400 Bad Request with body: {"error":{"status":400,"reason":"Bad Request","message":"Requested band \'VH\' is not present in Sentinel 1 tile \'S1B_EW...'

to which our usual reply is: include a polarization filter in your `load_collection`:

```python
properties={"polarization":lambda p: p == "DV"}
```

Can we do something to avoid this?

Context: https://github.com/openEOPlatform/architecture-docs/issues/155

**Comment by bossie** [comment]
Original Sentinel Hub error:
```json
{
  "error": {
    "status": 400,
    "reason": "Bad Request",
    "message": "Requested band 'VH' is not present in Sentinel 1 tile 'S1B_EW_GRDM_1SDH_20200107T154819_20200107T154919_019713_025452_EC0F' returned by criteria specified in `dataFilter` parameter.",
    "code": "RENDERER_S1_MISSING_POLARIZATION"
  }
}
```

Process graph: [process_graph.json.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/10821533/process_graph.json.txt)

**Comment by jdries** [comment]
FYI, filtering on polarization property is no longer recommended, there is a less ambiguous STAC property:

```
properties={                                  
     "sar:instrument_mode": lambda p: p == "IW"
}
```

**Comment by jdries** [comment]
My previous remark was not entirely correct, as there seem to exist IW products with a different polarization as well:
S1A_IW_GRDH_1SDH_20160713T173234_20160713T173303_012133_012CB5_35C2

**Comment by jdries** [comment]
It's indeed problematic, my suggestion:
- the error message could be better, as in 'load_collection for Sentinelhub collection SENTINEL1_GRD returned: Requested band 'VH' is not present in Sentinel 1 tile 'S1B_E ' 
- We can detect the case before even trying: using SENTINEL1_GRD without property filters is problematic, so either set default properties or throw an error. Throwing an error at this point can break existing cases, so my suggestion is setting defaults.

**Comment by EmileSonneveld** [comment]
Requesting with polarisation, the error message is already understandable: 
`OpenEO batch job failed: org.openeo.geotrellissentinelhub.package$NoSuchFeaturesException: no features found for criteria: collection ID "sentinel-1-grd" 1 polygon(s) [2017-03-01T00:00:00+00:00, 2017-03-10T00:00:00+00:00] metadata properties {polarization={eq=SH}}`  Introduced here: https://github.com/Open-EO/openeo-geotrellis-extensions/issues/128

Without polarisation, the error looks like this:
```OpenEO batch job failed: Exception during Spark execution: Sentinel Hub returned an error response: HTTP/1.1 400 Bad Request with body: {"error":{"status":400,"reason":"Bad Request","message":"Requested band 'HH' is not present in Sentinel 1 tile 'S1A_IW_GRDH_1SDV_20170307T043502_20170307T043527_015581_0199D9_5D7F' returned by criteria specified in `dataFilter` parameter.","code":"RENDERER_S1_MISSING_POLARIZATION"}} request: POST https://services.sentinel-hub.com/api/v1/process with (possibly abbreviated) body: { "input": { "bounds": { "bbox": [543520.0, 9524710.0, 546080.0, 9527270.0], "properties": { "crs": "http://www.opengis.net/def/crs/EPSG/0/32733" } }, "data": [ { "type": "sentinel-1-grd", "dataFilter": {"timeRange":{"from":"2017-03-07T00:00:00Z","to":"2017-03-08T00:00:00Z"}}, "processing": {"backCoeff":"GAMMA0_TERRAIN","orthorectify":true} } ] }, "output": { "width": 256, "height": 256, "responses": [ { "identifier": "default", "format": { "type": "image/tiff" } } ] }, "evalscript": "//VERSION=3\nfunction setup() {\n return {\n input: [{\n \"bands\": [\"HH\"]\n }],\n output: {\n bands: 1,\n sampleType: \"FLOAT32\",\n }\n };\n}\n\nfunction evaluatePixel(sample) {\n return [sample.HH];\n}" }```

```Python
import os
import datetime
import openeo

connection = openeo.connect("openeo-dev.vito.be").authenticate_oidc()
print(connection.root_url + " time: " + str(datetime.datetime.now()))

kinshasa_extent = {"west": 15.3, "south": -4.3 - 0.1, "east": 15.3 + 0.1, "north": -4.3}
datacube = connection.load_collection(
    "SENTINEL1_GRD",
    spatial_extent=kinshasa_extent,
    temporal_extent=["2017-03-01", "2017-03-10"],
    bands=["HH"],
    # properties={"polarization":lambda p: p == "SH"} # ENABLE/DISABLE
)

# save graph for debugging:
out_path = "out-" + str(datetime.datetime.now()).replace(":", "_")
os.mkdir(out_path)
datacube.print_json(file=os.path.join(out_path, "datacube_print_json.json"))

job = datacube.create_job()  # Creating a new job at the back-end

# Starts the job and waits until it finished to download the result.
job.start_and_wait()
job.get_results().download_files(out_path)
```

**Comment by jdries** [comment]
yes, so now the idea is to check the list of requested bands, and set the polarization accordingly.
This table can help with this:
https://docs.sentinel-hub.com/api/latest/data/sentinel-1-grd/#available-bands-and-data

So for instance, bands are set to VV and VH, polarization can only be DV
HV and HH bands => polarization = DH

**Comment by bossie** [comment]
This smaller process graph might be more convenient to reproduce the problem and derive a test case from: https://discuss.eodc.eu/t/datacube-cannot-be-stored-locally/326/1

**Comment by EmileSonneveld** [comment]
@jdries , If the user specifies only the HH-band, polarization can not be automatically determined, because it could be "SH" or "HH". Ok to show a warning in this case?
Or should we pick a polarisations by default. (Same goes for VV-band)

**Comment by EmileSonneveld** [comment]
So when asking for the HH-band and the VV-band, it is not really possible to determine a polarisation too

**Comment by jdries** [comment]
no, just don't do anything in the cases where no obvious default can be chosen (these are rare cases)

**Comment by EmileSonneveld** [comment]
Ok, then this PR is ready: https://github.com/Open-EO/openeo-geotrellis-extensions/pull/146

There is a unit test. This snippet should run fine after the fix is deployed:
```Python
import os
import datetime
import openeo

connection = openeo.connect("openeo-dev.vito.be").authenticate_oidc()
now = datetime.datetime.now()
print(connection.root_url + " time: " + str(now))

atlantis_extent = {"west": -30, "south": 57 - 0.1, "east": -30 + 0.1, "north": 57}  # no relevant sentinel data here
input_geojson = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [6.42, 51.03],
                        [6.42, 51.11],
                        [6.54, 51.11],
                        [6.54, 51.03]
                    ]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [atlantis_extent["west"], atlantis_extent["south"]],
                        [atlantis_extent["west"], atlantis_extent["south"]],
                        [atlantis_extent["east"], atlantis_extent["north"]],
                        [atlantis_extent["east"], atlantis_extent["north"]]
                    ]
                ]
            }
        }
    ]
}

datacube = connection.load_collection(
    "SENTINEL1_GRD",
    temporal_extent=["2017-03-01", "2017-03-15"],
    bands=["VV", "VH"],
    # properties={"polarization": lambda p: p == "DV"}  # Will now be automatically set.
)

datacube = datacube.filter_spatial(input_geojson)
# save graph for debugging:
out_path = "out-" + str(now).replace(":", "_")
os.mkdir(out_path)
datacube.print_json(file=os.path.join(out_path, "datacube_print_json.json"))

job = datacube.create_job(title=os.path.basename(__file__))
job.start_and_wait()
job.get_results().download_files(out_path)

```

**Comment by EmileSonneveld** [comment]
Fixed by this merge: https://github.com/Open-EO/openeo-geopyspark-driver/pull/410
