### ISSUE TITLE
Single row/line results with SENTINEL2_L2A

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#375]
```python
con = openeo.connect("openeo.vito.be").authenticate_oidc()
cube = con.load_collection(
    collection_id="SENTINEL2_L2A",
    temporal_extent=["2022-09-05", "2022-09-20"],
    spatial_extent={"west": 5.071, "south": 51.21, "east": 5.1028, "north": 51.23},
    bands =["B02", "B03"],
)
cube = cube.save_result(format="GTIFF")
cube.execute_batch...
```
(e.g batch job `j-f757a4cf89714ac9a16c36e333dcee3a`)

results in 5 tiff files (one per date), with 2 bands. The second band looks fine, but the first band has only one row or column of pixels

For example: quick visualization of the top left 10x10 pixels of these images:

![Screenshot from 2023-03-24 11-16-07](https://user-images.githubusercontent.com/44946/227494377-0e1b829d-e04c-4e2f-b68e-fde36d43f369.png)

**Comment by EmileSonneveld** [comment]
The requested area is on the edge of 2 sentinelhub tiles. The result has only pixels from the tile it is overlapping the least with. From 2022-09-19.
I'll check why
![image](https://user-images.githubusercontent.com/2298426/227570018-5007d1e0-dfb1-40df-a1ad-5d9bd3de3993.png)

**Comment by jdries** [comment]
Normally, this assumption of top-left corner should be enforced by this preprocessing function:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/fb91f01aa4f60b9b1a450191350a7ad5a1e3bac3/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala#L162

**Comment by EmileSonneveld** [comment]
The issue also disappears when reverting this commit: https://github.com/Open-EO/openeo-geotrellis-extensions/commit/368b43e35101f5baf2c193691816e851debc2257
It is a buffer zone that get's added just after the check you mention.
Also the fix in my MR fixes it. I'll check if the NaN lines are still a problem too

Both ways of fixing it gives a result like this:
![image](https://user-images.githubusercontent.com/2298426/227997167-dcd29a07-cead-47ae-8b11-2e189e9302ec.png)
The red dots indicate the corners of the requested area. It does not looks to be matching in the x-dimention.

**Comment by jdries** [comment]
Nice catch! So probably my attempt to add a buffer indeed also introduced extra tiles, which then broke the assumption further downstream?

**Comment by soxofaan** [comment]
probably related/duplicate issue: https://github.com/openEOPlatform/architecture-docs/issues/317

**Comment by soxofaan** [comment]
I can confirm that the original issue I reported here is fixed when using latest "openeo-dev.vito.be":

![Screenshot from 2023-03-30 13-48-26](https://user-images.githubusercontent.com/44946/228826902-e6289308-a6a4-46a7-8d29-3ebd2cc7b310.png)
