### ISSUE TITLE
drop obsolete user_facing_logger in batch_job.py

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#386]
If I recall correctly, `user_facing_logger` (<-> general YARN logging not visible to the user) was added in EP-3167 to make it possible for a user to look up the error/reason why a particular batch job failed. Centralized logging has since made it possible to also look up this error (and the rest of the logs) so its output file `$job_dir/log` became redundant; it seems this file is  no longer read anyway.

**Comment by bossie** [comment]
Should be a matter of replacing `user_facing_logger` with the general `logger` instance. It's also no longer necessary to pass the `log` file to `submit_batch_job_spark3.sh` etc.

**Comment by soxofaan** [comment]
yeah, I was also wondering about the use of that logger while discussing some logging related matter with @EmileSonneveld recently

**Comment by soxofaan** [comment]
I think the existence and usage of `user_facing_logger`  is fine, it's just the `_setup_user_logging()` call (and definition) that should be eliminated

**Comment by bossie** [comment]
It has no use anymore: 0f13214f7107f06c5e3414052f94af135288edd3

**Comment by bossie** [comment]
All traces of this logger and the `log` files that it writes to have been removed; the general `openeogeotrellis.deploy.batch_job` logger takes over its duties.
