### ISSUE TITLE
kubecost usage retrieval is broken

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#396]
As witnessed in the context of #387, kubecost usage retrieval is broken in `job_tracker_v2`:

```
Failed to retrieve usage stats from kubecost

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 298, in _get_usage
    raise K8sException(
K8sException: Unexpected response {'code': 200, 'data': [{}]}
```

This is also the case in the original `job_tracker` (no stack trace):

`Unable to retrieve job cost {'code': 200, 'data': [{}]}`

**Comment by jdries** [comment]
I think this is fixed, can you check again?

**Comment by bossie** [comment]
No errors but can't seem to find logs for a successful cost retrieval either. Investigating.

**Comment by bossie** [comment]
Looks like there are some issues with logs not being visible in Kibana but I got this one straight from the pod:

> Failed to retrieve usage stats from kubecost: ConnectionError: HTTPSConnectionPool(host='opencost.openeo-cdse-staging.vgt.vito.be', port=443): Max retries exceeded with url: /api/allocation?aggregate=namespace&filterNamespaces=spark-jobs-staging&filterPods=job-29abf1cad9-32cc7ddb-f7e1-4b1c-9%2A&window=5d&accumulate=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b3b5ee640>: Failed to establish a new connection: [Errno 110] Connection timed out'))

```
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4b3b5ee640>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/openeo/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opencost.openeo-cdse-staging.vgt.vito.be', port=443): Max retries exceeded with url: /api/allocation?aggregate=namespace&filterNamespaces=spark-jobs-staging&filterPods=job-29abf1cad9-32cc7ddb-f7e1-4b1c-9%2A&window=5d&accumulate=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b3b5ee640>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 289, in _get_usage
    response = requests.get(url, params=params)
  File "/opt/openeo/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='opencost.openeo-cdse-staging.vgt.vito.be', port=443): Max retries exceeded with url: /api/allocation?aggregate=namespace&filterNamespaces=spark-jobs-staging&filterPods=job-29abf1cad9-32cc7ddb-f7e1-4b1c-9%2A&window=5d&accumulate=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b3b5ee640>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by bossie** [comment]
Resource logging is reported working but currently done to Terrascope ETL API.

TODO:

- [ ] point job_tracker_v2 on CDSE to dedicated CDSE ETL API (staging: https://marketplace-cost-api-stag-warsaw.dataspace.copernicus.eu/, see https://confluence.vito.be/display/CDSE/CDSE+marketplace+deployment)

**Comment by bossie** [comment]
API call is successful after URL fix:

> Successfully retrieved total cost {'name': 'spark-jobs-staging', 'properties': {'cluster': 'default-cluster', 'namespace': 'spark-jobs-staging', 'labels': {'kubernetes_io_metadata_name': 'spark-jobs-staging'}}, 'window': {'start': '2023-06-02T10:59:06Z', 'end': '2023-06-07T10:59:06Z'}, 'start': '2023-06-02T10:59:06Z', 'end': '2023-06-07T10:55:00Z', 'minutes': 7195.89381, 'cpuCores': 18.49875, 'cpuCoreRequestAverage': 18.49875, 'cpuCoreUsageAverage': 0.32546, 'cpuCoreHours': 2218.58414, 'cpuCost': 28.84159, 'cpuCostAdjustment': 0, 'cpuEfficiency': 0.01759, 'gpuCount': 0, 'gpuHours': 0, 'gpuCost': 0, 'gpuCostAdjustment': 0, 'networkTransferBytes': 9518607897486.943, 'networkReceiveBytes': 370841160371254.75, 'networkCost': 0, 'networkCrossZoneCost': 0, 'networkCrossRegionCost': 0, 'networkInternetCost': 0, 'networkCostAdjustment': 0, 'loadBalancerCost': 0, 'loadBalancerCostAdjustment': 0, 'pvBytes': 0, 'pvByteHours': 0, 'pvCost': 0, 'pvs': None, 'pvCostAdjustment': 0, 'ramBytes': 114453758402.14207, 'ramByteRequestAverage': 114453758402.1436, 'ramByteUsageAverage': 59788960638.90989, 'ramByteHours': 13726618190410.434, 'ramCost': 41.54771, 'ramCostAdjustment': 0, 'ramEfficiency': 0.52239, 'externalCost': 0, 'sharedCost': 0, 'totalCost': 70.3893, 'totalEfficiency': 0.31555, 'rawAllocationOnly': None, 'proportionalAssetResourceCosts': None}

**Comment by bossie** [comment]
Applicable envars for job_tracker_v2:

```
OPENEO_ETL_API=https://marketplace-cost-api-stag-warsaw.dataspace.copernicus.eu
OPENEO_ETL_API_OIDC_ISSUER=https://cdasid.cloudferro.com/auth/realms/CDAS
OPENEO_ETL_OIDC_CLIENT_ID=???
OPENEO_ETL_OIDC_CLIENT_SECRET=!!!
```

**Comment by bossie** [comment]
All CDSE OpenEO's should log their resources in CDSE stag cost API (checked in kibana-1.stag, accessible from my user VM).

Tested with:

```python
connection = openeo.connect("https://openeo-staging.creo.vito.be").authenticate_oidc("CDSE-staging")

data_cube = (connection.load_collection("SENTINEL2_L2A")
             .filter_bands(["B04", "B03", "B02"])
             .filter_bbox([2.59003, 51.069, 2.8949, 51.2206])
             .filter_temporal(["2019-09-21", "2019-09-21"]))

data_cube.execute_batch("/tmp/test_batch_job_geotiff_on_cdse_s2l2a.tif", title="sentinel2-l2a",
                        job_options={'logging-threshold': "debug"})
```

However, there seems to be a problem wrt/ the user (`error_internal_user_not_found`):

```json
{
  "jobId": "j-3fc825b5f2dc4c7194117f324e007db5",
  "jobName": "sentinel2-l2a",
  "executionId": "job-3fc825b5f2-df7ea45d-ecc4-453f-8",
  "state": "FINISHED",
  "userId": "df7ea45d-ecc4-453f-8af9-de8cfb1058b1",
  "sourceId": "TerraScope/MEP",
  "orchestrator": "openeo",
  "status": "error_internal_user_not_found",
  "type": "processing",
  "value": 0,
  "unit": "shpu",
  "cost": 0,
  "date": "2023-06-09T13:28:19.000Z",
  "duration": 65000
}
```

**Comment by bossie** [comment]
@JanssenBrm now handles Keycloak IDs so instead of an `error_internal_user_not_found`, we get an `error_marketplace_user_not_found`.

**Comment by bossie** [comment]
The internal kubecost URL for prod and staging are the same so no need to accommodate on the application level:

> opencost.opencost.svc.cluster.local:9003/allocation
> They run in a different cluster, so it doesn't resolve to the same opencost pod

**Comment by bossie** [comment]
The OpenCost endpoint doesn't seem to take the namespace/pod filters into account so these requests return roughly the same results (= all namespaces instead of a single one, for all pods etc -> very big numbers):

```
curl http://opencost.opencost.svc.cluster.local:9003/allocation \
-G \
--data-urlencode window=1d \
--data-urlencode aggregate=namespace \
--data-urlencode accumulate=true
```

```
curl http://opencost.opencost.svc.cluster.local:9003/allocation \
-G \
--data-urlencode window=1d \
--data-urlencode aggregate=namespace \
--data-urlencode accumulate=true \
--data-urlencode filterNamespaces=spark-jobs-staging \
--data-urlencode filterPods=openeo-geotrellis-0-driver
```

I've tried v2 filters as well, makes no difference.

**Comment by tcassaert** [comment]
Using the following query + `jq` I can get a totalCost that's also represented in the opencost UI:
```
curl -XGET http://opencost.opencost.svc.cluster.local:9003/model/allocation/compute\?window\=today\&aggregate\=namespace\&step\=1d\&accumulate\=false | jq '.data[]."spark-jobs-dev"."totalCost"'
```
It does seem to be a resource heavy query, so it's not ideal, but at least you can get the numbers.

For a specific pod:

```
curl -XGET http://opencost.opencost.svc.cluster.local:9003/model/allocation/compute\?window\=today\&aggregate\=pod\&step\=1d\&accumulate\=false | jq '.data[]."openeo-geotrellis-0-f16aa088c498465f-exec-11"'
```

**Comment by tcassaert** [comment]
Also found this issue: https://github.com/opencost/opencost/issues/1772

**Comment by bossie** [comment]
At the request of @JanssenBrm, prod CDSE now logs to prod ETL API.

**Comment by tcassaert** [comment]
Pod/namespace metrics could also be retrieved from Prometheus directly:

`container_cpu_usage_seconds_total{pod="openeo-geotrellis-0-driver"}`

`container_memory_usage_bytes{namespace="spark-jobs-dev"}`

**Comment by bossie** [comment]
Prometheus staging: https://prometheus.openeo-cdse-staging.vgt...
Prometheus prod: https://prometheus.openeo-cdse-prod.vgt...

**Comment by bossie** [comment]
CPU, memory and network usage queries for job-90206ae556-df7ea45d on staging:

- CPU usage in cpu-seconds: `sum(container_cpu_usage_seconds_total{pod=~"job-90206ae556-df7ea45d-.+", container!=""})`
- Network usage in bytes: `sum(container_network_receive_bytes_total{pod=~"job-90206ae556-df7ea45d-.+"})`
- Memory usage in byte-seconds: `sum(avg_over_time(container_memory_usage_bytes{pod=~"job-90206ae556-df7ea45d-.+", container!=""}[5d])) * 52` where 52 is the job duration in seconds (is this right?)

**Comment by bossie** [comment]
Not yet merging because it's not clear which time series to include in the sum. In particular, time series 4 has substantial CPU usage but no `container` or `image` label:

https://prometheus.openeo-cdse-staging.vgt.vito.be/graph?g0.expr=container_cpu_usage_seconds_total%7Bpod%3D~%22job-90206ae556-df7ea45d-.%2B%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1w&g0.end_input=2023-06-22%2011%3A32%3A44&g0.moment_input=2023-06-22%2011%3A32%3A44

Then there's those `pause` containers.

Possibly relevant: https://stackoverflow.com/questions/70530385/prometheus-different-results-same-pod

**Comment by bossie** [comment]
As discussed: include all time series = potentially charge too much.

**Comment by bossie** [comment]
My job on CDSE dev was able to get its usage from Prometheus (double-checked in Prometheus UI):

> logging resource usage {'jobId': 'j-2151e9ae279a4ab398d25de7898ce441', 'jobName': 'sentinel2-l2a', 'executionId': 'job-2151e9ae27-df7ea45d-ecc4-453f-8', 'userId': 'df7ea45d-ecc4-453f-8af9-de8cfb1058b1', 'sourceId': 'cdse', 'orchestrator': 'openeo', 'jobStart': 1688038303000.0, 'jobFinish': 1688038390000.0, 'state': 'FINISHED', 'status': 'UNDEFINED', 'metrics': {'cpu': {'value': 69.582413132, 'unit': 'cpu-seconds'}, 'memory': {'value': 395596.4765625, 'unit': 'mb-seconds'}, 'time': {'value': 87000.0, 'unit': 'milliseconds'}}} at https://marketplace-cost-api-stag-warsaw.dataspace.copernicus.eu

This (failed because of something unrelated) Jenkins job on CDSE dev, however, was not (nothing in the Prometheus UI either):

```
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 285, in _get_usage
    byte_seconds = prometheus.get_memory_usage(application_id, application_duration_s)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/prometheus.py", line 44, in get_memory_usage
    return self._query_for_value(query, at)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/prometheus.py", line 22, in _query_for_value
    value = float(resp.json()['data']['result'][0]['value'][1])
IndexError: list index out of range
```

> logging resource usage {'jobId': 'j-d8af22f792f64297bbf7a9665d93c805', 'jobName': None, 'executionId': 'job-d8af22f792-cdse-ci-service-acco', 'userId': 'cdse-ci-service-account', 'sourceId': 'cdse', 'orchestrator': 'openeo', 'jobStart': 1688036621000.0, 'jobFinish': 1688036645000.0, 'state': 'FAILED', 'status': 'UNDEFINED', 'metrics': {'time': {'value': 24000.0, 'unit': 'milliseconds'}}} at https://marketplace-cost-api-stag-warsaw.dataspace.copernicus.eu

It only ran for 24 seconds so maybe this is too short for Prometheus' interval of 60 seconds to acquire those metrics.
