### ISSUE TITLE
automate build of geotrellis-backend-assembly

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#398]
This artifact is currently being built and put into Artifactory manually. It's unclear where it comes from and what changes have been applied to it. We already have a fork at https://github.com/Open-EO/geopyspark so it makes sense to push changes there and set up a Jenkins job to build it.

**Comment by jdries** [comment]
I solved this by simply copying over the scala code to geotrellis-extensions.
This means we no longer have to deal with a separate shaded jar that managed its own dependencies.
We can also start to remove some classes that we in fact don't use, for maintainability.
