### ISSUE TITLE
EJR does not work in k8s

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#399]
As [noted](https://github.com/Open-EO/openeo-geopyspark-driver/issues/387#issuecomment-1500312702) in #387, the EJR does not work on CreoDIAS because it requires credentials that are stored in Vault and therefore relies on:
- the `vault` binary
- Kerberos auth

The short term fix for the job_tracker/ETL API, which also requires credentials in Vault, was to put the burden on Terraform to fetch the credentials from Vault and pass them to the job_tracker by means of environment variables.

Maybe there is a better, k8s native way to access Vault?

**Comment by bossie** [comment]
@tcassaert:

> This is how we could inject secrets into the openEO deployment in Kube: https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-external-vault

**Comment by soxofaan** [comment]
after some 5'es and 6'es things seem to work properly now: jobs are entered in EJR on creation and status is updated from the job tracker
