### ISSUE TITLE
ANIN: integrate era5-land

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#409]
Use internal downloader tool:
https://git.vito.be/projects/BIGGEO/repos/cds-downloader/browse/cds_downloader

CLI example:
python3 -m cds_downloader download --dataset='${dataset}' --out-dir='${out_dir}' --start='${start}' --end='${end}'

Dataset:
https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview
Key variables:
Potential evaporation
2m temperature
wind components
Total precipitation

When downloader works, NRT would be in NIFI:
https://nifi-prod-01.vgt.vito.be:8443/nifi/?processGroupId=174c7e69-0183-1000-0000-00005f23f257&componentIds=

**Comment by jdries** [comment]
temperature will be special case: we want to convert 2-hourly data into daily min, max, mean

**Comment by VictorVerhaert** [comment]
To make sure this information does not get lost: 
```
Ik ging je nog het script bezorgen waarmee ik de cds-downloader runde:

Dat staat hier op Terrascope:
/home/johan.schreurs/Public/ANIN/script-to-run-cds-downloader/download-multiple-years.sh


Ik heb het naast de cache folders voor de gedownloade zip bestanden gezet.
Ter herinnering, dat is deze folder:
/home/johan.schreurs/Public/ANIN/cds-download-cache_southafrica

En ik heb de zip bestanden nog kunnen renamen zodat de cds-downloader die weer herkent, zodat het die ook hergebruikt.
Er was nl op een bepaald moment een wijziging nodig in de bestandsnaam, t.t.z. de dataset naam werd aan de bestandsnaam toegevoegd. 
Maar dat hadden de oude zip bestanden dus nog niet in hun naam, maar met een bulk rename is dat nu opgelost.
```

**Comment by JeroenVerstraelen** [comment]
We will use AGERA5 instead:
https://github.com/Open-EO/openeo-geopyspark-driver/issues/591
https://github.com/Open-EO/openeo-gfmap/issues/90
