### ISSUE TITLE
people-ea: eurostat vector cube loading

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#427]
use eurostatapiclient to retrieve statistics
use predefined geojsons: https://github.com/eurostat/Nuts2json

combining this, it would be possible to define a new type of vector cube collection that gives access to eurostat statistics

**Comment by JeroenVerstraelen** [comment]
Is it possible to receive some more information about this issue? Would this be a new process similar to load_collection for raster cubes or would this be done via the load_url process?

**Comment by jdries** [comment]
I think this is actually what we worked on over the last weeks, and is solved by the support for UDF's on vector data.

Basically the user will load the nuts regions from geojson as a vector cube, and then apply a udf to each region that retrieves data from eurostat.

I'll close this one now to avoid confusion!
