### ISSUE TITLE
Sentinel2 L2A + L1C: collection tests

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#428]
add collection tests to integration tests
It is important to test across the whole time range. Not necessary to cover all intermediate observations, just need to make sure that different processing baselines are somehow covered, maybe by filtering on that.

**Comment by EmileSonneveld** [comment]
TODO: Also download SCL bands where possible

**Comment by EmileSonneveld** [comment]
@bossie I worked on the main branch for this one. Does the resulting python code look OK to you?
https://git.vito.be/projects/TPT/repos/os_creodias_openeo_k8s/browse/kube_resources/applications/integrationtests/tests/test_collections.py
