### ISSUE TITLE
job and user id in conftest

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#429]
https://github.com/Open-EO/openeo-geopyspark-driver/blob/b5ea93ed110dcfb433f117fb20de93ded7831324/tests/conftest.py#L134-L135

@EmileSonneveld  why did you add these env vars here in conftest? 
These values don't seem to be used/checked elsewhere

**Comment by EmileSonneveld** [comment]
They are there to test the logging system.
`batch_job.py` also assigns them.

**Comment by EmileSonneveld** [comment]
They get red [here](https://github.com/Open-EO/openeo-geotrellis-extensions/blob/develop/openeo-logging/src/main/resources/OpenEOBatchJobJsonLogLayout.json#L43)
Monkeypatching changes the encironment variable too late to have effect here.

**Comment by soxofaan** [comment]
this ticket can be closed now if I understood correctly?

**Comment by EmileSonneveld** [comment]
@soxofaan If this one is ok: https://github.com/Open-EO/openeo-geopyspark-driver/pull/431
Not
