### ISSUE TITLE
Process "array_element" only accepts numbers for "label" parameter

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-geopyspark-driver#43]
Trying to run a process graph that contains

```json
"reducer": {
    "process_graph": {
        "red": {
            "process_id": "array_element",
            "arguments": {
                "data": {
                    "from_parameter": "data"
                },
                "label": "B04"
            }
        },
        "nir": {
            "process_id": "array_element",
            "arguments": {
                "data": {
                    "from_parameter": "data"
                },
                "label": "B08"
            }
        },
```

I receive an error:

> Expecting numeric value for 'label' but got 'B08'

But according to the `/processes` endpoint, both strings and numbers are valid:

> ![image](https://user-images.githubusercontent.com/17781682/95070823-f8c93200-0708-11eb-91fe-5c4dcc622e0d.png)

Or as rendered in the Hub:

> ![image](https://user-images.githubusercontent.com/17781682/95070107-e995b480-0707-11eb-80c0-daf66d90f3c9.png)

**Comment by soxofaan** [comment]
Indeed this is a known issue
the geopyspark driver only supports (int) index in array_element


(internal ref: EP-3583)

**Comment by jdries** [comment]
Suggested solution:
we already have a 'context' map in OpenEOProcessScriptBuilder
This map could contain a mapping from dimension names to labels along that dimension. 
So {'bands':['B02','B03']}
Band name aliases may need to be mapped to a standardized name beforehand?

**Comment by clausmichele** [comment]
I really hope this will be fixed soon, since it affects the client too https://github.com/Open-EO/openeo-python-client/issues/217

**Comment by jdries** [comment]
fixed on dev, will appear on prod soon.
Only for bands dimension, so no 'generic' support for labeled arrays.
