### ISSUE TITLE
missing products check seems to trigger too fast

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#436]
this came out of testing parcel delineation notebook.
The missing products check chooses sentinelhub:

 'SENTINEL2_L2A': skipping 'terrascope' because of 4 missing products.

need to see what these products are, because we're using an area in belgium and a cloud cover filter

**Comment by jdries** [comment]
Here we should consider that this now relies on a python based catalog client, whereas we may want to use the more advanced scala implementation.

**Comment by EmileSonneveld** [comment]
Might be relevant code: https://github.com/Open-EO/openeo-geopyspark-driver/blob/2b869da89fba94a1ba5ff110d711c4712f8183d4/openeogeotrellis/layercatalog.py#L1020-L1034

**Comment by EmileSonneveld** [comment]
The notebook: https://github.com/openEOPlatform/parcel-delineation/blob/main/Parcel%20delineation.ipynb

A more minimal graph that reproduces the issue:
```json
{
  "process_graph": {
    "loadcollection1": {
      "arguments": {
        "bands": [
          "B04",
          "B08",
          "SCL"
        ],
        "id": "SENTINEL2_L2A",
        "properties": {},
        "spatial_extent": {
          "east": 4.238070880405568,
          "north": 50.98139492286342,
          "south": 50.901788083056154,
          "west": 3.129509081558311
        },
        "temporal_extent": [
          "2023-01-01",
          "2023-01-30"
        ]
      },
      "process_id": "load_collection",
      "result": true
    }
  }
}
```
Log: `"(common_name) 'SENTINEL2_L2A': skipping 'terrascope' because of 8 missing products."`
Examples of missing tiles: `('31UDS', '20230110'), ('31UES', '20230110'), ('31UDS', '20230125')`
