### ISSUE TITLE
People-EA: UDF on VectorCube

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#437]
new-style VectorCube objects do not yet support applying a UDF.
We should consider supporting that, maybe allowing to run with apply_dimension, which is more future-proof than just invoking run_udf at top-level.

**Comment by jdries** [comment]
@soxofaan I gave it some thought, and have a draft PR with what I think it can look like. Can you maybe check if I'm missing something important.

**Comment by soxofaan** [comment]
related to https://github.com/Open-EO/openeo-python-driver/issues/197 (maybe even just a duplicate)

**Comment by soxofaan** [comment]
I think it's time to close this particular ticket. Basic end-to-end workflow (jupyter notebook) has been implemented and delivered. 
Most work (on python driver) was tracked under https://github.com/Open-EO/openeo-python-driver/issues/197.
Also various additions were done in python client
