### ISSUE TITLE
Sync request without explicit spatial_extent fails

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geopyspark-driver#449]
`spatial_extent` is needed when running the graph as a sync request, but not needed when running as a batch job.

Script to reproduce: (remove .txt extension to run)
[sync_needs_spatial_extent.py.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/11745025/sync_needs_spatial_extent.py.txt)

The sync job error: `openeo.rest.OpenEoApiError: [400] MissingSpatialFilter: No spatial filter could be derived to load this collection: SENTINEL2_L2A . Please specify a bounding box, or polygons to define your area of interest. (ref: r-16a9fdaa9c21422496954a4ad09772dc)`

**Comment by soxofaan** [comment]
trimming down to minimal reproduction snippet:
```python
cube = connection.load_collection(
    "SENTINEL2_L2A",
    temporal_extent=["2022-12-06", "2022-12-21"],
    bands=["B04", "B05", "B06"],
    # spatial_extent = {"east": 5.08, "north": 51.22, "south": 51.215, "west": 5.07}
)
geometry = {"type": "Polygon", "coordinates": [[[5.07, 51.215], [5.07, 51.22], [5.08, 51.22], [5.08, 51.215]]]}
aggregations = cube.aggregate_spatial(geometries=geometry, reducer="mean")
cube.download("issue449-sync.json")
```

fails on back-end "openeo.vito.be" with 
```
OpenEoApiError: [500] Internal: Server error: KeyError('west') (ref: r-2ac900095a96438cac24953c4c1ded97)
```

fails on back-end     "openeo.dev.warsaw.openeo.dataspace.copernicus.eu" with 
```
OpenEoApiError: [400] MissingSpatialFilter: No spatial filter could be derived to load this collection: SENTINEL2_L2A . Please specify a bounding box, or polygons to define your area of interest. (ref: r-141434b2725d4b40aff1361835456cf6)
```

**Comment by soxofaan** [comment]
ok found the issue:

```
cube = connection.load_collection(... no spatial extent here ...
aggregations = cube.aggregate_spatial(...
cube.download(...
```

we're downloading `cube` without any spatial constraint: no `spatial_extent` in `load_collection`, and no geometry from `aggregate_spatial`. The fix is to do `aggregations.download` instead of `cube.download`.
Then it works on all back-ends mentioned above.

original shared script also has this bug:
```python
    log.info("Batch job will succeed:")
    job = aggregations.execute_batch()
    log.info("job_id: " + job.job_id)
    job.get_results().download_files(output_dir)

    log.info("Sync request will fail:")
    cube.download(output_dir / "timeseries.json")
```

**Comment by EmileSonneveld** [comment]
My bad, this is indeed no sync/async issue. When using `aggregations`, it works as intended.
