### ISSUE TITLE
sar_backscatter: missing bits

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#453]
There's missing parts in backscatter output on product boundary. It only seems to happen in EPSG:3035 and not in UTM.

From the code, it's not so clear where the merging of tiles from 2 different products is supposed to happen, or why it is not visible for UTM. From what I see, for the affected SpatialKey's, I expect 2 tiles to be created, but they are never properly merged.

job: j-977cf7a7393f496f8e6696892994dbda

![Image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/5937096/cf591411-4a59-4381-8367-47cd58eccd72)

```
    isCreo = True

    S1_collection = "SENTINEL1_GRD"
    orbit_direction = "DESCENDING"

    if orbit_direction is not None:
        properties = {"sat:orbit_state": lambda orbdir: orbdir == orbit_direction}  # NOQA
    else:
        properties = {}

    # Load collection
    S1bands = creo_staging.load_collection(
        S1_collection,
        bands=['VH'],
        spatial_extent=laea20km_id_to_extent("E276N190"),
        temporal_extent=["2021-03-12", "2021-03-13"],
        properties=properties
    )

    if S1_collection == "SENTINEL1_GRD":
        # compute backscatter if starting from raw GRD,
        # otherwise assume preprocessed backscatter
        S1bands = S1bands.sar_backscatter(
            coefficient='sigma0-ellipsoid',
            local_incidence_angle=False,
            # DO NOT USE MAPZEN
            elevation_model='COPERNICUS_30' if isCreo else None,
            options={"implementation_version": "2",
                     "tile_size": 256, "otb_memory": 1024, "debug": True,
                     "elev_geoid": "/opt/openeo-vito-aux-data/egm96.tif"}
        )
    else:
        pass


    # Resample to the S2 spatial resolution
    target_crs = 3035
    if target_crs is not None:
        S1bands = S1bands.resample_spatial(
            projection=target_crs, resolution=10.0)
```

**Comment by JeroenVerstraelen** [comment]
Fix complete and has been verified locally and on https://openeo-staging.dataspace.copernicus.eu.

**Comment by jdries** [comment]
@JeroenVerstraelen  you now first merge, which invokes groupByKey, and then apply the partitioner. 
This means:
RDD is grouped/partitioned by product paths
groupByKey triggers a shuffle for the merge, using default partitioner
applyPartitioner then shuffles again?

Can we avoid the extra shuffle?
