### ISSUE TITLE
Quite a lot of warning logs with a simple job

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#455]
While playing with the simple batch job of https://github.com/eu-cdse/notebook-samples/blob/e14ea2d3588ed834a01275670f821f699e214ef7/openeo/Batch_job.ipynb  I noticed there where quite lot of (repeated) warnings,
which looks bad towards the user, while none of these are probably the fault of the user:

![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/44946/d793abf3-620b-4ef0-bcf9-d147a5d22a3c)

**Comment by soxofaan** [comment]
(this was with CDSE openeo.dataspace.copernicus.eu backend by the way)

**Comment by soxofaan** [comment]
pushed some logging tweak, now waiting for CI/deploy to test again

**Comment by soxofaan** [comment]
Situation is already better, but still room for improvement:
![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/44946/f5b9d53a-5960-4e2f-93fa-263ad19a5d83)

**Comment by soxofaan** [comment]
The "Failed to enrich collection metadata" warnings are now also eliminated

**Comment by soxofaan** [comment]
Now I get a lot of S3 warnings and errors, but @EmileSonneveld   is working on that if I understand correctly:

![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/44946/2d85fd94-dab5-4bc8-baec-92c92c9e7acf)

**Comment by EmileSonneveld** [comment]
Yes, I just got some S3 credentials, I hope to get a look what it is about

**Comment by EmileSonneveld** [comment]
@soxofaan The S3 problem is fixed and deployed yesterday

**Comment by soxofaan** [comment]
nice!

my test script now shows zero warnings or errors

closing this for now
