### ISSUE TITLE
no shub units for succeeded job

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#456]
This job j-aea8b5c9808d44cd815da029e565925c is reported as succeeded, but has 0 sh credits reported.
Logging seems to clearly show that sh was used.

Another recent job: j-866c6707aaa44623bb217f9f01a26dff

**Comment by bossie** [comment]
What back-end were these jobs created on?

**Comment by bossie** [comment]
Terrascope prod, got it.

**Comment by bossie** [comment]
It logged SH PUs but they're indeed 0:

> logging resource usage {'jobId': 'j-aea8b5c9808d44cd815da029e565925c', 'jobName': 'WWT_Deserts_75_2023_05_22', 'executionId': 'application_1682817307182_92413', 'userId': '1edbae7adc053e5164b8ac7696e17a9ec031bf5a11fe6dce659cafe39a9366a2@egi.eu', 'sourceId': 'TerraScope/MEP', 'orchestrator': 'openeo', 'jobStart': 1684748394693.0, 'jobFinish': 1684749058995.0, 'state': 'FINISHED', 'status': 'UNDEFINED', 'metrics': {'cpu': {'value': 73970, 'unit': 'cpu-seconds'}, 'memory': {'value': 187883305, 'unit': 'mb-seconds'}, 'time': {'value': 664302.0, 'unit': 'milliseconds'}, 'processing': {'value': 0.0, 'unit': 'shpu'}}}

**Comment by bossie** [comment]
Replayed j-aea8b5c9808d44cd815da029e565925c on openeo-dev but SH PUs are still 0.0:

> logging resource usage {'jobId': 'j-c1aa07b402264547a4c8bf9583965b8f', 'jobName': 'no shub units for succeeded job #456', 'executionId': 'application_1686127502899_77183', 'userId': '7d523381374b62e6f2aad1f2f9fb6eddf624d382a8f71db6dcf5788e3aae0af3@egi.eu', 'sourceId': 'TerraScope/MEP', 'orchestrator': 'openeo', 'jobStart': 1687263427633.0, 'jobFinish': 1687264596129.0, 'state': 'FINISHED', 'status': 'UNDEFINED', 'metrics': {'cpu': {'value': 99275, 'unit': 'cpu-seconds'}, 'memory': {'value': 251495531, 'unit': 'mb-seconds'}, 'time': {'value': 1168496.0, 'unit': 'milliseconds'}, 'processing': {'value': 0.0, 'unit': 'shpu'}}} at https://etl.terrascope.be

Input pixels do work on dev so it's not just a matter of updating the prod job_tracker with the fix for #439.

job_metadata.json makes no mention of SH PUs: :thinking: 

```json
"usage": {
  "input_pixel": {
    "value": 3.5,
    "unit": "mega-pixel"
  }
}
```

**Comment by bossie** [comment]
Fixed bug where a process graph that combines SHub and Terrascope collections, the `input_pixel` usage simply replaces the `sentinelhub` usage:

![input_pixel_shpus](https://github.com/Open-EO/openeo-geopyspark-driver/assets/1032518/065bb262-4fc7-469a-ad05-a2fdd72425d6)

> logging resource usage {'jobId': 'j-5227d2312a104d1c9db1ef9efb9b7620', 'jobName': 'no shub units for succeeded job #456', 'executionId': 'application_1686127502899_80118', 'userId': '7d523381374b62e6f2aad1f2f9fb6eddf624d382a8f71db6dcf5788e3aae0af3@egi.eu', 'sourceId': 'TerraScope/MEP', 'orchestrator': 'openeo', 'jobStart': 1687417093967.0, 'jobFinish': 1687418124330.0, 'state': 'FINISHED', 'status': 'UNDEFINED', 'metrics': {'cpu': {'value': 112739, 'unit': 'cpu-seconds'}, 'memory': {'value': 286112432, 'unit': 'mb-seconds'}, 'time': {'value': 1030363.0, 'unit': 'milliseconds'}, 'processing': {'value': 7665.333488553762, 'unit': 'shpu'}}} at https://etl.terrascope.be

**Comment by bossie** [comment]
SH PUs will no longer be logged in the ETL API if there weren't any consumed:

> logging resource usage {'jobId': 'j-df4831a5cccc4d04a46d82f487d13d85', 'jobName': "don't log 0 SH PUs", 'executionId': 'application_1686127502899_80173', 'userId': '7d523381374b62e6f2aad1f2f9fb6eddf624d382a8f71db6dcf5788e3aae0af3@egi.eu', 'sourceId': 'TerraScope/MEP', 'orchestrator': 'openeo', 'jobStart': 1687419437893.0, 'jobFinish': 1687419563812.0, 'state': 'FINISHED', 'status': 'UNDEFINED', 'metrics': {'cpu': {'value': 1438, 'unit': 'cpu-seconds'}, 'memory': {'value': 3396820, 'unit': 'mb-seconds'}, 'time': {'value': 125919.0, 'unit': 'milliseconds'}}} at https://etl.terrascope.be
