### ISSUE TITLE
add Sentinel-3 to Terrascope instance

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#465]
@JohanKJSchreurs please add these to openeo-dev
manually test if layer works
then add collection test: https://git.vito.be/projects/BIGGEO/repos/openeo-collection-tests/browse
Keep an eye on duration/performance of collection test.

**Comment by jverrydt** [comment]
Collection IDs:
* urn:eop:VITO:TERRASCOPE_S3_SY_2_VG1_V1
* urn:eop:VITO:TERRASCOPE_S3_SY_2_V10_V1

**Comment by jdries** [comment]
the new collections themselves have been added, now we just need the tests

**Comment by jdries** [comment]
SENTINEL3_SYNERGY_VG1 still seems to have an issue:
'create_pyramid failed: Could not find data for your load_collection request with catalog ID "urn:eop:VITO:TERRASCOPE_S3_SY_2_VG1_V1". The catalog query had correlation ID "j-e987759eedea43aab693c32fe464c448" and returned 32 results.

j-e987759eedea43aab693c32fe464c448

**Comment by bossie** [comment]
Can't recover the process graph of j-e987759eedea43aab693c32fe464c448; any particular one that's giving trouble @jdries ?

This batch job seems to work fine:

```json
{
  "process_graph": {
    "loadcollection1": {
      "arguments": {
        "bands": [
          "NDVI"
        ],
        "id": "SENTINEL3_SYNERGY_VG1",
        "spatial_extent": {
          "east": 31.376679932051676,
          "north": 30.24943417530817,
          "south": 29.833771524705824,
          "west": 30.807402823618027
        },
        "temporal_extent": [
          "2020-07-01",
          "2020-08-01"
        ]
      },
      "process_id": "load_collection"
    },
    "saveresult1": {
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "format": "GTiff",
        "options": {}
      },
      "process_id": "save_result",
      "result": true
    }
  }
}
```

**Comment by bossie** [comment]
One for SENTINEL3_SYNERGY_VG10 as well.

**Comment by bossie** [comment]
OK, trying to add SENTINEL3_SYNERGY_VG1 to openeo-collection-tests exposes the problem:

> [400] NoDataAvailable: There is no data available for the given extents. Could not find data for your load_collection request with catalog ID "urn:eop:VITO:TERRASCOPE_S3_SY_2_VG1_V1". The catalog query had correlation ID "r-0e064465d5d0473f80dc6be5c14af18a" and returned 2 results. (ref: r-0e064465d5d0473f80dc6be5c14af18a)

SENTINEL3_SYNERGY_VG10 still works fine though.

**Comment by bossie** [comment]
Looking through the logs, features are being discarded and this warning is logged instead:

> Did not find expected number of bands 15 for feature urn:eop:VITO:TERRASCOPE_S3_SY_2_VG1_V1:S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002 with links Array(Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/tg.tif,Some(tg),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/vza.tif,Some(vza),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/B3.tif,Some(B3),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/vaa.tif,Some(vaa),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/saa.tif,Some(saa),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/sm.tif,Some(sm),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/sza.tif,Some(sza),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/B2.tif,Some(B2),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/ag.tif,Some(ag),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/MIR.tif,Some(MIR),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/wvg.tif,Some(wvg),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/B0.tif,Some(B0),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/og.tif,Some(og),None,None), Link(file:///data/MTDA/TERRASCOPE_Sentinel3/COG/SY_2_VG1/S3B/2020/07/01/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002/S3B_SY_2_VG1____20200701T163347_20200702T163347_20200707T165532_EUROPE____________LN2_O_NT_002.SEN3/NDVI.tif,Some(NDVI),None,None))

**Comment by bossie** [comment]
So the deal seems to be that the OSCARS catalog reports 15 bands, but early (?) features only have 14: they lack the TOA_NDVI band.

A workaround is to explicitly specify a `bands` argument; this is also the reason why the process graph above works (`"bands":["NDVI"]`).

**Comment by bossie** [comment]
As discussed:

- report issue to s-ops,
- _don't_ implement workaround where layercatalog.json overrides OSCARS' band information (untested),
- add to openeo-collection-tests with a more recent temporal extent to avoid the problem in the meanwhile.

**Comment by bossie** [comment]
Added to openeo-collection-tests.

Teams [ref](https://teams.microsoft.com/l/message/19:7158e70d861847dab2ea2baa917bfa62@thread.tacv2/1695979479648?tenantId=9e2777ed-8237-4ab9-9278-2c144d6f6da3&groupId=befdddf8-55e8-4c70-855e-8802739f2ae9&parentMessageId=1695979479648&teamName=Remote%20Sensing%20Services&channelName=Software%20operations&createdTime=1695979479648&allowXTenantAccess=false).

**Comment by bossie** [comment]
Confirmed by Carolien T.:

> Yes, TOA_NDVI was added in VG1 products from 14 June 2021 onwards. 

So features without the TOA_NDVI band are silently discarded; shall I attempt to insert a NODATA band @jdries ?

**Comment by jdries** [comment]
yes, inserting nodata band is probably the way to go. This kind of thing also can happen for other collections, so this could be a generic solution.

**Comment by bossie** [comment]
TODO; adapt the openeo-collection-tests time range for SENTINEL3_SYNERGY_VG1 to include dates that lack a TOA_NDVI band.

**Comment by bossie** [comment]
Updated openeo-collection-tests.
