### ISSUE TITLE
add more PROBA-V collections to Terrascope instance

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#466]

**Comment by jverrydt** [comment]
Collection IDs:
* urn:eop:VITO:PROBAV_S1_TOC_NDVI_100M_COG_V2
* urn:eop:VITO:PROBAV_S5_TOC_NDVI_100M_COG_V2
* urn:eop:VITO:PROBAV_S10_TOC_NDVI_333M_COG_V2
* urn:eop:VITO:PROBAV_S10_TOC_NDVI_1KM_COG_V2

**Comment by jdries** [comment]
yes, thanks!

**Comment by bossie** [comment]
TODO: add to openeo-collection-tests.

**Comment by bossie** [comment]
Recent half-open temporal interval changes have implications for openeo-collection-tests, particularly for new ref files (`expected_results/expected_XYZ.json`); addressing this as well.

**Comment by bossie** [comment]
Added to openeo-collection-tests.

Available on prod:
https://openeo.vito.be/openeo/1.1/collections/PROBAV_L3_S1_TOC_100M
https://openeo.vito.be/openeo/1.1/collections/PROBAV_L3_S1_TOC_333M
