### ISSUE TITLE
support & example of running backend as local docker container

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#467]
For EOEPCA docker & HPC runners:

Two options:
* start webapp locally
* start job based on process graph json, so command line tool, no webapp

Use load_stac to load data

Startpoint:
https://github.com/Open-EO/openeo-geotrellis-kubernetes/blob/master/examples/run_local.md

Document everything + simplify where possible.

Epic: EOEPCA/roadmap#10

**Comment by soxofaan** [comment]
FYI: long time ago I already made a command line tool to execute a process graph with geopyspark driver machinery:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/19740a43e75eb49c7461f33bcf7b35f7efdc69f1/openeogeotrellis/cli.py#L1-L17

It's pretty old, so I'm not sure if it still works

**Comment by jdries** [comment]
This one needs to see how we enable 'in-memory' job registry.

**Comment by JohanKJSchreurs** [comment]
Brief summary from PR https://github.com/Open-EO/openeo-geopyspark-driver/pull/533
- [x]  Be able to run test suite (pytest) in Docker.
- [x]  Running backend / web app as local docker container, namely be able to use the REST API.
- [ ]  Be able to run a batch job for testing.   --> This needs the in-memory job register to be able to track the batch jobs

**Comment by JeroenVerstraelen** [comment]
This issue continues in the following EPIC:
https://github.com/Open-EO/openeo-geopyspark-driver/issues/806
