### ISSUE TITLE
Mask process not working

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-geopyspark-driver#47]
I have just tested the mask process as discussed in the dev meeting. It throws an error: "An error occured while calling RasterMask..." (too slow to read the rest, before it disappears).
The process graph up to "reduce_dimension" works. 
Here the visual process graph:
![image](https://user-images.githubusercontent.com/51962348/97583852-b0472080-19f7-11eb-8b1d-860aa6d7b212.png)

Here the json:
```
{
  "process_graph": {
    "1": {
      "arguments": {
        "bands": null,
        "id": "TERRASCOPE_S2_NDVI_V2",
        "spatial_extent": {
          "east": 5.67950128534149,
          "north": 51.98561668073381,
          "south": 51.960603275339736,
          "west": 5.6154620713870225
        },
        "temporal_extent": [
          "2018-01-01T00:00:00Z",
          "2018-02-01T23:59:59Z"
        ]
      },
      "process_id": "load_collection"
    },
    "2": {
      "arguments": {
        "data": {
          "from_node": "4"
        },
        "process": {
          "process_graph": {
            "1": {
              "arguments": {
                "x": {
                  "from_parameter": "x"
                },
                "y": 100
              },
              "process_id": "gt",
              "result": true
            }
          }
        }
      },
      "process_id": "apply"
    },
    "3": {
      "arguments": {
        "data": {
          "from_node": "4"
        },
        "mask": {
          "from_node": "2"
        },
        "replacement": 0
      },
      "process_id": "mask"
    },
    "4": {
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "1": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "5": {
      "arguments": {
        "data": {
          "from_node": "3"
        },
        "format": "GTIFF"
      },
      "process_id": "save_result",
      "result": true
    }
  }
}
```

**Comment by jdries** [comment]
The actual error can be copied from the console in your web browser dev tools:

An error occurred while calling o1389.rasterMask. Trace:\npy4j.Py4JException: Method rasterMask([class geotrellis.spark.ContextRDD, class geotrellis.spark.ContextRDD, class java.lang.Integer]) does not exist\n\tat py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)\n\tat py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)\n\tat py4j.Gateway.invoke(Gateway.java:274)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\n\n

**Comment by jdries** [comment]
Ah yes, known issue: please use 0.0 for your replacement value, so that it's a double instead of an int.
We'll need to fix this in python.

**Comment by jdries** [comment]
should be fixed now!
