### ISSUE TITLE
reduce maintenance on tsservice router rules

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#474]
Additional proxy endpoints for tsservice keep popping up and supporting them requires building and redeploying.

Keeping the Host match for dev but dropping it for prod will still route dev traffic to epod-openeo-dev and the rest to epod-openeo-[12].

https://git.vito/projects/BIGGEO/repos/openeo-deploy/browse/mep/probav-mep.py?at=254644b58cf11ad9e46d31823358f72526ffa265#269-277

**Comment by JeroenVerstraelen** [comment]
Host match has been dropped in probav-mep.py
