### ISSUE TITLE
Add type to derived_from links so that it's clearly not a STAC JSON

### ISSUE THREAD

**Issue by JohanKJSchreurs** [Open-EO/openeo-geopyspark-driver#486]
Add type to derived_from links so that it's clearly not a STAC JSON (which is the default)

This is part of https://github.com/openEOPlatform/architecture-docs/issues/327, but having a separate issue in openeo-geopyspark-driver makes it a easier to create a branch and PR on the repository where code was modified.

**Comment by jdries** [comment]
seems fixed
