### ISSUE TITLE
get job usage/result metadata in (ES) job registry

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#488]
Current elastic job registry does not contain usage info (cpu hours, credits,...).
It would be convenient to have this information in a database as well, both for faster retrieval and for generating statistics.

**Comment by bossie** [comment]
Related: https://github.com/Open-EO/openeo-geopyspark-driver/blob/7ad561daf33319ca5e824f79c60a2108cc965e0d/openeogeotrellis/job_tracker_v2.py#L523C29-L523C40
