### ISSUE TITLE
support generic reducers in aggregate_spatial (aka zonal_statistics) 

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#49]
`aggregate_spatial`/`zonal_statistics`  in openeo-geopyspark-driver (and openeo-python-driver) assumes the provided reducer is a simple one-process reducer, and only supports: 'histogram', 'sd', 'median' or 'mean'

(also: I think it would be cleaner if we could also remove the usage of old-style "zonal_statistics" and use 1.0-style "aggregate_spatial" in more places)

**Comment by soxofaan** [comment]
also see Open-EO/openeo-python-client#144

**Comment by jdries** [comment]
Note that this is far from trivial, the current code path is based on computing histograms, and can only support statistics based on that.
It would be nice to have a use case or example of what would be useful to additionally support.

**Comment by soxofaan** [comment]
Indeed, generic `aggregate_spatial` reducers will be lot of work with probably not a lot of uptake at the moment.

However there are still some simple one-process reducers we could easily add (based on histograms),
e.g.  from the "reducer" category listing at https://processes.openeo.org/:
- `max` and `min`
- `count`  basic version: count  valid elements (`condition=null`), or count all elements (`condition=true`)
- `quantiles`

**Comment by jdries** [comment]
this one got fixed, we now also support using multiple reducers.
Fully generic is harder, so we focus on the list marked as 'reducer' in openeo-processes.
