### ISSUE TITLE
VLCC logs resources to Terrascope ETL API as "cdse"

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#490]
ETL API indices in kibana-apps ES:

![cdse_logs_in_terrascope_etl](https://github.com/Open-EO/openeo-geopyspark-driver/assets/1032518/76403d29-b417-4443-888e-8c91a7db5ca3)

The `User-Agent` header in these access logs indicate that the requests are coming from vlcc-prod:

![MicrosoftTeams-image (1)](https://github.com/Open-EO/openeo-geopyspark-driver/assets/1032518/1de5a7a7-2c2b-4c9a-bf78-2059f19d0ac5)

**Comment by bossie** [comment]
As discussed: log VLCC resources to CDSE ETL API.

**Comment by bossie** [comment]
@jdries this was requested by Bram; is it ok to update vlcc-prod with this fix?

**Comment by jdries** [comment]
yes please, you'll only want to notify users of that cluster

**Comment by bossie** [comment]
Looks like @tcassaert already redeployed VLCC 3.1 with this fix in the meanwhile.

**Comment by bossie** [comment]
@JanssenBrm I gather from their respective Kibanas that VLCC OpenEO has started logging to the CDSE prod ETL API instead of the Terrascope ETL API, with sourceId "vlcc", since 16/08; can you confirm?

**Comment by JanssenBrm** [comment]
I can now indeed see incoming requests from the VLCC source on CDSE Kibana instance. I don't see any CDSE entries anymore on the TerraScope Kibana instance. So it looks like everything is working fine now!
