### ISSUE TITLE
Support for CORS

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-geopyspark-driver#5]
We try to access the GeoPySpark back-end for a presentation next week, but unfortunately it doesn't send CORS headers so the JS client (in a browser environment) and the Web Editor can't access it:

> Access to XMLHttpRequest at 'http://openeo.vgt.vito.be/openeo/' from origin 'http://editor.openeo.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

It would be appreciated to get CORS support. For more information see https://open-eo.github.io/openeo-api/v/0.3.1/cors/

**Comment by jdries** [comment]
I enabled cors, and was able to load our backend into the editor interface.
