### ISSUE TITLE
CDSE reported request durations are too large

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#513]
When looking at the traefik logs on kibana-infra (openeo-creo* index pattern) there appears to be something wrong with the Duration field:
```
kubernetes.container.name: traefik AND RequestPath: *collections* AND (RequestHost: openeo.dataspace.copernicus.eu OR RequestHost: openeo.creo.vito.be)
```

It reports the request duration in nanoseconds with two issues:

1. The duration is sometimes exceptionally large:
- /collection requests can take up to 160 minutes
- /result requests can take 3 days

2. The average duration is larger than we would expect:
- /collection requests take on average 12-20 seconds
- /openeo/1.1/jobs POST takes on average 10 minutes
- /openeo/1.1/jobs GET takes on average 30 minutes

The issue is clear on the OpenEO CDSE dashboard on grafana.intern.

**Comment by bossie** [comment]
For future reference, what was done to fix this?
