### ISSUE TITLE
load_stac functionality?

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-geopyspark-driver#528]
I post the link that I also posted on the CDSE support. It seems the `load_stac` doesn't work yet with public catalogs?
https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/posts/13919325025181--openEO-load-stac-process-not-working-with-public-catalogs

**Comment by clausmichele** [comment]
I'm continuing in the CDSE forum, getting other errors after this fix

**Comment by soxofaan** [comment]
Circling back from the forum discussion:


>       "https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a"
>
> The `KeyError: 'eo:bands'` seems to come from here:
>
>        File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 893, in get_band_names
>          return [get_band_name(eo_band) for eo_band in asst.extra_fields["eo:bands"]]
>      KeyError: 'eo:bands'
>
> So apparently something goes wrong trying to extract band names from the assets in that collection

@bossie   any quick ideas?

**Comment by bossie** [comment]
For https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a, the problem seems twofold:

1. we're not respecting our assumption that band assets have an `eo:bands` property,
2. we're also assuming that all items in this collection have the same bands available but they don't: `java.lang.IllegalArgumentException: band cirrus not found in S2A_32TPS_20220627_0_L2A`

Fixing 1 is easy enough: https://github.com/Open-EO/openeo-geopyspark-driver/blob/7d408c70ea3b58aff5b69555ee9908d678b73661/openeogeotrellis/backend.py#L878

But then we bump into 2; this probably should work if we specify a `bands` argument, as is the case here, but it doesn't. This requires some more work/testing.

Reproduce with:
```python
connection = openeo.connect("https://openeo-dev.vito.be").authenticate_oidc()

bands = ["red", "nir"]
url = "https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a"

data_cube = (connection
             .load_stac(url=url,
                        spatial_extent={"east": 11.40, "north": 46.52, "south": 46.46, "west": 11.25},
                        temporal_extent=["2022-06-01", "2022-06-30"],
                        bands=bands)
             .save_result("GTiff"))
```

**Comment by bossie** [comment]
Same problem for https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a: `java.lang.IllegalArgumentException: band AOT not found in S2A_MSIL2A_20220627T100611_R022_T32TPS_20220628T030557`

Ideally we invest some time in setting up automatic tests for particular public STAC APIs/catalogs, where we don't actually read assets from S3.

**Comment by jdries** [comment]
@bossie  should we add a recommendation somewhere to always specify a bands filter?

**Comment by bossie** [comment]
No, that's what I was trying to say: a small fix wrt/ `eo:bands` + a bands filter would have been a good temporary workaround but apparently that's still not enough to fix it.

**Comment by clausmichele** [comment]
@bossie are there updates on this?

**Comment by jdries** [comment]
Hi @clausmichele , I guess you're asking for BiDS?  We're a bit flooded with BiDS work for the moment and at the same time trying to cope with high urgency project requirements. So I don't know if we can still support yet another way of loading Sentinel-2 L2A in the 3 days we have left.

**Comment by bossie** [comment]
A fix is available on CDSE dev.

**Comment by bossie** [comment]
Fix is available on https://openeo-staging.dataspace.copernicus.eu/.

This applies to `load_stac` of https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a; a bands filter is not necessary (but still recommended for performance).

**Comment by bossie** [comment]
A `load_stac` of https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a does not work and fails with an error:
> HTTP/1.1 404 The specified resource does not exist.

Said resource is an underlying asset e.g. https://sentinel2l2a01.blob.core.windows.net/sentinel2-l2/32/T/PS/2022/06/27/S2A_MSIL2A_20220627T100611_N0400_R022_T32TPS_20220628T030557.SAFE/GRANULE/L2A_T32TPS_A036627_20220627T100933/IMG_DATA/R10m/T32TPS_20220627T100611_B04_10m.tif

Maybe it really doesn't exist but I'm guessing it just requires authentication.

**Comment by clausmichele** [comment]
Thanks @bossie. Yes indeed, the Microsoft Planetary Collections require to sign the connection in this way:
https://pystac-client.readthedocs.io/en/stable/usage.html#automatically-modifying-results

**Comment by clausmichele** [comment]
@bossie do you plan to add support also for Microsoft Planetary collections?

**Comment by bossie** [comment]
Don't know what's on the road map in that regard. @jdries?

This would also require a way to pass a SAS token to `load_stac` and AFAICT the API does not accommodate for that (yet).

**Comment by clausmichele** [comment]
I would be happy to contribute to an updated proposal of the `load_stac`, since there are some edge cases that are not covered yet.
