### ISSUE TITLE
Support multiple accounting backends in aggregator scenario

### ISSUE THREAD

**Issue by JanssenBrm** [Open-EO/openeo-geopyspark-driver#531]
With the deployment of the aggregator, processing can be divided on multiple back-ends. For example, when deploying the aggregator in CDSE, some of the processing could be done on the TerraScope environment. 

In order to fully support this, the final processing environment (in the example above, TerraScope) should interact with the proper accounting backend (in the example, the CDSE marketplace-cost-api). Specifically, whenever TerraScope gets a request to process a job from CDSE it should:

- Execute the credit check against the CDSE backend
- Report the resources used to the CDSE backend

Some possible approaches for openEO to determine the correct accounting backend have already been discussed with @soxofaan :
- A user agent could identify from which environment the request is coming.
- Inspection of the token could achieve the same thing.

**Comment by soxofaan** [comment]
related: https://github.com/eu-cdse/openeo-cdse-infra/issues/27

**Comment by soxofaan** [comment]
did first successful experiment today:
created job (j-240208eceedf489dbe7ad113d25e0bf0) on "openeo-dev.vito.be" backend with `job_options={"etl_api_id": "CDSE-staging"}` and the job tracker (for dev) sent the resource usage data to the CDSE staging ETL API

**Comment by soxofaan** [comment]
setup was done through `openeogeotrellis.integrations.etl_api.MultiEtlApiConfig` usage in `GpsBackendConfig` in openeo-deploy project

**Comment by soxofaan** [comment]
I'm going to close this ticket for now. 
There is still other work to be done (e.g. at level of aggregator: https://github.com/Open-EO/openeo-aggregator/issues/135, and aligning OIDC providers in multiple deployments), but that is food for other tickets
