### ISSUE TITLE
NetCDF result download comes without CRS

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#54]
Upon downloading results in NetCDF format, no CRS is specified in the file. Is this intentional?
The files appear to be in the corresponding WGS84 UTM zone, which can be assigned later, but this appears not very secure to me.

Example ProcessGraph:
`{
  "process_graph": {
    "1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "TERRASCOPE_S2_NDVI_V2",
        "spatial_extent": {
          "west": 5.224096231078771,
          "south": 50.69038597219307,
          "east": 5.311809621280062,
          "north": 50.72560528417654
        },
        "temporal_extent": [
          "2020-10-08T00:00:00Z",
          "2020-10-22T23:59:59Z"
        ],
        "bands": [
          "NDVI_10M"
        ]
      }
    },
    "2": {
      "process_id": "reduce_dimension",
      "arguments": {
        "reducer": {
          "process_graph": {
            "1": {
              "process_id": "min",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "result": true
            }
          }
        },
        "dimension": "t",
        "data": {
          "from_node": "1"
        }
      }
    },
    "3": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "2"
        },
        "format": "NETCDF"
      },
      "result": true
    }
  }
}`

**Comment by jdries** [comment]
Apparently this is not directly supported in xarray:
https://github.com/pydata/xarray/issues/2288
There's talk of a workaround, (setting crs scalar coordinate), need to figure out what it is exactly.

**Comment by jdries** [comment]
Could be some useful stuff in here:
https://corteva.github.io/rioxarray/stable/_modules/rioxarray/rioxarray.html#XRasterBase.write_crs

**Comment by jonathom** [comment]
I was wrong - CRS is set as global attribute of the NetCDF file. This just doesn't seem to be recognized automatically by e.g. QGIS. The projection is therefore accessible through (QGis) properties/information and can then be set manually.

**Comment by dimzog** [comment]
`rioxarray` `open_rasterio` solves the CRS problem for me, but I/O seems slow. Did you find a workaround @jonathom ?

**Comment by RichardScottOZ** [comment]
Thanks for the tip @jonathom

**Comment by jdries** [comment]
We're rolling out a new netcdf implementation on dev that encodes the crs in a way that at least GDAL understands.
