### ISSUE TITLE
Experimental support for onnx runtime

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#543]
ONNX promises to store and run ML models built in various frameworks (Tensorflow, pytorch), without having to install all those frameworks. 
This can lead to further standardization of deep learning support in openEO.

I don't want to include it as a dependency in the image yet, but perhaps we can store dependencies on artifactory, and have some sample code, or even a built-in function that allows users to easily enable ONNX support in their UDF without having to deal with the more complex dependency management approach themselves.

**Comment by jdries** [comment]
Link to dependencies:
https://git.vito.be/projects/APPL/repos/cropclass/browse/src/cropclass/config/settings.py#14

OpenEO job options:
https://git.vito.be/projects/APPL/repos/cropclass/browse/src/cropclass/config/settings.py#45

Example of adding to python path:
https://git.vito.be/projects/APPL/repos/cropclass/browse/src/cropclass/classification.py#423

**Comment by VincentVerelst** [comment]
*Comment for myself*
custom udf dependencies in OpenEO:
https://documentation.dataspace.copernicus.eu/APIs/openEO/job_config.html#custom-udf-dependencies
