### ISSUE TITLE
best available pixel composite

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#544]
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiZz8u7yoSCAxUX_7sIHZ-vAfoQFnoECBUQAQ&url=https%3A%2F%2Fwww.tandfonline.com%2Fdoi%2Fpdf%2F10.1080%2F07038992.2014.945827&usg=AOvVaw1tr17gl3Vm98bmTF5bTeln&opi=89978449

Current implementation:
```

scl = c.load_collection(
    "SENTINEL2_L2A",
    temporal_extent = ["2022-07-01", "2022-08-01"],
    bands = ["SCL"],
    max_cloud_cover=70
)#.resample_spatial(resolution=60)

def makekernel(iwindowsize):
    kernel_vect = scipy.signal.windows.gaussian(iwindowsize, std=iwindowsize / 6.0, sym=True)
    kernel = np.outer(kernel_vect, kernel_vect)
    kernel = kernel / kernel.sum()
    return kernel

classification = scl.band("SCL")
binary = (classification == 3) | (classification == 8) | (classification == 9) | (classification == 10) | (classification == 11)
    
distance = binary.apply_kernel(makekernel(11))

from openeo.processes import absolute, int,inspect

label = Parameter('label')
def bap_selection(distance_timeseries):


    min = distance_timeseries.min()
    
    return distance_timeseries.array_apply(lambda x:int(x)!=int(min))
    

rank_mask = distance.apply_neighborhood(
        bap_selection,
        size=[{'dimension': 'x', 'unit': 'px', 'value': 1}, {'dimension': 'y', 'unit': 'px', 'value': 1},
              {'dimension': 't', 'value': "month"}],
        overlap=[]
    )
```

**Comment by jdries** [comment]
@VincentVerelst  we now have a very nice baseline implementation using UDF.
Next step is to port to predefined functions.
Most realistic is perhaps to start with the date score, so leave distance to cloud in udf, and move date score outside.

**Comment by VincentVerelst** [comment]
To calculate the date score you would need the day of month for each date. How would you extract those without a UDF?

**Comment by jdries** [comment]
@VincentVerelst  this is how I did that in my original, pure openEO, implementation. 

Note that this is just a copy paste of an earlier example, I did not yet adjust to how you do the final scoring, you'll still need to do that!

```

from openeo.processes import absolute, int,inspect,multiply,array_apply

label = Parameter('label')
parent = Parameter('parent.data')

def bap_selection(cloud_distance):    
    scoring_rule = lambda x:absolute(15*x) + absolute(x.process("date_difference",date1=x.process("date_replace_component",date=label,value=15,component="day"),date2=label,unit="day"))
    score = cloud_distance.array_apply(scoring_rule)        
    return score.array_apply(lambda x:int(x)!=int(array_apply(parent,scoring_rule).min()))
    
```

rank_mask = distance.apply_neighborhood(
        bap_selection,
        size=[{'dimension': 'x', 'unit': 'px', 'value': 1}, {'dimension': 'y', 'unit': 'px', 'value': 1},
              {'dimension': 't', 'value': "month"}],
        overlap=[]
    )

**Comment by jdries** [comment]
Todo before completion: add integration test and perhaps also CDSE benchmark
