### ISSUE TITLE
VITO SH consumption 2023/08

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#547]

**Comment by bossie** [comment]
PUs consumed by Jenkins running tests in geotrellis-extensions/geotrellis-sentinelhub are never logged in the ETL API so there is at least a discrepancy there. Not sure how much of an impact they make so getting those numbers is a start.

Another theory is that OpenEO requests using basic authentication are not accounted for.

**Comment by bossie** [comment]
Also: check if Jenkins usage is reported to prod ETL instead of dev ETL.

**Comment by bossie** [comment]
Related: https://github.com/Open-EO/openeo-geopyspark-driver/issues/459

**Comment by bossie** [comment]
As discussed: impact of requests during development incl. Jenkins could be handled by using a dedicated SHub account.

**Comment by bossie** [comment]
**geotrellis-extensions/geotrellis-sentinelhub unit tests**: 780 PU/run * (20 runs in 9 working days ≈ 44 runs/month) ≈ 35000 PUs/month or 3.5% of 1,000,000 so insignificant.

**Comment by jdries** [comment]
Final conclusion was that this is caused by speculation in spark.
