### ISSUE TITLE
unexpected importance of parameter type in func add_dimension

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#55]
I stumbled upon the following behaviour of the function `add_dimension`: It seems to only write the given `label` when the parameter `type` is not `other` (but, for example, `bands`). When type is `other` it seems to just be set as `band_0`. Because `type` has a default value (`other`) and therefore is not a mandatory input I did not expect it to be so important towards the behaviour of the function. In my opinion this should at least be documented.

I did not test this with other backends. Here's an example:
`{
  "process_graph": {
    "add_dimension_IWUCC3825R": {
      "arguments": {
        "data": {
          "from_node": "reduce_dimension_IBSFT4301B"
        },
        "label": "collaps1",
        "name": "bands",
        "type": "other"
      },
      "process_id": "add_dimension"
    },
    "load_collection_WHZYS7018X": {
      "arguments": {
        "bands": [
          "B04",
          "B08"
        ],
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "spatial_extent": {
          "east": 4.5277,
          "north": 50.9305,
          "south": 50.7816,
          "west": 4.2369
        },
        "temporal_extent": [
          "2020-10-01",
          "2020-10-15"
        ]
      },
      "process_id": "load_collection"
    },
    "reduce_dimension_IBSFT4301B": {
      "arguments": {
        "context": null,
        "data": {
          "from_node": "reduce_dimension_SXELG4042R"
        },
        "dimension": "bands",
        "reducer": {
          "process_graph": {
            "array_element_OCQIS1854F": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "index": 1,
                "return_nodata": false
              },
              "process_id": "array_element"
            },
            "array_element_ZXQBW2629C": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "index": 0,
                "return_nodata": false
              },
              "process_id": "array_element"
            },
            "normalized_difference_JVSKC0506O": {
              "arguments": {
                "x": {
                  "from_node": "array_element_ZXQBW2629C"
                },
                "y": {
                  "from_node": "array_element_OCQIS1854F"
                }
              },
              "process_id": "normalized_difference",
              "result": true
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "reduce_dimension_SXELG4042R": {
      "arguments": {
        "context": null,
        "data": {
          "from_node": "load_collection_WHZYS7018X"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "mean_ZYDSH5431N": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "ignore_nodata": true
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "save_result_PLEPS1878X": {
      "arguments": {
        "data": {
          "from_node": "add_dimension_IWUCC3825R"
        },
        "format": "NetCDF",
        "options": {}
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

**Comment by jdries** [comment]
Good point, thing is, our particular backend really does not support adding arbitrary dimensions. We simple have time and bands, and the space dimensions are pretty much fixed.
People can give them a different name if they want, but that's about it.
Maybe our backend should throw an error when type is 'other'?

**Comment by jonathom** [comment]
I opened #57 for another problem related to the `type` parameter. I think both problems could be solved when `other` just isn't allowed as you suggested and `type` becomes a mandatory, not an optional parameter.

**Comment by soxofaan** [comment]
I opened API discussion on this: Open-EO/openeo-processes#213

**Comment by jdries** [comment]
Closing this one, as it now seems to be an API discussion.
