### ISSUE TITLE
ensure_executor_logging id handling

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#553]
@bossie I have question about `ensure_executor_logging`:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/9183af49607bb8fe812b79e33ce5781c855300eb/openeogeotrellis/utils.py#L436-L469

especially the last part
```python
decorator = on_first_time(partial(setup_context_aware_logging,
                                      user_id=FlaskUserIdLogging.get_user_id(),
                                      request_id=FlaskRequestCorrelationIdLogging.get_request_id()))
```

- this is going (or at least intended) to be executed on an spark executor where there is not flask request context, so `FlaskRequestCorrelationIdLogging.get_request_id()` is never going to return something useful. can that just be dropped?
- the decorator will be executed once (`on_first_time`) per executor, so isn't there risk of leaking ids (e.g. user id in this case) when the same executor process is reused for different sync jobs of different users?

(stumbled on this while digging for https://github.com/Open-EO/openeo-geopyspark-driver/issues/546 and https://github.com/eu-cdse/openeo-cdse-infra/issues/29)

**Comment by bossie** [comment]
That was the hard one. Let me get back to you on that.

**Comment by bossie** [comment]
> this is going (or at least intended) to be executed on an spark executor where there is not flask request context, so FlaskRequestCorrelationIdLogging.get_request_id() is never going to return something useful. can that just be dropped?

What is supposed to happen is: `FlaskRequestCorrelationIdLogging.get_request_id()` is called when the `@ensure_executor_logging` decorator is applied to a Spark callback function; this happens in the driver and therefore there is a valid request ID available. Then Spark serializes the decorated callback, including the request ID, and sends it to the executors where it is executed.

AFAICT executor logs carry the proper `req_id`:
![executor_logs_req_id](https://github.com/Open-EO/openeo-geopyspark-driver/assets/1032518/d7381d7f-f34c-418c-871e-3386cc0484d7)

**Comment by soxofaan** [comment]
ok thanks for that clarification.
I somehow missed that the `FlaskUserIdLogging.get_user_id()` call itself happens in the driver and not in the executor
