### ISSUE TITLE
openEO random_forest_classifier validation/inference fails in CDSE

### ISSUE THREAD

**Issue by Pratichhya** [Open-EO/openeo-geopyspark-driver#562]
When testing [https://open-eo.github.io/openeo-python-client/machine_learning.html](https://open-eo.github.io/openeo-python-client/machine_learning.html), we can train the model and download the model weights too. But, when trying to validate/infer from the trained model, it fails with the following error:

`"OpenEO batch job failed: OpenEOApiException(status_code=400, code='Internal', message='No random forest model found for job j-231029b6164049ba92c3eada7603f037', id='no-request')"`

However, this is only the case when executing `openeo.dataspace.copernicus.eu` but works well when tested in `openeo.cloud` or `openeo.vito.be`

**Comment by jdries** [comment]
FYI we now have mounted the object storage bucket as a posix directory in the containers. 
Hence models can be saved and read from there, just like on YARN, so this should start working again with limited remaining effort.
Do note that the new bucket functionality may still be feature flagged, to be checked with @tcassaert .

**Comment by tcassaert** [comment]
There's a PR (#684) for this. It's not yet in use.

**Comment by EmileSonneveld** [comment]
Hey, I re-launched the job of `j-231029b6164049ba92c3eada7603f037` on https://openeo.dataspace.copernicus.eu/ and got a result. (My job ID was `j-240308cce2b542f691fdab4b0c088f1b`)
As I understand @tcassaert his fix did indeed work.

**Comment by tcassaert** [comment]
This is not on prod yet, so something else made it work then.

**Comment by EmileSonneveld** [comment]
CDSE staging and prod assign a different href to the model asset. The s3:// version works best. 
![MicrosoftTeams-image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/2298426/b80ab3b1-bf27-4226-9b0e-b8e63d356c2b)

Both backends have all files:
dev: `/OpenEO-data/batch_jobs/j-240327428e7f48269cbf04840296cb9f`
staging: `/OpenEO-data/batch_jobs/j-240322a516184973a25ae51c55005416`
![MicrosoftTeams-image (2)](https://github.com/Open-EO/openeo-geopyspark-driver/assets/2298426/b96b7119-ea5d-44bf-9b0f-53c85e681e14)
![MicrosoftTeams-image (1)](https://github.com/Open-EO/openeo-geopyspark-driver/assets/2298426/b0783251-f29d-4461-b807-feaefeb61963)

**Comment by JeroenVerstraelen** [comment]
Currently waiting on https://github.com/eu-cdse/openeo-cdse-infra/issues/115 to deploy the required mounts on CDSE prod. Then this issue should be finished.

**Comment by JeroenVerstraelen** [comment]
@Pratichhya You can use the following code for training and inference.

Training:
https://gist.github.com/JeroenVerstraelen/ddaf818b5ae71f0fca2dfc68271cec1b

Inference:
https://gist.github.com/JeroenVerstraelen/b26d89cf9c84e2dc4435fb47802ebaed
