### ISSUE TITLE
Eliminate vault based approach to get ETL API credentials

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#564]
At the moment there are multiple paths to obtain ETL API credentials: vault based on YARN/Terrascope deploy, env-var based on k8s deploys. The vault path involves a dependency on kerberos auth (e.g. need keytab), which trickles down in quite some places, making it hard to move some things around, e.g. for https://github.com/Open-EO/openeo-geopyspark-driver/issues/531

as discussed this week with @bossie  it's probably best for now to drop the vault based path, and just use env vars always to simplify things.

An advantage of using vault in our own app, compared to env vars,  is that it would support credential rotation automatically without need to restart/redeploy. However, so far we didn't have the need for that feature, so probably fine to lose it for now.

**Comment by bossie** [comment]
Right, note that eliminating the dependency on Vault entirely is not possible because we rely on it for the non-default SHub credentials on Terrascope, for which the actual OpenEO user needs authorization, so they can't be passed in @ deployment time.

**Comment by soxofaan** [comment]
yes I'm only talking about getting ETL API creds from vault, not any other vault usage

**Comment by soxofaan** [comment]
ETL OIDC creds now go through env vars both on Terrascope and CDSE.
Removed the logic to handle the unused vault path in a9f9ab7 to simplify the whole flow
