### ISSUE TITLE
Validation complains about missing products on CDSE

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#566]
When using SENTINEL2_L2A on CDSE, I now get warning about missing products:
`
[MissingProduct] Tile 'S2B_MSIL2A_20220604T104619_N0400_R051_T31UES_20220604T124954' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2B_MSIL2A_20220604T104619_N0400_R051_T31UFS_20220604T124954' in collection 'SENTINEL2_L2A' is not available. `

this is a bit special because CDSE is the reference archive, I'm not even sure how we can implement a proper missing products check on CDSE? Can we add config to disable this check there?

**Comment by soxofaan** [comment]
to reproduce (requires openeo client >= 0.24.0):

```python
import openeo
con = openeo.connect("openeo.dataspace.copernicus.eu")
con.authenticate_oidc()
cube = con.load_collection(
    "SENTINEL2_L2A",
    temporal_extent=["2022-06-01", "2022-06-10"],
    spatial_extent={"west": 3, "south": 51, "east": 3.01, "north": 51.01},
    bands=["B02"]
)
cube.download("tmp.nc")
```
this will show warning
> Preflight process graph validation raised: [MissingProduct] Tile 'S2A_MSIL2A_20220602T105631_N0400_R094_T31UDS_20220609T120117' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2A_MSIL2A_20220602T105631_N0400_R094_T31UES_20220609T120117' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2B_MSIL2A_20220604T104619_N0400_R051_T31UES_20220604T124954' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2B_MSIL2A_20220604T104619_N0400_R051_T31UDS_20220604T124954' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2B_MSIL2A_20220607T105619_N0400_R094_T31UES_20220607T125419' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2B_MSIL2A_20220607T105619_N0400_R094_T31UDS_20220607T125419' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2A_MSIL2A_20220609T104631_N0400_R051_T31UDS_20220609T171618' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2A_MSIL2A_20220609T104631_N0400_R051_T31UES_20220609T171618' in collection 'SENTINEL2_L2A' is not available.




To directly get validation report without having to wait for the `download()` to complete, instead do:
```python
print(con.validate_process_graph(cube))
```

**Comment by soxofaan** [comment]
FYI as discussed: I pushed a quick workaround to avoid spamming users with buggy validation reports: extensive collection based validation is disabled on production instances with c63728c

**Comment by EmileSonneveld** [comment]
The creo catalog can let know by itself that it has 'ARCHIVED' products. As I understand, the current check will log them if they are encountered. However, something goes wrong, and 'ONLINE' products are logged instead.

**Comment by jdries** [comment]
I disabled missing product check on CDSE for now. We'll need to investigate the above mentioned issue where 'ONLINE' products are logged as missing.

It is also very much the question if this procedure really finds all products for which no L2A product exists. It seems that we only find the ones that have been archived, but not the ones that were never in the catalog in the first place.

**Comment by soxofaan** [comment]
FYI:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/a9f9ab7ce5fa04f07ea077ea0c40a83d0acee2f4/openeogeotrellis/layercatalog.py#L1042-L1044
https://github.com/Open-EO/openeo-geopyspark-driver/blob/a9f9ab7ce5fa04f07ea077ea0c40a83d0acee2f4/openeogeotrellis/catalogs/creo.py#L202-L206

Our current implementation parses "AVAILABLE" vs  "ORDERABLE" as follows
https://github.com/Open-EO/openeo-geopyspark-driver/blob/a9f9ab7ce5fa04f07ea077ea0c40a83d0acee2f4/openeogeotrellis/catalogs/creo.py#L85-L99 

note that this terminology is different from the "ARCHIVED" and "ONLINE" you are talking about

**Comment by EmileSonneveld** [comment]
So the offline products where already removed when deduplicating products with the scala code. 
I changed it to take the difference between offline and online products per creodias space/time key.

@soxofaan Does that sound ok? Otherwise, I can also just remove the check there

**Comment by soxofaan** [comment]
I don't completely understand what you say here, and I don't know these catalogue details well enough to be honest.

I had a look at PR #584  as well and I'm confused that  `missing = offline - online`, isn't it just `missing = offline`? I mean how can a tile be both online and offline?

**Comment by EmileSonneveld** [comment]
Tiles can have multiple versions, typical a difference processingBaseline. It looks like a whole bunch of old processingBaseline tiles have been archived and appear `offline` now. They still show up in the catalogue, because users can manually request them from the archieve.

With this fix, I assume that if a tile (a location and date) has an `offline` and an `online` version, we pick the `online` one and we are ok. 
An other option would be to do a single catalogue request, and keep track of the "status" property. If after deduplication, there is still an `offline` tile, we give the warning. (Needs changes in scala then)

**Comment by soxofaan** [comment]
Ok thanks for that explanation, I guess it's worth to put a comment about this in the implementation.

what I also find confusing (again, I'm not that familiar with the creodias catalogue api), is that we pre-define these  status values "available", "orderable" and "not found" here
https://github.com/Open-EO/openeo-geopyspark-driver/blob/a9f9ab7ce5fa04f07ea077ea0c40a83d0acee2f4/openeogeotrellis/catalogs/base.py#L6-L9
while you talk about "offline" and "online". Is there some documented listing we (can) follow? There is this reference but that link is dead:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/a9f9ab7ce5fa04f07ea077ea0c40a83d0acee2f4/openeogeotrellis/catalogs/creo.py#L88-L93
