### ISSUE TITLE
`[401] unknown: Unauthorized`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#569]
Users sometimes get an obscure error along the lines of
```
openeo.rest.OpenEoApiError: [401] unknown: Unauthorized
```
(this is how openeo python client typically renders it)

**Comment by soxofaan** [comment]
With the help of a user of openeo-dev.vito.be I could reconstruct the response  received client side:
- HTTP status code 401
- headers: `{'Content-Type': 'application/json', 'Date': 'Mon, 06 Nov 2023 14:17:09 GMT', 'Content-Length': '26', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'}`
- response body: `{"message":"Unauthorized"}`


I didn't find traces of the request in the app logs (of geopyspark web app), and the lack of a "code" and "id" field also indicate that this response is not coming from the geopyspark webapp itself.

This must be coming from some proxy middelware, but it's not clear from where (headers don't give any hint to me)

**Comment by soxofaan** [comment]
This user is also hitting this (through openeo.cloud): https://discuss.eodc.eu/t/esa-world-cereal/639/31

**Comment by soxofaan** [comment]
another case? https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/posts/14590725361309-Authentication-error-OpenEO-401-Unauthorized-CASSINI-hackathon

**Comment by jdries** [comment]
Traefik has a number of 401's yesterday, so seems possible that it's coming from there?

**Comment by tcassaert** [comment]
We indeed pinpointed that the 401s and 403s are coming from Traefik, via a plugin that gets the info from the cost API.
The error message should be improved, to allow us to identify the request more easily.

**Comment by akasom89** [comment]
Hello 

Thanks @soxofaan for opening this thread. 

I face the same issue. Is there any solution. I used my GOOGLE account in EGI. My target is to use a collection on VITO. 

I place here the log of the error.

![Error](https://github.com/Open-EO/openeo-geopyspark-driver/assets/155361800/82e8b3be-5fb1-408d-bec1-cdfb18f9f206)

Is there any other option or solution for this!? If you go backward of python client version, would it help?

Thanks in advance

**Comment by Simoniman** [comment]
@akasom89 

I faced the same problem. It seemed the authentication done by this line of code, is not enough (it only give access to VITO) : 

connection = openeo.connect("openeo.vito.be").authenticate_oidc()

I solved it by signing in Terrascope.be using "EduGAIN & social logins" Button and access terrascope too.

Then I could download the data. 

Maybe this is a bug that should be handled in the background.

**Comment by soxofaan** [comment]
>  If I go backward in python client versions, would it help?

No that won't change a thing. This is back-end side problem, the client-side python version is irrelevant

**Comment by JanssenBrm** [comment]
The API backend is now updated to return a better response code in these cases. It should also provide a better integration with the python client in case tokens get expired. 

However, the issue can have several causes. The most plausible solution is the one provided by @Simoniman. In case you are receiving this error, please confirm your registration by registering through https://openeo.cloud/.

**Comment by soxofaan** [comment]
Given the latest back-end changes (and some python client side tweaks), the actual error message won't be `[401] unknown: Unauthorized` anymore, and will instead contain more information about the actual problem.
It think we can close this ticket #569 and just start new, more fine grained tickets for the different root causes.

E.g. @akasom89 : can you retry and confirm that you get another error message?
