### ISSUE TITLE
'resample_cube_spatial' can't handle temporally reduced input

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#58]
The function `resample_cube_spatial` can't seem to handle data that is temporally reduced, i.e. has undergone a `reduce_dimension(.. dimension = t ..)` process. It throws the error `geotrellis.layer.SpatialKey cannot be cast to geotrellis.layer.SpaceTimeKey` when both `data` and `target` or just `data` are temporally reducedand, and the error `TypeError: can't compare offset-naive and offset-aware datetimes ` when reduced data is put as `target`. When the `reduce_dimension` is done _after_ the resampling, the process runs without error.

Example process, expected to throw the error above:
`{
  "process_graph": {
    "load_collection_TWKYF6910T": {
      "arguments": {
        "bands": [
          "VV"
        ],
        "id": "TERRASCOPE_S1_SLC_COHERENCE_V1",
        "spatial_extent": {
          "east": 4.5277,
          "north": 50.9305,
          "south": 50.7816,
          "west": 4.2369
        },
        "temporal_extent": [
          "2020-10-01",
          "2020-10-31"
        ]
      },
      "process_id": "load_collection"
    },
    "load_collection_VGBOT9882O": {
      "arguments": {
        "bands": [
          "NIR"
        ],
        "id": "PROBAV_L3_S5_TOC_100M",
        "spatial_extent": {
          "east": 4.5277,
          "north": 50.9305,
          "south": 50.7816,
          "west": 4.2369
        },
        "temporal_extent": [
          "2020-10-01",
          "2020-10-31"
        ]
      },
      "process_id": "load_collection"
    },
    "reduce_dimension_MQUHW5102U": {
      "arguments": {
        "context": null,
        "data": {
          "from_node": "load_collection_VGBOT9882O"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "mean_ZQKLU1648K": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "ignore_nodata": true
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "resample_cube_spatial_SSRYY7709G": {
      "arguments": {
        "data": {
          "from_node": "reduce_dimension_MQUHW5102U"
        },
        "method": "near",
        "target": {
          "from_node": "load_collection_TWKYF6910T"
        }
      },
      "process_id": "resample_cube_spatial"
    },
    "save_result_HQUXV2759H": {
      "arguments": {
        "data": {
          "from_node": "resample_cube_spatial_SSRYY7709G"
        },
        "format": "NetCDF",
        "options": {}
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

**Comment by jdries** [comment]
Yes indeed, this is simply not yet implemented, need to make it more generic! 
Can you continue with the workaround you found yourself?

**Comment by jonathom** [comment]
Yes, it works fine when switching the two processes.

**Comment by jdries** [comment]
This one seems to work now, on openeo-dev.
