### ISSUE TITLE
user unable to start batch jobs if previous spark-job omits status key (kubernetes)

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#580]
When listing the spark-jobs of a user with:
```
result = api_instance.list_namespaced_custom_object(
                        "sparkoperator.k8s.io", "v1beta2", pod_namespace, "sparkapplications",
                        label_selector = label_selector
                    )
```
It is possible that some of the jobs in the output do not have a 'status' key. In this case the user is unable to start a batch job. Our code should log when this happens but not throw an error.

https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/backend.py#L2157

**Comment by jdries** [comment]
this is a live issue, should be treated as critical, committed a first attempt to quickfix this

**Comment by jdries** [comment]
closing as solved, need to reopen if we see it again
(still waiting for prod deploy)
