### ISSUE TITLE
Unexpected results when using `divide`

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-geopyspark-driver#581]
I use the below code to calculate a 'score' parameter. The pixel values for the first date of the _day_of_month_ cube are 4. (float32). When the `date_score` function is applied, I get the result -2. instead of the expected -2.2 ((4 - 15) / 5)

When I use `day.subtract(15).multiply(0.2)` instead of  `day.subtract(15).divide(5)`, I do get the expected result of -2.2

```
c=openeo.connect("openeo.vito.be").authenticate_oidc()

scl = c.load_collection(
    "SENTINEL2_L2A",
    spatial_extent=spatial_extent,
    temporal_extent=temporal_extent,
    bands=["SCL"]
)

label = Parameter('label')

def day_of_month_calc(input):    
    day = lambda x:15 + x.process("date_difference",date1=x.process("date_replace_component",date=label,value=15,component="day"),date2=label,unit="day") 
    return input.array_apply(day)  

def date_score(day):
    return day.subtract(15).divide(5)

day_of_month = scl.apply_neighborhood(
        day_of_month_calc,
        size=[{'dimension': 'x', 'unit': 'px', 'value': 1}, {'dimension': 'y', 'unit': 'px', 'value': 1},
              {'dimension': 't', 'value': "month"}],
        overlap=[]
    )

date_score = (1.0 * day_of_month).apply(date_score)
```

**Comment by soxofaan** [comment]
@VincentVerelst   does dividing by a float give correct result? E.g. `.divide(5.0)`  or `.divide(5.678)`. I kind or remember we tried that without success. 
I guess we should do the same for divide as for multiply: promote to float if at least one of the arguments is float.

**Comment by VincentVerelst** [comment]
@soxofaan , no dividing by float also doesn't give the correct result.

**Comment by VincentVerelst** [comment]
The same problem seems to hold for `power` by the way.

**Comment by jdries** [comment]
I now force these operations to return floats, see PR.

**Comment by jdries** [comment]
Tested on cdse staging, and I now correctly get floats.
Note that the 'apply' process already included conversion to float, so not entirely sure at what point it went back to ints.

Note that the callback in original example can also be replaced with:
`date_score = (day_of_month -15) /5`

In any case, it looks more correct now, so closing.
