### ISSUE TITLE
apply temporal UDF to RDD with EmptyMultibandTile

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#583]
Requested for People-EA:
aggregate_temporal_period on cube with nodata gaps
run udf over time dimension

UDF should receive nodata tiles for empty compositing intervals.
These are represented by EmptyMultibandTile, so conversion to numpy rdd may crash on that.

**Comment by JeroenVerstraelen** [comment]
Tested with process graph that performed an apply_dimension UDF after an aggregate_temporal (which introduces Constant tiles through EmptyMultibandTiles). Previously it gave this error:

`OpenEO batch job failed: Exception during Spark execution: class geotrellis.raster.FloatConstantTile cannot be cast to class geotrellis.raster.FloatArrayTile (geotrellis.raster.FloatConstantTile and geotrellis.raster.FloatArrayTile are in unnamed module of loader org.apache.spark.util.MutableURLClassLoader @595ba4ef)
`

Now the batch job completes without issues.
