### ISSUE TITLE
Convert AgERA5 collection to STAC

### ISSUE THREAD

**Issue by mbuchhorn** [Open-EO/openeo-geopyspark-driver#591]
job-id: 
j-2311167f76864f8ba91d15a2a2c185a0

Issues:
I requested the temperature-mean band from the AgERA5 collection, but it looks like the dewpoint-temperature was used!!!! See image

![image](https://github.com/Open-EO/openeo-api/assets/125027391/8adc2029-78aa-4fc9-839f-b71bad9de5ea)

 
![image](https://github.com/Open-EO/openeo-api/assets/125027391/78c5bb92-ab5b-470e-9ce9-26feab2530be)

**Comment by jdries** [comment]
The necessary config for basic stac has been created.
TODO:

- [ ] find scale and offset parameters
- [ ] generate http links rather than posix (to terrascope download service)
- [ ] mount agera5 on terrascope download service
- [ ] upload stac metadata to openeo stac api

**Comment by jdries** [comment]
Catalog online with data for 202x:
https://radiantearth.github.io/stac-browser/#/external/stac.openeo.vito.be/collections/agera5_daily

**Comment by jdries** [comment]
updated it again starting from 2010, with latest stac builder.
