### ISSUE TITLE
best available pixel: experiment with low-resolution cloud mask

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#592]
Loading the cloud mask at 60m resolution could be a way to speed things up further. We do not necessarily need a very refined cloudmask for this kind of method.

**Comment by VincentVerelst** [comment]
I've ran the algorithm on a 20x20km sample. Both by using the full UDF method and by using pre-defined processes for the date score. Both were run with an SCL resolution of 20m and 60m, below are the results.

It seems that lowering the SCL resolution has a big impact on the full UDF method, but not on the pre-defined processes method. 

![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/30296933/c4676d5c-139a-43d5-b293-957919bdc21d)
