### ISSUE TITLE
Terrascope Sentinel-2 data: gaps close to product overlap

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-geopyspark-driver#594]
When working with Terrascope S2 data I encounter two problems using the following spatiotemporal extents.

```
`spatial_extent = {"crs":"epsg:4326","east":-8.736381,"north":38.91534,"south":38.695691,"west":-9.011335487913325}
temporal_extent = ["2022-02-01","2022-03-01"]`
```

First, as seen in the screenshot below, part of a swath seems to be interrupted, while on the Terrascope viewer the data is uninterrupted.

![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/30296933/008ae0d7-3834-46e4-a42f-8a7baa244cad)

Secondly, when masking B02 data, some data, which should be masked away, remains there. The screenshot below shows the binary mask for a few selected dates (yellow = 1, purple = 0).

![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/30296933/c95e567d-d0b4-4cb2-a586-34c9fe285513)

When this mask is applied to raw B02 data, I obtain the following result:

![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/30296933/f107440d-f860-4e1e-b008-afcc22fa7317)

It can be seen that there remains some data left on 03 february, which should be masked away.

If I enlarge the spatial extent, I observe the same artefact on 03 february, but on different y-coordinates, as seen in the screenshot below.

![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/30296933/1fc164e8-b3c5-4c06-a921-a75e1b504b8a)

**Comment by jdries** [comment]
This simple script zooms in on the actual problem:

```

    spatial_extent = {"crs": "epsg:4326", "east": -8.85, "north": 38.91534, "south": 38.79,
                       "west": -9.011335487913325}
    temporal_extent = ["2022-02-11", "2022-02-14"]
    c = openeo.connect("openeo.vito.be").authenticate_oidc()
    cube = c.load_collection("TERRASCOPE_S2_TOC_V2", temporal_extent=temporal_extent,
                             spatial_extent=spatial_extent,
                             bands=["B02"], max_cloud_cover=75)
    cube.execute_batch('bad_terra5.nc')
```

Overlaying the results with shapes of sentinel-2 inputs, reveals that we're close to the edge of products here:

![image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/5937096/625f3cfb-02e4-44f3-9969-7ad3dd35f021)

**Comment by jdries** [comment]
Found the problem and pushed a fix: tile 29SNC had a very small bounding polygon, due to being on the edge of the swath. JTS then returned zero when computing the distance between this polygon and the tile extent, which is incorrect in our interpretation of this distance.
We now detect the empty polygon case explicitly, so we can deal with the situation.

**Comment by jdries** [comment]
The SCL band still has an issue.
Hypothesis: nodata value there is 0, but when loaded together with other bands, it needs celltype conversion, and this is probably not happening properly. 
The result is then, when merging overlapping tiles, an all-nodata tile could be chosen over a tile that has actual data...

**Comment by VincentVerelst** [comment]
It seems that a lot of the artefacts were a result of a difference in spatial resolution between the rgb_bands and the BAP rank_mask. By adding an explicit `resample_cube_spatial` the artefacts in the above region are gone. Also tested on two other regions; no artefacts were observed.

**Comment by jdries** [comment]
solved via recent other improvements
