### ISSUE TITLE
Internal Server Error on batch/preview job

### ISSUE THREAD

**Issue by Sijoma** [Open-EO/openeo-geopyspark-driver#6]
Hello all,

I am trying to get the results of a batch job and preview the job.

Tested with 2 process graphs:
## PG 1: 
```
{
  "process_graph": {
    "process_id": "NDVI",
    "process_description": "Computes the normalized difference vegetation index (NDVI) for all pixels and time slices of the input dataset.",
    "imagery": {
      "process_id": "filter_daterange",
      "process_description": "Creates a subset in including only values inside a given data range.",
      "imagery": {
        "process_id": "filter_bbox",
        "process_description": "Creates a subset in including only values inside a given bounding box.",
        "imagery": {
          "process_id": "get_collection",
          "process_description": "Finds the Collection to be processed.",
          "name": "CGS_SENTINEL2_RADIOMETRY_V102_001"
        },
        "extent": {
          "west": 10.9840519,
          "east": 11.2523813,
          "north": 46.5853562,
          "south": 46.7603795
        }
      },
      "extent": [
        "2018-01-27T11:13:29.024Z",
        "2018-04-28T11:13:29.024Z"
      ]
    },
    "red": "B04",
    "nir": "B8A"
  }
}
```

## PG 2:
```
{
  "process_graph": {
    "imagery": {
      "red": "B4",
      "nir": "B8A",
      "imagery": {
        "extent": [
          "2018-01-27T11:13:29.024Z",
          "2018-02-28T11:13:29.024Z"
        ],
        "imagery": {
          "extent": {
            "west": 10.9840519,
            "east": 11.2523813,
            "north": 46.5853562,
            "south": 46.7603795
          },
          "imagery": {
            "process_id": "get_collection",
            "name": "CGS_SENTINEL2_RADIOMETRY_V102_001"
          },
          "process_id": "filter_bbox"
        },
        "process_id": "filter_daterange"
      },
      "process_id": "NDVI"
    },
    "process_id": "max_time"
  }
}
```

## Response on http://openeo.vgt.vito.be/openeo/0.4.0/preview :
```
HTTP/1.1 500 Internal Server Error
Date: Tue, 12 Mar 2019 14:45:00 GMT
Server: nginx/1.10.3
Content-Type: application/json
Content-Length: 60
Access-Control-Allow-Origin: *
Connection: close

{
  "message": "'NoneType' object has no attribute 'get'"
}
```

## Response on http://openeo.vgt.vito.be/openeo/0.4.0/jobs 
```
HTTP/1.1 201 Created
Date: Tue, 12 Mar 2019 14:46:09 GMT
Server: nginx/1.10.3
Content-Type: text/html; charset=utf-8
Content-Length: 0
Location: http://openeo.vgt.vito.be/openeo/0.4.0/jobs/d3c4c928-1c17-4ac9-bcdd-ea4a740aeea2
Access-Control-Allow-Origin: *
Connection: close
```

## Response on http://openeo.vgt.vito.be/openeo/0.4.0/jobs/d3c4c928-1c17-4ac9-bcdd-ea4a740aeea2/results :
```
HTTP/1.1 500 Internal Server Error
Date: Tue, 12 Mar 2019 14:46:50 GMT
Server: nginx/1.10.3
Content-Type: application/json
Content-Length: 371
Access-Control-Allow-Origin: *
Connection: close

{
  "message": "Command '['./submit_batch_job.sh', 'OpenEO batch job d3c4c928-1c17-4ac9-bcdd-ea4a740aeea2', '/mnt/ceph/Projects/OpenEO/d3c4c928-1c17-4ac9-bcdd-ea4a740aeea2/in', '/mnt/ceph/Projects/OpenEO/d3c4c928-1c17-4ac9-bcdd-ea4a740aeea2/out', 'mep_tsviewer@VGT.VITO.BE', 'mep_tsviewer.keytab-799e0a26-f2fa-423b-a372-7b262fd6cd8c']' returned non-zero exit status 1"
}
```

**Comment by jdries** [comment]
I was not yet able to try it myself, but some quick suggestions:
The process graphs appear to be using version 0.3.x, could you try this endpoint:
http://openeo.vgt.vito.be/openeo/0.3.0/
The /jobs call will probably not work, but /preview is tested a lot more internally.

**Comment by Sijoma** [comment]
When using http://openeo.vgt.vito.be/openeo/0.3.1/preview or http://openeo.vgt.vito.be/openeo/0.3.0/preview

I get the following response: 
```
HTTP/1.1 500 Internal Server Error
Date: Tue, 12 Mar 2019 15:39:54 GMT
Server: nginx/1.10.3
Content-Type: application/json
Content-Length: 26
Access-Control-Allow-Origin: *
Connection: close

{
  "message": "'args'"
}

```

**Comment by m-mohr** [comment]
When running them in the Web Editor on http://openeo.vgt.vito.be/openeo/0.3.0, the Web Editor reports that there is no process called NDVI, which is true. The process list doesn't include the NDVI process any longer. Could that be added back for 0.3.0? Also, filter_daterange was already renamed filter_temporal for 0.3.0. Seems the 0.4.0 processes were backported to 0.3.0, which is not very useful for the 0.3.0 instance.

**Comment by Sijoma** [comment]
Yes, it would be for me to be able to run the version 0.3.x processes now instead of waiting on the implementation of the necessary features from every provider.

**Comment by m-mohr** [comment]
@jdries Would it be possible to get the old processes back for http://openeo.vgt.vito.be/openeo/0.3.0 in the next days? Would be very helpful for the compliance tests we are implementing and running...

**Comment by jdries** [comment]
Actually I'm afraid all of my old NDVI examples were based on UDF's. However, I might be able to implement the 'new' NDVI process:
https://github.com/Open-EO/openeo-processes/blob/master/ndvi.json
This should then also be usable from the 0.3.0 API.  Would that work for you?
Overall, there is really not a lot of room for me to fix issues that are specific to 0.3.0.

**Comment by m-mohr** [comment]
The new NDVI process is somewhat different from the old definition, see https://open-eo.github.io/openeo-api/v/0.3.1/processreference/#NDVI

Therefore it wouldn't help very much if you backport the new process as we need to process the same 0.3.1 compatible graphs on multiple back-ends to get meaningful results. Would it be possible to simply use the NDVI function as an "alias" for your UDF-based implementation?

The other issue is, that the 0.3 endpoint from VITO returns 0.4 processes now, which was not the case some days or weeks ago, but is not very usable by clients as the processes and schemas are completely incompatible. Would it be possible to revert that? Otherwise the 0.3 endpoint is not very useful for anybody, I guess.

Thanks!

**Comment by jdries** [comment]
@m-mohr I had a look, but I can't find a solution that is really trivial to implement. Our 0.3 endpoint is indeed not very useful for anything. I think the 0.4.0 support already covers more possibilities than what we could do in 0.3. (Except for UDF support.)
Given that we are going to need compliancy testing for 0.4.0 anyway, perhaps we can already create the equivalent process graph in that version? That could also be helpful to the backends that are currently implementing 0.4.0.

**Comment by m-mohr** [comment]
Somebody can probably do that, but due to different process specifications it is not very meaningful for the comparison in the master thesis. Due to time constraints of the master thesis (due mid June) Simon will only work on API v0.3 for now as most back-ends won't be 0.4 compatible in the next couple of weeks. That was agreed upon in one of the last dev telcos by the participants. So I guess we'll probably have to drop the VITO back-end from our compliance tests for now and retry once we'll work on 0.4 after June.

**Comment by jdries** [comment]
No problem to only include our backend for tests with 0.4.0, this gives me also more time to improve things, and get more reference data in.

**Comment by jdries** [comment]
Closing this old issue, seems outdated!
