### ISSUE TITLE
 about geopyspark==0.4.6+openeo

### ISSUE THREAD

**Issue by geostax** [Open-EO/openeo-geopyspark-driver#60]
Hi,
How can i find the python lib of geopyspark==0.4.6+openeo?
![image](https://user-images.githubusercontent.com/29589394/100879696-b6448b80-34e6-11eb-8f47-cfdba7c2f358.png)

**Comment by jdries** [comment]
Here:
https://artifactory.vgt.vito.be/webapp/#/artifacts/browse/tree/General/python-openeo/geopyspark/0.4.6+openeo/geopyspark-0.4.6+openeo-py3-none-any.whl
Other wheels for our backend can also be found there.

If you're looking for the source, it's here:
https://github.com/Open-EO/geopyspark
It's a fork, we only apply minor changes needed to build against newer versions of Geotrellis.

**Comment by geostax** [comment]
OK! it is really a great job. Looking forward to cooperating with you on this project.

**Comment by jdries** [comment]
Thanks! Happy to see other people trying it out.
There's one more jar you'll need for geopyspark:
https://artifactory.vgt.vito.be/auxdata-public/openeo/geotrellis-backend-assembly-0.4.6-openeo.jar
It's also built from that geopyspark fork repo.

**Comment by geostax** [comment]
By the way, did you apply geotrellis v3.5.0 in this project?

**Comment by jdries** [comment]
Yes! We're on the latest geotrellis 3.5.0, as it contains required bugfixes.

**Comment by soxofaan** [comment]
FYI: the travis file lists how to get the necessary dependencies:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/e33b176a39c1da2755373cb9ac5c3be13b9d5756/.travis.yml#L6-L10

I'll have a look if I can simplify this a bit further (e.g. I think the `requirements-dev.txt` can be eliminated)

**Comment by soxofaan** [comment]
I further simplified installation procedure to something like

    pip install . --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple
    python scripts/get-jars.py

(builds and integration tests are still running at the moment, so there might be some additional finetuning necessary)

**Comment by soxofaan** [comment]
will close this ticket for now

feel free to reopen if you encounter more install/setup issues
