### ISSUE TITLE
`aggregate_spatial` download not following requested save_result format (e.g. GeoJSON)?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#620]
user wants to dowload result of `aggregate_spatial` in GeoJSON format (or something else) that allows inspecting the geometries.

example:

### setup

```python
import openeo
con = openeo.connect("openeo-dev.vito.be").authenticate_oidc()

cube = con.load_collection(
    "SENTINEL2_L2A",
    temporal_extent="2023-09",
    bands=["B02"],
)

geometry = {
    "type": "Polygon"
    "coordinates": [[[5.076, 51.22], [5.076, 51.216], [5.084, 51.217], [5.08, 51.221], [5.076, 51.22]]],
}
```

###  Spatiotemporal
```
vc = cube.aggregate_spatial(geometry, reducer="mean")
vc.download("tmp.geojson", format="GeoJSON")
```

does not result in GeoJSON, but our ad-hoc json format
```
{"2023-09-02T00:00:00Z":[[2821.200693756194,2609.406342913776,2399.656095143707,2181.0545094152626,2508.486124876115,3052.7879088206146,3255.195242814668,3276.349851337958,3324.8186323092173,7501.266105054509,1988.806739345887,1690.5792864222003,156.0,8.189791873141724,null,71.0812685827552,255.0,1.0,165.0,44.0,272.9603567888999,5.960356788899901,1.0]],"2023-09-04T00:00:00Z":[[421.3726461...
```

Seems the user provided format is completely ignored, even downloading with invalid format works:
```python
vc.download("result-spatiotemporal.geojson", format="foobar")
# Same download format (JSON)
```

### Spatial

First eliminating the temporal dimension with temporal mean gives other behavior:

```python
vc = cube.reduce_temporal("mean").aggregate_spatial(geometry, reducer="mean")
vc.download("result-spatiotemporal.geojson", format="GeoJSON")
```

fails with 
> OpenEoApiError: [501] FeatureUnsupported: Unsupported output format geojson; supported are: JSON and CSV (ref: r-2312154de4f744cc9c0f0c6274062341)

Downloading with format JSON works:
```python
vc = cube.reduce_temporal("mean").aggregate_spatial(geometry, reducer="mean")
vc.download("result-spatiotemporal.json", format="JSON")
```
works and just gives a table in JSON:
```
[[2418.45242814668]]
```

The other suggested alternative CSV failed:

```python
vc = cube.reduce_temporal("mean").aggregate_spatial(geometry, reducer="mean")
vc.download("result-spatiotemporal.CSV", format="CSV")
```
with
> OpenEoApiError: [500] Internal: Server error: TypeError("send_file() got an unexpected keyword argument 'mimetypes'") (ref: r-2312151309444b60b81545adb99fcc7b)

**Comment by soxofaan** [comment]
related to 
- https://github.com/Open-EO/openeo-python-driver/issues/149

**Comment by jdries** [comment]
Is CoverageJSON perhaps the solution?

**Comment by jdries** [comment]
we now support geoparquet, would be good to check if that solves this issue?

**Comment by soxofaan** [comment]
possibly related/duplicate: #201

**Comment by JeroenVerstraelen** [comment]
Geojson is implemented.
Throw error for netCDF.
Look into json output because that still uses the old structure.

**Comment by VincentVerelst** [comment]
This is currently a blocking issue for https://github.com/Open-EO/openeo-gfmap/issues/87

**Comment by jdries** [comment]
@VincentVerelst  I just did a couple of experiments, also requesting csv and parquet, and I always just get the expected result. Can you give a code sample that doesn't work?

**Comment by VincentVerelst** [comment]
@jdries , for example j-240425ffc0c34991836f4dd8d8fb520a:
```python
c = openeo.connect('openeo.vito.be').authenticate_oidc()

s2 = c.load_collection(
    collection_id=collection,
    bands=bands,
    temporal_extent=temporal_extent
).reduce_dimension(dimension='t', reducer='mean')

features = s2.aggregate_spatial(geometries=geom, reducer='mean')

job = features.execute_batch(
    title='Point feature extraction',
    out_format='GeoParquet'
)
```
gives _FeatureUnsupportedException(status_code=501, code='FeatureUnsupported', message='Unsupported output format GeoParquet; supported are: JSON, CSV and GeoParquet', id='no-request')_

`geom` is a FeatureCollection of Points.

**Comment by jdries** [comment]
@VincentVerelst  can you try specifying it as 'Parquet', that is the official name:
https://openeo.vito.be/openeo/1.0/file_formats
I'll see where this error message comes from...

**Comment by VincentVerelst** [comment]
Confirmed `out_format='Parquet'` works!
