### ISSUE TITLE
Support geoparquet as output format type for VectorCubes.

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-geopyspark-driver#623]
Is it possible to support geoparquet as an output format type when downloading VectorCubes?

**Comment by bossie** [comment]
Related: https://github.com/Open-EO/openeo-geopyspark-driver/issues/271

**Comment by bossie** [comment]
@VincentVerelst could you share the process graph that you want to support this for?

**Comment by bossie** [comment]
[j-2312195ac86a4e7388aa5ead60702cdc_process_graph.json.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/13872488/j-2312195ac86a4e7388aa5ead60702cdc_process_graph.json.txt)

**Comment by bossie** [comment]
Is this what you expected? I appended .txt to the filename to be able to attach it to this issue.

[test_run_j_2312195ac86a4e7388aa5ead60702cdc_locally.parquet.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/14054390/test_run_j_2312195ac86a4e7388aa5ead60702cdc_locally.parquet.txt)

**Comment by jdries** [comment]
Yes, I can open this in QGis and ogrinfo also recognizes it, so looking fine.

**Comment by bossie** [comment]
TODO:

- [ ] include `feature_index` column

**Comment by bossie** [comment]
Available on https://openeo-dev.vito.be.
