### ISSUE TITLE
Sentinel-3 LST: add cloud info

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#625]
Collection: SENTINEL3_SLSTR_L2_LST
Sentinel 3 LST products come with cloud flags in two different files

Users will need this info for cloud maskiing

The ‘confidence_in’ variable contains quality information on the LST observation, and is detailed in Table
6. Note that the snow and sea-ice flag and the summary_cloud flag (now computed using only
probabilistic flag) are the only ones not directly transferred from SLSTR L1b product but recomputed
inside LST processing (see section 5.1.1).

**Comment by bossie** [comment]
Exposed as band "flags_in:confidence_in" (no aliases yet).
