### ISSUE TITLE
Plotting + alerting of benchmark results

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#628]
We systematically collect benchmark results:
https://kibana-apps.vgt.vito.be/app/kibana#/dashboard/9a857600-46b7-11ec-9c26-3f76720e6a27?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-90d%2Cto%3Anow))

I would like to add a visualization that shows:
- the distribution of results of last X months (e.g. X=4)
- the location of last 10 results plotted with respect to distribution

The next thing is then to have alerting with a dynamic threshold: for instance we could try to alert in grafana if results deviate by 2 standard deviations.

Note: I don't know if Grafana even allows for this.

**Comment by jdries** [comment]
other example of costs:
https://kibana-1.prod.warsaw.marketplace.dataspace.copernicus.eu/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-08T04:21:56.243Z',to:'2024-01-09T11:00:00.000Z'))&_a=(columns:!(cost,jobName,jobId,service,sourceId,value,unit,userId,duration),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'56cadb80-1005-11ee-8091-1bebee325886',key:sourceId,negate:!t,params:(query:vlcc),type:phrase),query:(match:(sourceId:(query:vlcc,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'56cadb80-1005-11ee-8091-1bebee325886',key:unit,negate:!f,params:(query:cpu-seconds),type:phrase),query:(match:(unit:(query:cpu-seconds,type:phrase))))),index:'56cadb80-1005-11ee-8091-1bebee325886',interval:auto,query:(language:kuery,query:'jobName:%20benchmarks*'),sort:!(!(date,desc)))

**Comment by VictorVerhaert** [comment]
Basic licence of kibana does not support alerting ("Watcher" plug-in)

**Comment by VictorVerhaert** [comment]
[Grafana dashboard](https://grafana.intern.vgt.vito.be/d/C4JHLKcIk/cdse-marketplace-benchmarks?orgId=1)
The benchmarks can be selected on top.

**Comment by jdries** [comment]
I have the impression that the current dashboard displays terrascope benchmarks rather then CDSE, so need to rename, and add another one for CDSE

**Comment by VictorVerhaert** [comment]
Dashboard has been renamed. Once I have the CDSE benchmarks I'll add a new dashboard for them.

**Comment by VictorVerhaert** [comment]
New dashboard for CDSE benchmarks has been created: https://grafana.intern.vgt.vito.be/d/tw84AttIk/cdse-marketplace-benchmarks
It seems there are only 2 benchmarks being run, is this correct?

**Comment by jdries** [comment]
correct, so now it's a matter of adding more.
We also see that they consume very little, so we may need bigger benchmarks to get relevant numbers.
________________________________
