### ISSUE TITLE
Questions about TERRASCOPE coherence dataset

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#63]
I have some questions about the TERRASCOPE_S1_SLC_COHERENCE_V1 dataset, that I hope you can help me with (quotes from the description):

> The product algorithm starts from two ESA Level-1 SLC products which are from the same area, the same relative orbit number and **preferably from within a short time interval** [my emphasis].

1. So far I just assumed these images would _always_ be successive images. Is that correct?
2. Which timestamps do they have in the collection, first or second acquisition?
3. Is there a way to know which two dates were used in the coherence calculation?

> This product exposes properties to enable filtering on relative orbit number and orbit direction.

4. I assume this feature has yet to be implemented - but how will it be done?

These details would be very interesting towards using this coherence product for change detection use cases, as it is important to know _in which time period_ changes occurred. I have outlined an example use case already in #53.

**Comment by jdries** [comment]
This description is perhaps a bit better:
https://docs.terrascope.be/#/DataProducts/Sentinel-1/ProductsOverview?id=slc-coherence
Also note the limited region!

This catalog query shows metadata of underlying products:
https://services.terrascope.be/catalogue/products?collection=urn:eop:VITO:TERRASCOPE_S1_SLC_COHERENCE_V1

1. Image pairs are 6 days apart
2. Second acquisition, the catalog lists both
3. That information is only in the catalog for now, openEO has only one date. But in our collection, the difference is always 6 days.
4. It is implemented by specifying properties in load_collection
 
This is one of the only examples I could find:
https://github.com/Open-EO/openeo-python-client/blob/master/tests/rest/datacube/test_datacube100.py#L366

```
im = con100.load_collection(
    "S2",
    spatial_extent={"west": 16.1, "east": 16.6, "north": 48.6, "south": 47.2},
    temporal_extent=["2018-01-01", "2019-01-01"],
    properties={
        "eo:cloud_cover": between(min=0, max=50),
        "platform": eq("Sentinel-2B", case_sensitive=False)
    }
)
```

**Comment by jonathom** [comment]
Perfect, thank you very much!
