### ISSUE TITLE
Investigate OpenEO result saving to bucket

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#645]
Would it be possible to specify a bucket, as long as an object name (or object template in the case of `sample_by_feature` enabled) where OpenEO automatically uploads the results of a job?

**Comment by jdries** [comment]
This is actully being defined mainly in the workspace API:
https://github.com/Open-EO/openeo-api/pull/518

also somewhat related to:
https://github.com/Open-EO/openeo-processes/pull/485

**Comment by jdries** [comment]
done: export_workspace will be implemented
