### ISSUE TITLE
how to solve the  "ERROR: No matching distribution found for rlguard-lib>=0.0.6" ?

### ISSUE THREAD

**Issue by automataIA** [Open-EO/openeo-geopyspark-driver#672]
After cloning the repository via:
`git clone openeo-geopyspark-driver`

and giving the command:
`pip install . --extra-index-url https://artifactory.vgt.vito.be/artifactory/api/pypi/python-openeo/simple`

It gives me this error (from the setup.py file):
`
ERROR: Could not find a version that satisfies the requirement rlguard-lib (from openeo-geopyspark) (from versions: none)
ERROR: No matching distribution found for rlguard-lib
`

How do I solve it?

**Comment by soxofaan** [comment]
@bossie I remember we did or were in the process eliminating this rlguard dependency. Do you know the status of this?

**Comment by bossie** [comment]
That would be https://github.com/Open-EO/openeo-geopyspark-driver/issues/216.

I'll remove the dependency and references to it.
