### ISSUE TITLE
terrascope EJR: too much logging

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#688]
ejr logging on cdse got reduced some time ago, but this solution does not apply to terrascope (yet) we should do the same there.

**Comment by soxofaan** [comment]
you mean EJR related logs happening from the job tracker cron job that show up in batch job logs seen by end users?

**Comment by JeroenVerstraelen** [comment]
@soxofaan @jdries Is this a change in log4j or in the code?

**Comment by jdries** [comment]
on cdse we solved it by putting EJR logs in a separate index, which is not included when retrieving logs. This avoids that we have to reduce all EJR logging, and also allowed to set lower retention time on job tracker index.
I however don't have an opinion on the best solution really, for me the most urgent thing is that users really shouldn't see this, as it reduces usability of logs quite a bit.

**Comment by soxofaan** [comment]
Indeed, I would fix this by piping the Terrascope job tracker logs to a dedicated index, like we do on CDSE

**Comment by soxofaan** [comment]
I think this one is done and can be closed
