### ISSUE TITLE
Item STAC metadata has no geometry or bbox for netCDFs with time series

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-geopyspark-driver#689]
The file below represents STAC item metadata for a netCDF with time dimensions generated on CDSE staging. It can be seen that the 'geometry' field is null. This issue can be reproduced on openeo-dev.vito.be.
Is it possible to include the 'geometry' field along with the 'bbox' field, as the latter is also required by the STAC spec if 'geometry' is not null.  (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md)

[item-example.json](https://github.com/Open-EO/openeo-geopyspark-driver/files/14383793/item-example.json)

Issue is related to https://github.com/Open-EO/openeo-geopyspark-driver/issues/646

**Comment by jdries** [comment]
I committed something for this, might be an easy fix.

**Comment by jdries** [comment]
@VincentVerelst  please check if it shows up now (on staging/dev)

**Comment by VincentVerelst** [comment]
[item-with-geometry.json](https://github.com/Open-EO/openeo-geopyspark-driver/files/14393640/item-with-geometry.json)
Seems to work now, thanks!
