### ISSUE TITLE
sentinel3: add solar angles to LST

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#696]
Solar angles can be used to determine night from day. This matters quite a bit for creating decent temperature composites.
These angles are provided in a lower resolution, so needs some work to correctly read and combine with other bands.

**Comment by bossie** [comment]
@jdries This concerns these datasets right?

NETCDF:"geometry_tn.nc":solar_azimuth_tn
NETCDF:"geometry_tn.nc":solar_zenith_tn

**Comment by jdries** [comment]
Yes!

**Comment by jdries** [comment]
@bossie  I think you are right about the non-square pixels, extract from data format spec:

> The resolution of this grid is 1 km on alongtrack direction and 16 km on across-track one

https://sentinels.copernicus.eu/documents/247904/1872792/Sentinel-3-SLSTR-Product-Data-Format-Specification-Level-2-Land.pdf/e587c02b-1454-46ff-b74e-bfc91943ae78?t=1637223909444

This would mean that you need to upsample the angles with a factor 16 along the x-axis, which would then immediately give you the output resolution?

**Comment by bossie** [comment]
Status update: ongoing, should be a gradient but looks like a rug.

![solar_azimuth_tn_rug](https://github.com/Open-EO/openeo-geopyspark-driver/assets/1032518/6f9402f3-b514-44b3-8843-6f92a2a8288e)

I noticed that these angle bands are treated differently in the original code by Bart O. so I'm adding that part to our code too.

**Comment by bossie** [comment]
Getting somewhere: proper gradient with values that match input.

![solar_azimuth_correct](https://github.com/Open-EO/openeo-geopyspark-driver/assets/1032518/2def1e8f-20f2-4d34-91ec-0b0302625729)

**Comment by bossie** [comment]
All bands including solar_azimuth_tn and solar_zenith_tn: [test_SENTINEL3_SLSTR_L2_LST_all.tif.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/14724968/test_SENTINEL3_SLSTR_L2_LST_all.tif.txt)

**Comment by jdries** [comment]
Nice!

**Comment by bossie** [comment]
Seems to work, needs collection test to make sure I didn't break anything. Can use some cleaning up as well.

**Comment by bossie** [comment]
Added `kube_resources.applications.integrationtests.tests.test_collections.test_compare_SENTINEL3_SLSTR_L2_LST` to test for regressions wrt/ current bands.
