### ISSUE TITLE
`linear_scale_range` throws unsupported operation error

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#71]
Upon applying a `linear_scale_range` I get a "unsupported operation" error. Is this known?

Test graph for reference:
`{
  "process_graph": {
    "1": {
      "process_id": "apply",
      "arguments": {
        "data": {
          "from_node": "reduce1"
        },
        "process": {
          "process_graph": {
            "2": {
              "process_id": "linear_scale_range",
              "arguments": {
                "x": {
                  "from_parameter": "x"
                },
                "inputMin": 0,
                "inputMax": 4000,
                "outputMin": 0,
                "outputMax": 255
              },
              "result": true
            }
          }
        }
      }
    },
    "loadco1": {
      "arguments": {
        "bands": [
          "B02",
          "B03",
          "B04"
        ],
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "spatial_extent": {
          "west": 4.181508513240051,
          "south": 50.770854338038305,
          "east": 4.326734351829529,
          "north": 50.84505243999911
        },
        "temporal_extent": [
          "2021-02-01T00:00:00Z",
          "2021-02-14T23:59:59Z"
        ]
      },
      "process_id": "load_collection"
    },
    "reduce1": {
      "arguments": {
        "data": {
          "from_node": "loadco1"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "mean1": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "savere1": {
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "format": "PNG",
        "options": {
          "red": "B4",
          "green": "B3",
          "blue": "B2"
        }
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

**Comment by soxofaan** [comment]
that's a known issue: see #45
