### ISSUE TITLE
SENTINEL3_SYN cloud flags band

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#716]
```
con = openeo.connect("openeo.dev.warsaw.openeo.dataspace.copernicus.eu").authenticate_oidc()

    spatial_extent = {"west": -100, "south": 50, "east": -95, "north": 60}
    temporal_extent = ["2021-08-03", "2021-08-10"]
    mask = con.load_collection(
        "SENTINEL3_SYN_L2_SYN",
        spatial_extent=spatial_extent,
        temporal_extent=temporal_extent,
        bands=["CLOUD_flags"]
    )
    mask.download("/tmp/s3_mask.nc")
```

KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/eodata/Sentinel-3/SYNERGY/SY_2_SYN___/2021/08/05/S3B_SY_2_SYN____20210805T180318_20210805T180618_20210807T201444_0179_055_255_1980_LN2_O_NT_002.SEN3/flags_in.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]
E

**Comment by JeroenVerstraelen** [comment]
For this sprint only an analysis needed.

**Comment by jdries** [comment]
When bounds went outside of product geometry, there are 0 valid lat/lon coords, hence the error.
Committed a fix + test.
