### ISSUE TITLE
Make Item ID configurable in Open-EO output STAC metadata

### ISSUE THREAD

**Issue by GriffinBabe** [Open-EO/openeo-geopyspark-driver#721]
@jdries In order to re-merge output samples with the correct input data we would require to have the item id in the output STAC metadata configurable by the user

**Comment by soxofaan** [comment]
is this by any chance a duplicate of https://github.com/Open-EO/openeo-geopyspark-driver/issues/722 ?

**Comment by kvantricht** [comment]
> is this by any chance a duplicate of [#722](https://github.com/Open-EO/openeo-geopyspark-driver/issues/722) ?

@GriffinBabe could you check this and either assign this ticket to someone who could take up the task or close it when it's already done?

**Comment by VincentVerelst** [comment]
https://github.com/Open-EO/openeo-geopyspark-driver/issues/722 should have indeed closed this issue as well (duplicate).
