### ISSUE TITLE
sample_by_feature: use feature property to name output items/assets

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#722]

**Comment by jdries** [comment]
@VincentVerelst on cdse staging, can you try setting feature_id_property in your format options? It needs to be set to a property of your vector data, like 'id' or something else that's unique.

**Comment by jdries** [comment]
@VincentVerelst  I had a look, I think it currently only works when you have a 'real' vector cube in filter spatial, rather than specifying geojson inline. 
We should also fix this, but it could be that it actually works already when gfmap loads the geometry from geoparquet.

**Comment by jdries** [comment]
Also made a commit to try and make it work for inline FeatureCollection, still needs to go through pipelines.

**Comment by JeroenVerstraelen** [comment]
Vincent confirmed that this works. (Geoparquet and geojson).
