### ISSUE TITLE
keep band names after aggregate_spatial

### ISSUE THREAD

**Issue by VictorVerhaert** [Open-EO/openeo-geopyspark-driver#723]
aggregate_spacial now replaces band names with derived names (e.g. B02_mean -> percentile_approx(band_0, 0.5, 100000) when using median as reducer).
An alternative to fixing this issue is adding the rename_labels process to vectorcubes so users can manualy rename the bands.

**Comment by VictorVerhaert** [comment]
In the jobresult metadata, the band names are still present. My test case was with exporting to a csv, where the column names are derived.
job_id: j-240507e5933c471bb7f06896f454e533 on CDSE.

**Comment by jdries** [comment]
Note that you can only keep the band names when only one statistic is computed. In the case of computing multiple stats, we are forced to create new band names, to keep them unique.

**Comment by jdries** [comment]
I added a branch showing a fix for csv. The issue may however not be fully accurate, in the sense that it is output format specific:
csv -> band names from spark
netcdf -> tries to use band names from python metadata
parquet -> constructs own band names here: https://github.com/Open-EO/openeo-python-driver/blob/413c7c0a7070590dce491102f4f0a1cc5b8c0ce2/openeo_driver/save_result.py#L568

**Comment by jdries** [comment]
Committed a fix for parquet, which is normally the most relevant format for worldcereal.

**Comment by jdries** [comment]
@VincentVerelst  can you do a check for parquet files on openeo-dev or cdse staging?
Should be better for that file format.

**Comment by jdries** [comment]
I now also improved it for CSV (still in build pipelines).
When only one reducer is specified, band names will be preserved as-is. (Most common case.)
In case of multiple reducers, it will be something like mean(B01), min(B01), mean(B02),min(B02) which is still an improvement over previous approach.
rename_labels after aggregate_spatial will not yet have an effect on csv output, that only works for parquet and netcdf for now.
