### ISSUE TITLE
VITO Backend -- OpenEo Api Error: [401] TokenExchangeFailure

### ISSUE THREAD

**Issue by eswan-star** [Open-EO/openeo-geopyspark-driver#725]
Hi there. 

I'm new to OpenEO and am working with the code provided on the ReadMe for the simple example. I'm running the code as is, signed up for an account and am logged in to both https://terrascope.be/ and https://portal.terrascope.be/. I am able to authenticate just fine but when I go to run the last line of code, `cube.download("ndvi-max.tiff")`, I get an **OpenEoApiError: [401] TokenExchangeFailure: Authentication failed. Please login on our marketplace web https://portal.terrascope.be/ first, and then try authenticate again.**

I make sure I am logged in and try again and I keep getting the same error. On the openEO Documentation for Error Handling, it says **401 Unauthorized: The client did not provide any authorization details (usually using the Authorization header), but authorization is required for this request to be processed.**

I'm wondering how to proceed for this example? I also tried a few different backends and their different versions with no luck. 
Any help would be appreciated! 

Thanks. 
-Elaine

**Comment by soxofaan** [comment]
Note that is not an issue in the openeo python client itself, but with the Terrascope backend and its credit check system.

While also not ideal, I think it's better to move this ticket under openeo-geopyspark-driver

**Comment by Pratichhya** [comment]
Also, I reached out to the user. The issue was said to have been resolved. @ElaineSwanny, please correct me if I am wrong.

**Comment by eswan-star** [comment]
Hi @Pratichhya Yes, it is working for me now.

**Comment by AM1729** [comment]
Hi @Pratichhya I am facing a similar issue while executing an UDP using the client. 

Once I try to login to the Terrascope using EduGAIN and Social Logins it says 
`User with email <email> already exists. How do you want to continue?`

Can you kindly guide me here..

**Comment by Pratichhya** [comment]
@AM1729 It seems like you have already registered, so maybe you can go to https://portal.terrascope.be/  and, during the logging process, add to the existing account.

And if it is fine could you share your email address or else you can directly mail eoplaza@terrascope.be with the error you have

**Comment by soxofaan** [comment]
@AM1729   how did you end up in this bug tracker to report your problem?  I'm just curious as there might be something wrong with guiding users to the proper support channels.

**Comment by AM1729** [comment]
Thanks @Pratichhya this was solved. 
@soxofaan I just searched the error as I was not very sure of the issue, and this popped up on the top.
