### ISSUE TITLE
bbox/geometry not present in stac with netCDF 

### ISSUE THREAD

**Issue by VictorVerhaert** [Open-EO/openeo-geopyspark-driver#733]
result of some jobs cannot be loaded using load_stac due to missing bbox/geometry in the item assets.

Example job (CDSE): [j-24031996c7024c089c7b1f5d80bef35e](https://openeo.dataspace.copernicus.eu/openeo/1.2/jobs/j-24031996c7024c089c7b1f5d80bef35e/results/ZmFiYTBmOTUtMDRiNy00NTYwLWFlYjQtYzAxNzJkZDlkZTA5/75f50e4641925eac5519285fa1eda945?expires=1711537596)

**Comment by jdries** [comment]
This looks like a single asset result, so no sample_by_features or anything. Should be reproducible with a simpler process graph as well.

**Comment by JeroenVerstraelen** [comment]
Best to double check.

**Comment by VictorVerhaert** [comment]
This issue seems to be fixed in my latests tryout.
