### ISSUE TITLE
array_element label is expecting number, not string

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#77]
When I try and select a band with `array_element` via `label` and a string, backend responds with `Expecting numeric value for 'label' but got 'B08'` error. E.g. like this in a python child process: `b8 = array_element(data, label = "B08")`. I think it would need to accept and handle strings as well.

Example graph to reproduce:
`{
  "process_graph": {
    "load_collection_VECWJ6541K": {
      "arguments": {
        "bands": [
          "B04",
          "B08"
        ],
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "spatial_extent": {
          "east": 5.7298,
          "north": 52.7335,
          "south": 52.6457,
          "west": 5.5661
        },
        "temporal_extent": [
          "2021-04-26",
          "2021-04-29"
        ]
      },
      "process_id": "load_collection"
    },
    "reduce_dimension_THJWN2638J": {
      "arguments": {
        "context": null,
        "data": {
          "from_node": "load_collection_VECWJ6541K"
        },
        "dimension": "bands",
        "reducer": {
          "process_graph": {
            "add_YFBHY8628T": {
              "arguments": {
                "x": {
                  "from_node": "array_element_GSQVG7902R"
                },
                "y": {
                  "from_node": "array_element_JUARV3831M"
                }
              },
              "process_id": "add"
            },
            "array_element_GSQVG7902R": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "label": "B08",
                "return_nodata": false
              },
              "process_id": "array_element"
            },
            "array_element_JUARV3831M": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "label": "B04",
                "return_nodata": false
              },
              "process_id": "array_element"
            },
            "divide_SGKYR4623C": {
              "arguments": {
                "x": {
                  "from_node": "subtract_XRPUQ8083V"
                },
                "y": {
                  "from_node": "add_YFBHY8628T"
                }
              },
              "process_id": "divide",
              "result": true
            },
            "subtract_XRPUQ8083V": {
              "arguments": {
                "x": {
                  "from_node": "array_element_GSQVG7902R"
                },
                "y": {
                  "from_node": "array_element_JUARV3831M"
                }
              },
              "process_id": "subtract"
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "save_result_YOPDW4987P": {
      "arguments": {
        "data": {
          "from_node": "reduce_dimension_THJWN2638J"
        },
        "format": "GTiff",
        "options": {}
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

**Comment by soxofaan** [comment]
Indeed this is a known issue
the geopyspark driver only supports (int) index in `array_element`

duplicate: #43 

(internal ref: EP-3583)

**Comment by jonathom** [comment]
I see. thanks!
