### ISSUE TITLE
Vectorcube batch job STAC collection don't contain any items

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-geopyspark-driver#787]
When downloading the results of a vectorcube batch job in any supported format (CSV, geoparquet,...) the resulting STAC collection doesn't contain any items. 

An example STAC collection for a CSV output (the result from job j-2405302269e44f85bc8d8876e31ccb77 on CDSE): 
[no-item-stac-collection.json](https://github.com/user-attachments/files/15512658/no-item-stac-collection.json)

**Comment by bossie** [comment]
@VincentVerelst for context, how will you be using/what will you be using these STAC items for?

**Comment by VincentVerelst** [comment]
@bossie 
- After a series of batch jobs to create a STAC collection with each item in the collection representing the Parquet output file of a specific batch job
- Once supported, read in the STAC collection with `load_stac`
