### ISSUE TITLE
Masking throws SpatialKey/SpaceTimeKey error

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#80]
As mentioned in [/python-client#212](https://github.com/Open-EO/openeo-python-client/issues/212), I am trying to mask a cube with data that comes from another cube, e.g. mask a radar image with an NDVI threshold or something like this, could also just be two bands not from the same collection. I've been trying around a little and always run into the `Error: geotrellis.layer.SpatialKey cannot be cast to geotrellis.layer.SpaceTimeKey`.

Below is the process graph with my intuitive approach. Because the above looks like a dimension error I tried reducing / not reducing specific dimensions on purpose (see e.g. second graph), to receive two cubes with the same dimensions, but always run into `SpaceTimeKey` error.

`{
  "process_graph": {
    "loadcollection1": {
      "arguments": {
        "bands": [
          "VV"
        ],
        "id": "S1_GRD_SIGMA0_ASCENDING",
        "spatial_extent": {
          "east": 5.7298,
          "north": 52.7335,
          "south": 52.6457,
          "west": 5.5661
        },
        "temporal_extent": [
          "2021-06-01T00:00:00Z",
          "2021-06-15T00:00:00Z"
        ]
      },
      "process_id": "load_collection"
    },
    "loadcollection2": {
      "arguments": {
        "bands": [
          "B04",
          "B08"
        ],
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "spatial_extent": {
          "east": 5.7298,
          "north": 52.7335,
          "south": 52.6457,
          "west": 5.5661
        },
        "temporal_extent": [
          "2021-06-01T00:00:00Z",
          "2021-06-15T00:00:00Z"
        ]
      },
      "process_id": "load_collection"
    },
    "resamplecubespatial1": {
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "method": "near",
        "target": {
          "from_node": "loadcollection2"
        }
      },
      "process_id": "resample_cube_spatial"
    },
    "reducedimension2": {
      "arguments": {
        "data": {
          "from_node": "loadcollection2"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "mean2": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "reducedimension1": {
      "arguments": {
        "data": {
          "from_node": "resamplecubespatial1"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "mean1": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "reducedimension3": {
      "arguments": {
        "data": {
          "from_node": "reducedimension2"
        },
        "dimension": "bands",
        "reducer": {
          "process_graph": {
            "add1": {
              "arguments": {
                "x": {
                  "from_node": "arrayelement1"
                },
                "y": {
                  "from_node": "arrayelement2"
                }
              },
              "process_id": "add"
            },
            "arrayelement1": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "index": 1
              },
              "process_id": "array_element"
            },
            "arrayelement2": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "index": 0
              },
              "process_id": "array_element"
            },
            "divide1": {
              "arguments": {
                "x": {
                  "from_node": "subtract1"
                },
                "y": {
                  "from_node": "add1"
                }
              },
              "process_id": "divide"
            },
            "lt1": {
              "arguments": {
                "x": {
                  "from_node": "divide1"
                },
                "y": 0.3
              },
              "process_id": "lt",
              "result": true
            },
            "subtract1": {
              "arguments": {
                "x": {
                  "from_node": "arrayelement1"
                },
                "y": {
                  "from_node": "arrayelement2"
                }
              },
              "process_id": "subtract"
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "mask1": {
      "arguments": {
        "data": {
          "from_node": "reducedimension1"
        },
        "mask": {
          "from_node": "reducedimension3"
        }
      },
      "process_id": "mask"
    },
    "saveresult1": {
      "arguments": {
        "data": {
          "from_node": "mask1"
        },
        "format": "GTiff",
        "options": {}
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

Second example without NDVI computation. Here, no dimension is reduced except the `time` dim of the mask cube.

`{
  "process_graph": {
    "1": {
      "arguments": {
        "bands": [
          "B04"
        ],
        "data": {
          "from_node": "reducedimension1"
        },
        "wavelengths": []
      },
      "process_id": "filter_bands"
    },
    "2": {
      "arguments": {
        "bands": [
          "VH"
        ],
        "data": {
          "from_node": "resamplecubespatial1"
        },
        "wavelengths": []
      },
      "process_id": "filter_bands"
    },
    "3": {
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "process": {
          "process_graph": {
            "1": {
              "arguments": {
                "x": {
                  "from_parameter": "x"
                },
                "y": 4000
              },
              "process_id": "lt",
              "result": true
            }
          }
        }
      },
      "process_id": "apply"
    },
    "6": {
      "process_id": "mask",
      "arguments": {
        "mask": {
          "from_node": "3"
        },
        "data": {
          "from_node": "2"
        }
      }
    },
    "loadcollection1": {
      "arguments": {
        "bands": [
          "B04",
          "B08"
        ],
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "spatial_extent": {
          "east": 5.7298,
          "north": 52.7335,
          "south": 52.6457,
          "west": 5.5661
        },
        "temporal_extent": [
          "2021-06-01T00:00:00Z",
          "2021-06-15T00:00:00Z"
        ]
      },
      "process_id": "load_collection"
    },
    "loadcollection2": {
      "arguments": {
        "bands": [
          "VV",
          "VH"
        ],
        "id": "S1_GRD_SIGMA0_ASCENDING",
        "spatial_extent": {
          "east": 5.7298,
          "north": 52.7335,
          "south": 52.6457,
          "west": 5.5661
        },
        "temporal_extent": [
          "2021-06-01T00:00:00Z",
          "2021-06-15T00:00:00Z"
        ]
      },
      "process_id": "load_collection"
    },
    "reducedimension1": {
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "mean1": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "reduce_dimension"
    },
    "resamplecubespatial1": {
      "arguments": {
        "data": {
          "from_node": "loadcollection2"
        },
        "method": "near",
        "target": {
          "from_node": "loadcollection1"
        }
      },
      "process_id": "resample_cube_spatial"
    },
    "saveresult1": {
      "arguments": {
        "data": {
          "from_node": "6"
        },
        "format": "GTiff",
        "options": {}
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

Do I have the wrong approach to masking or is there something else wrong?

**Comment by jdries** [comment]
The problem is caused by reducing the time dimension, and the fact that our backend doesn't support masking an x,y,t layer with an x,y layer.
Is it an option to not reduce over time, or can you indicate priority for supporting this?

**Comment by jonathom** [comment]
Thanks for the response. From that, other issues arise for me:
1. In the first process graph, I was reducing time for both cubes (still the time dimensions were different afterwards?). If I remove these reductions, unmasked data (in this case, S1) images are returned.
2. The same applies to the second process graph, the one where only one cube was reduced temporally. When I substitute `mask` for `merge_cubes`, I get data and masking layers back, looking like they should have produced a masked image - of course there are still multiple timesteps in the game that don't work well in the output formats.
> Is it an option to not reduce over time

Yes, but do the timestamps of both dimensions `t` need to match for masking then?

re. priority: Not very urgent. If I could wish for something I'd be more interested in an opportunity to calculate standard deviation from a neighbourhood ;) (#79)

**Comment by jdries** [comment]
The original issue should have been solved, masking an x,y,t collection with an x,y mask should now work. 
Please reopen if not fixed!
https://github.com/Open-EO/openeo-geopyspark-driver/commit/18b42b348923620d92b373c9bb282d2c12b4cef0
