### ISSUE TITLE
test local_batch_job.py with load_stac, see if output is written correctly

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#807]
- Add simple test that runs process graph using local_batch_job.py and hcecks if the output is valid.
- We will use load_stac for all datacube loading in local batch jobs
- add documentation

**Comment by EmileSonneveld** [comment]
This is implemented under https://github.com/Open-EO/openeo-geopyspark-driver/issues/839
