### ISSUE TITLE
sentinelhub processing: request cost estimate for large jobs

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geopyspark-driver#815]
We had an issue where a user with 1000 credits was able to run a job with sentinelhub processing where we had to pay for 270,000 openEO credits.

**Comment by EmileSonneveld** [comment]
Job id: `j-240613a84d384d6d8d34d7ece7855cd9`

**Comment by jdries** [comment]
@EmileSonneveld  anything still blocking this?

**Comment by EmileSonneveld** [comment]
Jeroen was going to check it out, but I think we can merge. If something goes wrong, the user is shown how to disable the check

**Comment by JeroenVerstraelen** [comment]
Checked the code, I don't see any issues for a merge!

**Comment by EmileSonneveld** [comment]
This caused an error in integration tests: test_simple_cloud_masking
Might be because of data_mask being copied in a context where it should not

**Comment by EmileSonneveld** [comment]
This works fine on staging. After deploy, it can be monitored with [kibana (internal link)](https://kibana-infra.vgt.vito.be/app/kibana#/discover/9385d820-3cdf-11ee-8cc4-3747d5233c59?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-8d,to:now))&_a=(columns:!(levelname,message,filename),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'592a42f0-e665-11ec-8cc4-3747d5233c59',key:levelname,negate:!f,params:(query:ERROR),type:phrase),query:(match:(levelname:(query:ERROR,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'592a42f0-e665-11ec-8cc4-3747d5233c59',key:name,negate:!f,params:(query:openeogeotrellis.deploy.batch_job),type:phrase),query:(match:(name:(query:openeogeotrellis.deploy.batch_job,type:phrase))))),index:'592a42f0-e665-11ec-8cc4-3747d5233c59',interval:auto,query:(language:kuery,query:'message:*ProcessGraphComplexityException*'),sort:!(!('@timestamp',desc))))
