### ISSUE TITLE
local_batch_job.py investigate logging

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#838]
same file?
json logging?

**Comment by JeroenVerstraelen** [comment]
EPIC: https://github.com/Open-EO/openeo-geopyspark-driver/issues/806

**Comment by EmileSonneveld** [comment]
The logging is visible unstructered while running in the console, and JSON-structured output is written in `openeo.log`.
In the JSON, there are some variables that could be filled in: `"user_id":"${env:OPENEO_USER_ID}","job_id":"${env:OPENEO_BATCH_JOB_ID}"`
