### ISSUE TITLE
python-memory should also have a maximum

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geopyspark-driver#850]
This job should throw an error early on: `j-240827102bf84bf798aebf2193155558`
job_options:
```json
{
  "executor-memory": "10g",
  "python-memory": "10g",
  "udf-dependency-archives": [...]
}
```

Probably need to update this code:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/8c0023593d7578ef925f0072d745ce00d6515203/openeogeotrellis/backend.py#L1762

cc @pvbouwel

**Comment by JeroenVerstraelen** [comment]
Waiting for code review
