### ISSUE TITLE
Support new implementation of stac fields querystring parameter 

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geopyspark-driver#862]
On stac.openeo.vito.be, adding '&fields=+properties.proj:epsg' in the query string makes sure this field is included in the results (by default it is hidden)
But when doing the same on stac-openeo-dev.vgt.vito.be, it removes all fields and only shows the one specified. Once this logic is promoted to prod, our stac catalogs will give errors. Best it to specify a list of all properties we need to have no issues in the transition period
 
Url that shows the issue: https://stac-openeo-dev.vgt.vito.be/search?limit=20&bbox=8.058428808185612%2C40.66%2C8.999%2C41.291280668691115&datetime=2017-12-22T00%3A00%3A00Z%2F2017-12-24T23%3A59%3A58.999000Z&collections=copernicus_r_utm-wgs84_10_m_hrvpp-vi_p_2017-now_v01&fields=+id
 

Where the code needs to be updated: https://github.com/Open-EO/openeo-geopyspark-driver/blob/dd4b2d9ecf3844e05a7ec93b33e43b5f1bf525d5/openeogeotrellis/load_stac.py#L240

(cc @bossie )

**Comment by EmileSonneveld** [comment]
I understood that stac.openeo.vito.be waits for this ticket to be implemented to update their server.

**Comment by JeroenVerstraelen** [comment]
I checked with Stijn Caerts and he responded with the following

>Hey Jeroen, on our side, there is no deadline to complete this issue. The Terrascope and openEO STAC API versions are decoupled, so we have already done the release within Terrascope. The one for openEO can happen when you are ready.


So we can delay this issue until the next sprint.

**Comment by jdries** [comment]
some users actually use the terrascope stac endpoint as well, so the assumption that this could be postponed was wrong.
From what I can tell, in the new implementation, we can just drop the 'fields' parameter, and we'll get all the metadata?

Specifying actual fields seems more like an optimization, but then we need consistency across catalogs first.

**Comment by EmileSonneveld** [comment]
https://stac.terrascope.be/collections/sentinel-2-l2a now works on https://openeo.vito.be/openeo/
TODO: CDSE

**Comment by StijnCaerts** [comment]
https://stac.openeo.vito.be/ has been updated to our latest version 1.0.3.

**Comment by EmileSonneveld** [comment]
I started integration tests
A quick vegetation indices test went fine

**Comment by EmileSonneveld** [comment]
Works fine without the fields querystring too
