### ISSUE TITLE
Sentinel-2 processing issues - missing blocks

### ISSUE THREAD

**Issue by mbuchhorn** [Open-EO/openeo-geopyspark-driver#865]
usage of my S1/S2 processing pipelines at CDSE leads to unexpected results:
- partly or completely unprocessed (filled with nodata) blocks within the band (e.g. B06 reflectance of S2) but each timeseries steps has different unprocessed blocks!
- last block in a band has all values of 32769 (but the nodata value is 65535)
- order of unprocessed to processed blocks are the same over all reflectance bands in the same timestep   
- clear artefacts are seen between two processed blocks - value break between neighboring blocks
- static DEM band which is just copied to all timesteps shows in the last timesteps artefacts (see also https://github.com/WorldCereal/worldcereal-classification/issues/141)

job info:
https://openeo.dataspace.copernicus.eu/openeo/1.2/jobs/j-24091249a9984c939a40c97fcfbeebcf/results/MTMxMjk0OTctMDVmNi00NTIwLThiNjMtNWI3NjI0OTU5ZGQ4/4e358f09302d71c7e41ddfd41668ac17?expires=1726753081

used repository:
https://github.com/ESA-WEED-project/eo_processing

example code to replicate bug:
https://github.com/ESA-WEED-project/eo_processing/blob/main/notebooks/example_time-series_VIs_features.ipynb

![image](https://github.com/user-attachments/assets/cccd4504-2ce8-42aa-be8e-4dd4cb40a4ee)

![image](https://github.com/user-attachments/assets/4f246690-cd5c-4076-8518-b24c474fac87)

![image](https://github.com/user-attachments/assets/f505a4ad-0fae-449c-81a2-425b6299faad)

**Comment by mbuchhorn** [comment]
UPDATE!!!!
I implemented the new SCL cloud masking and that fixed the missing blocks etc. BUT new issues popped up:
- S1 HH and HV -> last time step is all nodata (in every test)
- dataset is too big -> should be 700x700 pixel and is now 701x701 pixel (looks like the S1 and S2 datasets have an extra pixel) --> with old SCL cloud masking the datacube had the correct dimension
- DEM dataset generated from static input has extra lower line nodata and right column nodata (looks like was correctly generated with 700x700 pixel & then filled)


job info:
https://openeo.dataspace.copernicus.eu/openeo/1.2/jobs/j-240912e9e52948068aa1249eebc7fffc/results/MTMxMjk0OTctMDVmNi00NTIwLThiNjMtNWI3NjI0OTU5ZGQ4/6f9f2af91e26ccc83477fb84ceb257b2?expires=1726781292

used repository:
https://github.com/ESA-WEED-project/eo_processing

example code to replicate bug:
https://github.com/ESA-WEED-project/eo_processing/blob/main/notebooks/example_time-series_VIs_features.ipynb

**Comment by jdries** [comment]
The extent of the output is shifted by 5m, possibly explaining the extra pixel. Need to see where this comes from.

**Comment by mbuchhorn** [comment]
I saw that too. I have the feeling that somewhere in the pipeline the datacube shifts from "area" to "point". I mean, in NetCDF the reference is always "center of pixel" and therefore to get the coordinate 5 m shifted is correct BUT I see the same coordinates also when I generate the output as GTiff. So something goes wrong.

Even worse.... it looks like it is only the metadata??!!!??  When I open the netCDF and look to the coordinate array then I see this:
![image](https://github.com/user-attachments/assets/08d553f4-2894-4ce8-a914-ead805ba8ff9)

that are the requested UL coordinate of the BBOX - except that it is 0ne pixel too much in the right and one pixel too much in the bottom. Requested BBOX was:
![image](https://github.com/user-attachments/assets/f954fcb0-cc3d-49ce-9eb2-060bc65184cb)

**Comment by jdries** [comment]
@mbuchhorn I believe I found the cause of the extra pixel. It is very important to load the SCL band in a separate 'load_collection' call. We have an optimization to only load data that is not masked, but this won't work if you explicitly ask to load all the data first.
As a side effect, the buffering that we need to apply to correctly create the cloud mask adds this extra unwanted pixel.

Here's how your process graph should look like:

![Image](https://github.com/user-attachments/assets/06f18590-e496-465a-bcc7-23604649cc38)

**Comment by mbuchhorn** [comment]
looks like all is working now

**Comment by kvantricht** [comment]
@mbuchhorn is this missing timesteps for S1 also solved?

**Comment by mbuchhorn** [comment]
@kvantricht in my current tests I have also a last timestep for the S1 data --> it is only strange that the S1 10daily composite from 21-12-2021 to 31-12-2021 gives not back a complete image (only half of the scene is filled), but that could be due to the Sentinel-1 issues which arise on December 23 2021 :)
