### ISSUE TITLE
support upload to /files endpoint

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#866]
For upload of small, temporary, auxiliary data, we should support:
https://api.openeo.org/#tag/File-Storage/operation/upload-file
And then allow its use for reading of catboost models.

It should only work on deployments with object storage available. Just write file to a user specific directory.

Next steps is automatic cleanup and/or credit based accounting.

**Comment by JeroenVerstraelen** [comment]
Can be done via S3 proxy with OIDC support by @pvbouwel.

**Comment by pvbouwel** [comment]
Features required should be enabled via https://github.com/eu-cdse/openeo-cdse-infra/issues/262

**Comment by jdries** [comment]
closing this one, we have an alternative
