### ISSUE TITLE
support point/line geometries in `aggregate_spatial`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#88]
The Geopyspark driver currently only supports polygon geometries in `aggregate_spatial`, while the official spec https://github.com/Open-EO/openeo-processes/blob/60fb5e22579f34010de42af71c3d2d70f2dea906/aggregate_spatial.json#L20 also defines behavior for point and line geometries.

This ticket is to at least document/discuss that the geopyspark driver does not support that 
and collect feedback about priority if it should.

**Comment by soxofaan** [comment]
issue raised here as well: #84

**Comment by jdries** [comment]
Points and lines are supported now on openeo-dev. 
Should work when using geojson, loading vector data from file depends on vector cube work.
