### ISSUE TITLE
apply_vectorcube(geometries, cube) udf for VectorCubes

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#881]

**Comment by soxofaan** [comment]
I guess this ticket is actually an epic, so to keep overview, cross-referencing the related tickets/PR's:
- python client: https://github.com/Open-EO/openeo-python-client/pull/631
- python driver: https://github.com/Open-EO/openeo-python-driver/issues/314
- python driver: https://github.com/Open-EO/openeo-python-driver/issues/315
- geopyspark driver:  https://github.com/Open-EO/openeo-geopyspark-driver/pull/882
