### ISSUE TITLE
filter_spatial causes result with a  smaller extent

### ISSUE THREAD

**Issue by VictorVerhaert** [Open-EO/openeo-geopyspark-driver#891]
example job-id: j-241004aecee24f7cbd8cadfa2901de8e

Trying to get a patch of 1280x1280m on 20m resolution, however the result is 1260x1260. (one row and column missing)
 
target extent: "spatial_extent": {"west": 701120, "south": 7818080,  "east": 702400,  "north": 7819360, "crs": "EPSG:32701"}
 
resulting extent: 701130.0000000000000000,7818090.0000000000000000 : 702390.0000000000000000,7819350.0000000000000000
 
file used by filter_spatial: https://artifactory.vgt.vito.be/artifactory/auxdata-public/LCFM/sentinel1_tmp/patch_geom_01KFU.parquet
 
polygon used by filter_spatial and result visualized:
 where you see a 10m buffer on each side.
![image](https://github.com/user-attachments/assets/605f325d-e524-4a09-8c7d-05e613a6d2bd)

The same process without the filter_spatial correctly returns 1280x1280m. Filter_spatial is needed for grouping multiple patches in one job (to give some context).

**Comment by JeroenVerstraelen** [comment]
It appears that this is intended behavior. 

|   | minx | maxx | miny | maxy | crs |
| ------------- | ------------- | ------------- |  ------------- | ------------- | ------------- | 
| Requested  |  701120.0 | 702400.0 | 7818080.0 | 7819360.0 | EPSG:32701 |
| Output | 701130.0 | 702390.0 | 7818090.0 | 7819350.0 | EPSG:32701 |



In the [NetCDFRDDWriter.scala](https://github.com/Open-EO/openeo-geotrellis-extensions/blob/2a25a26e3d8e03135c9d3bdeba31d1400e8e73b7/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala#L597) logs we can see the following line:
```
Writing netCDF to /batch_jobs/j-241022f5e8fb403a917dce9cdfb13b9b/lcfm-s1-01KFU_01KFU_086_63.nc 
with bands [VV, VH, VHonVV], float32, 
EPSG:32701, 
GridExtent(Extent(701120.0, 7818080.0, 702400.0, 7819360.0), CellSize(20.0,20.0), 64x64)
```
So it is writing a 64x64 raster with the correct `rasterExtent` and correct UTM crs. 


The coordinates for the final NetCDF are generated using the following lines in [NetCDFRDDWriter.scala#L714](https://github.com/Open-EO/openeo-geotrellis-extensions/blob/2a25a26e3d8e03135c9d3bdeba31d1400e8e73b7/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala#L714):
```
val xValues = for (x <- 0 until rasterExtent.cols) yield rasterExtent.extent.xmin + x * rasterExtent.cellwidth + rasterExtent.cellwidth / 2.0
val yValues = for (y <- 0 until rasterExtent.rows) yield rasterExtent.extent.ymax - y * rasterExtent.cellheight - rasterExtent.cellheight / 2.0
```

In the current example this is:
```
minx = 701120.0 + 0*20 + 10 = 701130.0
maxx = 701120.0 + 63*20 + 10 = 702390.0
miny = 7819360.0 - 63*20 - 10 = 7818090.0
maxy = 7819360.0 - 0*20 - 10 = 7819350.0
```
I am not entirely sure why the NetCDFRDDWriter adds this (rasterExtent.cellwidth / 2.0) border around the extent. Perhaps @jdries knows more about this.

When running the same process graph without filter_spatial I did get the identical output as the run with a filter_spatial @VictorVerhaert.
I used the process graph from j-241004aecee24f7cbd8cadfa2901de8e as a template. It does produce a 64x64 result while your post mentions 1280x1280.

- [Process graph with filter_spatial](https://gist.github.com/JeroenVerstraelen/3c00e388b280744d5dc99cfff2d3555b)
- [Process graph without filter_spatial](https://gist.github.com/JeroenVerstraelen/9ebfb56f756579a9dbd2464f85f1c163)
