### ISSUE TITLE
Create S3 storage for WEED on CDSE

### ISSUE THREAD

**Issue by HansVRP** [Open-EO/openeo-geopyspark-driver#892]

**Comment by pvbouwel** [comment]
@HansVRP  I'll put it blocked for now generally for a bucket we need to know:
 - bucket names
 
 Access rules per bucket (E.g. RO, RW) and to which granularity
 
One gotcha is that it should be kept as simple as possible since we can only grant permissions at project level so each differnt type of permission requires a separate openstack project.

**Comment by HansVRP** [comment]
@pvbouwel do we typically have a single bucket per project or per dataset? 

If its per project I would simply go with a WEED bucket and use the same rules as used for e.g. lcfm. 

I will double check with Marcel on his requirements

**Comment by pvbouwel** [comment]
Initial requirements are clear.

We need a bucket for ecdc (ecosystem characterization data cubes) we bootstrap it in WAW3-1 in a separate project (such that billing can be separate).

We need internal credentials RW to use the bucket.
OpenEO needs RW access to the bucket as well (so we shouldn't use easy to guess bucket name but rather one with a hash like LCFM)

**Comment by pvbouwel** [comment]
Running into issues with project creation on CF: https://jira.cloudferro.com/browse/CDSE-1547

**Comment by pvbouwel** [comment]
Workaround to manage EC2 credentials: https://git.vito.be/projects/TPT/repos/os_creodias_openeo_k8s/commits/0734afccac8cb2dfc9c6215209d24646eeaabaa8#s3%2Fcreate_ec2_credential%2Fscripts%2Fcreate_ec2_credentials.sh

**Comment by pvbouwel** [comment]
At this stage it is possible to create buckets, access roles and credentials via Terraform.

Unfortunately ownership of `ec2 credentials` is not just the project where it is part off but it is also tied to the user. Hence we want be able to fully manage pre-existing `ec2 credentials`. But given that the majority is on changes in policies we'll focus on that.

**Comment by pvbouwel** [comment]
Bucket and policies are imported and managed via terraform.

For S3Proxy old openstack user and credentials have been removed and those have also been migrated to the new way (as there I had full controll). For other project we will await CF feedback so this item can be closed for now.
