### ISSUE TITLE
load_per_product: bands mismatch between metadata and data cube

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#893]
```json
{
  "process_graph": {
    "loadstac2": {
      "arguments": {
        "bands": [
          "precipitation-flux",
          "temperature-mean"
        ],
        "spatial_extent": {
          "crs": "EPSG:32631",
          "east": 398043.66962998867,
          "north": 5807663.283030516,
          "south": 5800318.038133569,
          "srs": "EPSG:32631",
          "west": 388117.96494662925
        },
        "temporal_extent": [
          "2021-12-01",
          "2022-11-30"
        ],
        "url": "https://s3.waw3-1.cloudferro.com/swift/v1/agera/stac/collection.json"
      },
      "process_id": "load_stac"
    },
    "save1": {
      "arguments": {
        "data": {
          "from_node": "loadstac2"
        },
        "format": "NETCDF"
      },
      "process_id": "save_result",
      "result": true
    }
  }
}
```

The resulting netCDF asset contains 4 bands (`precipitation-flux`, `temperature-mean`, `unkown_band_2`, `unkown_band_3`) instead of the expected 2 (`precipitation-flux`, `temperature-mean`).

**Comment by bossie** [comment]
The regression is due to a different `default_reading_strategy` in the configuration of CDSE: `load_per_product` as opposed to `load_by_target_partition` on Terrascope; it was recently introduced upon fixing #812 where this `load_per_product` was actually applied to `load_stac`.

It seems `load_per_product` has a bug; a workaround is to disable it with a `load_stac` feature flag:
```json
{
  "process_graph": {
    "loadstac2": {
      "arguments": {
        "bands": [
          "precipitation-flux",
          "temperature-mean"
        ],
        "featureflags": {
          "load_per_product": false
        },
        "spatial_extent": {
          "crs": "EPSG:32631",
          "east": 398043.66962998867,
          "north": 5807663.283030516,
          "south": 5800318.038133569,
          "srs": "EPSG:32631",
          "west": 388117.96494662925
        },
        "temporal_extent": [
          "2021-12-01",
          "2022-11-30"
        ],
        "url": "https://s3.waw3-1.cloudferro.com/swift/v1/agera/stac/collection.json"
      },
      "process_id": "load_stac"
    },
    "save1": {
      "arguments": {
        "data": {
          "from_node": "loadstac2"
        },
        "format": "NETCDF"
      },
      "process_id": "save_result",
      "result": true
    }
  }
}
```

This will fix the bands in the netCDF asset; peculiar is the fact that the result is only 2x1 pixels (regardless of the reading strategy used) and placed in the wrong location (near the equator). It does seem to work for larger AOI e.g. [0, 50, 5, 55].

**Comment by bossie** [comment]
> and placed in the wrong location (near the equator)

This seems to be an issue with the netCDF output as writing to GeoTiff does not exhibit this problem. This probably means that the workaround above indeed fixes Kristof V.T. original process graph.

**Comment by jdries** [comment]
@bossie note that it might just be that netcdf has better capabilities to write unknown bands, while geotiff relies more on cube metadata.
Feel free to assign this one to me if you haven't digged into load_per_product yet.

**Comment by jdries** [comment]
bylinktitle is false in the load_stac case, so we end up with a 'MultiBandCompositeRasterSource':
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/33cfe4e8274ef951f5490e706212a58c2e47c059/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala#L1565

There are various todo's that suggest that this is simply not well supported by load_per_product.

**Comment by bossie** [comment]
To confirm, I replayed Kristof's original job (`j-2410014bb4244419b8886854e8b4bab7`) with `"load_per_product": false` as `j-241008e2a777466e912f625af2e6c5b2` and it finishes successfully, as expected.

**Comment by jdries** [comment]
This is where it happens:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/39a36dc77c8b730e74b8fb2da52748d139d36085/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala#L646

MultibandCompositeRasterSource produces a multiband tile, this code is not ready for that, and believes it actually has to add the second band.

**Comment by jdries** [comment]
Committed a fix, I have unit tests, but they need to be properly integrated.
Still to do is to support the most complex cases, like proba-v, where multiple multi-band assets are combined.

**Comment by jdries** [comment]
Fixed and added tests, followup issue for more complex cases:
https://github.com/Open-EO/openeo-geotrellis-extensions/issues/332
