### ISSUE TITLE
test export_workspace + asset_per_band combination

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#905]
Edit batch job options from existing integrationtest

**Comment by VictorVerhaert** [comment]
example job that should be able to work: j-241011225b584a8ca14e374da7a9afe4

**Comment by JeroenVerstraelen** [comment]
In cdse integrationtests, @EmileSonneveld is working on asset_per_band.

**Comment by VictorVerhaert** [comment]
For this issue we will probably have to create a bucket for integration tests to avoid using (and leaking) workspace names of project specific buckets

**Comment by soxofaan** [comment]
can't we have the test logic public, but  we manage the secrets in the Vault? We already have plenty of tests that work that way

**Comment by JeroenVerstraelen** [comment]
Requires a bucket for integration tests and a workspace.
Alternative: moto library has throwaway s3 test service (scala requires swift url, you'll have to point this to the boto3 service via env variable).

**Comment by soxofaan** [comment]
> Alternative: moto library has throwaway s3 test service

FYI: https://docs.getmoto.org/en/latest/docs/server_mode.html


For example I used that in the tests for a pytest plugin for the APEx benchmarks
https://github.com/ESA-APEx/apex_algorithms/blob/7142e499a0ac8b261d6d941274965058e4ac0fda/qa/unittests/tests/pytest/test_pytest_upload_assets.py#L35-L39
using these fixtures https://github.com/ESA-APEx/apex_algorithms/blob/7142e499a0ac8b261d6d941274965058e4ac0fda/qa/unittests/tests/pytest/conftest.py
