### ISSUE TITLE
gdal.py can not use logging library with default multiprocessing

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#906]
**Description:**

We've encountered an issue with deadlocks arising from an interaction between Python's multiprocessing and logging libraries in gdal.py. These deadlocks occur sporadically, leading to batch jobs running significantly longer than expected or getting stuck entirely.

**Problem:**
- The root cause appears to be the sharing of memory between processes in the multiprocessing library, which happens by default. This sharing can lead to deadlocks in certain scenarios.
- As an initial fix, we disabled memory sharing, but this caused occasional Out of Memory errors.
- For now, we’ve worked around this issue by removing the logging functionality to prevent deadlocks.

**Next Steps:**
The ultimate solution will involve refactoring the module to reduce the scope of multithreading, but this will require more extensive changes.

**Current Workaround:**
Temporarily, we've opted to remove logging to avoid the deadlocks until we can rewrite the multithreaded parts of the module.

Commit that turned off logging in gdal.py:
https://github.com/Open-EO/openeo-geopyspark-driver/commit/c1b8676b3c93183082c93b97601cabe38e643f34

**Comment by bossie** [comment]
Restored a couple of log entries (poorly) in the context of https://github.com/eu-cdse/openeo-cdse-infra/issues/278; they use `print()` rather than a logger.

**Comment by EmileSonneveld** [comment]
A user encountered this issue here: https://forum.dataspace.copernicus.eu/t/sentinel-3-syn-gets-stuck/1429/3

To fix it, it is probably best to create the thread pool with `get_context("spawn")` instead of the default way that uses forks. (The fork way appears to copy mutexes, that could be in their locked state. When the parent process unlocks them, the child process would still have a locked mutex)

On top of that, it would be nice to add a timeout to the child processes.

**Comment by bossie** [comment]
I figured that would happen as logs are not limited to our own code.

**Comment by EmileSonneveld** [comment]
Gdal info got stuck even without multi threading:
`kubectl ... logs a-XXX-driver`
```python
...
{"message": "wrote metadata to /batch_jobs/j-2411280c977a4136a65091c5c7670b27/job_metadata.json", "levelname": "INFO", "name": "openeogeotrellis.deploy.batch_job", "created": 1732807885.0597, "filename": "batch_job.py", "lineno": 503, "process": 70, "job_id": "j-2411280c977a4136a65091c5c7670b27", "user_id": "89a9c868-cc44-46bb-9229-15ff7f2985cf"}
{"message": "Extracting result metadata from <DryRunDataTracer (traces: [<DataSource#140483550301632('load_collection', ('SENTINEL3_SYN_L2_SYN', {'productType': {'eq': 'SY_2_SYN___'}}))>, <DataTrace#140483504447632(#140483550301632, temporal_extent, ('2021-07-01', '2021-07-05'))>, <DataTrace#140483504449392(#140483504447632, spatial_extent, {'west': 0.5599048737374801, 'south': 40.542182462457816, 'east': 0.930517481832652, 'north': 40.8198900246893, 'crs': 'EPSG:4326'})>, <DataTrace#140483504449472(#140483504449392, bands, ['Syn_Oa01_reflectance', 'Syn_Oa02_reflectance', 'Syn_Oa03_reflectance', 'Syn_Oa04_reflectance', 'Syn_Oa05_reflectance', 'Syn_Oa06_reflectance', 'Syn_Oa07_reflectance', 'Syn_Oa08_reflectance', 'Syn_Oa09_reflectance', 'Syn_Oa10_reflectance', 'Syn_Oa11_reflectance', 'Syn_Oa12_reflectance', 'Syn_Oa16_reflectance', 'Syn_Oa17_reflectance', 'Syn_Oa18_reflectance', 'Syn_Oa21_reflectance', 'Syn_S1O_reflectance', 'Syn_S2O_reflectance', 'Syn_S3O_reflectance', 'Syn_S5O_reflectance', 'Syn_S6O_reflectance'])>, <DataTrace#140483504449552(#140483504449472, properties, {'productType': {'process_graph': {'eq1': {'process_id': 'eq', 'arguments': {'x': {'from_parameter': 'value'}, 'y': 'SY_2_SYN___'}, 'result': True}}}})>, <DataTrace#140483504449632(#140483504449552, apply, {})>, <DataTrace#140483504448912(#140483504449632, apply_dimension, {'dimension': 'bands'})>])>", "levelname": "INFO", "name": "openeogeotrellis.deploy.batch_job_metadata", "created": 1732807885.0742595, "filename": "batch_job_metadata.py", "lineno": 116, "process": 70, "job_id": "j-2411280c977a4136a65091c5c7670b27", "user_id": "89a9c868-cc44-46bb-9229-15ff7f2985cf"}
double free or corruption (out)
Fatal Python error: Aborted

...

Current thread 0x00007fc52a4ee100 (most recent call first):
  File "/usr/lib64/python3.8/site-packages/osgeo/gdal.py", line 6618 in InfoInternal
  File "/usr/lib64/python3.8/site-packages/osgeo/gdal.py", line 441 in Info
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/gdal.py", line 476 in read_gdal_info
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/gdal.py", line 332 in _process_gdalinfo_for_netcdf_subdatasets
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/gdal.py", line 274 in parse_gdal_raster_metadata
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/gdal.py", line 257 in read_gdal_raster_metadata
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/gdal.py", line 216 in _get_metadata_callback
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/gdal.py", line 116 in <listcomp>
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/gdal.py", line 116 in exec_parallel_with_fallback
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/gdal.py", line 164 in _extract_gdal_asset_raster_metadata
```

- This even happens without the UDF in the process graph `j-2411280c977a4136a65091c5c7670b27`
- Even happens with specifying 7Gb+ for executor and driver
- Does not happen locally. (Got a small output NetCDF that is visualizable in Q-GIS)

**Comment by EmileSonneveld** [comment]
Putting GDAL_NUM_THREADS=1 made gdal.Info cause a segfault. This is not easily recoverable. I changed the code to make it possible to run gdalinfo as a subprocess, which provides a graceful fallback if it fails.

**Comment by EmileSonneveld** [comment]
GDAL logs an error when a band contains pure nodata. Once suppressed, it still fills something in under `raster:bands`
```js
  "raster:bands": [
      {
          "name": "Syn_Oa01_reflectance",
          "statistics": {
              "minimum": 0.0,
              "maximum": 0.17989999055862,
              "mean": 0.043436175571097,
              "stddev": 0.037197965268448,
              "valid_percent": 16.96
          }
      },
      {
          "name": "Syn_Oa02_reflectance",
          "statistics": {
              "valid_percent": 0.0 // new
          }
      },
      ...
```

**Comment by EmileSonneveld** [comment]
Now on CDSE prod. Tested with the process graph of Dave Gabor and let him know it works

Monitoring on kibana showed a timout on a gdalinfo call. The openeo process succeeded, but without pixel statistics on a few bands. I drastically increased the timeout to 30min. (If the download speed stays the same, it should be able to internally download a 7Gb file)

Monitoring also showed that a warning is shown for csv and parquet files (but all works fine). Next release that warning will be gone too.

I'll monitor for gdalinfo errors in a for a while.

**Comment by EmileSonneveld** [comment]
Timeout seems to be fine. Next step is to use the gdalinfo json that is written on the executor.
