### ISSUE TITLE
batch_job.py `write_metadata`: avoid ad-hoc file selection for upload

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#940]
https://github.com/Open-EO/openeo-geopyspark-driver/blob/b63280c5fc5b928a0d231ab1aec6e3b47b4b9c36/openeogeotrellis/deploy/batch_job.py#L511-L519

Here we're building an ugly ad-hoc deny-list for "files"  that should not be uploaded to S3

As mentioned in the TODO, we should use an explicit asset list to upload instead of blindly assuming everything from the job dir should be uploaded (minus  some hand-picked exceptions)

**Comment by soxofaan** [comment]
cc @EmileSonneveld

**Comment by soxofaan** [comment]
As an illustration that this does not scale:
```
if UDF_PYTHON_DEPENDENCIES_FOLDER_NAME in str(file_path):
```

doesn't even work as `UDF_PYTHON_DEPENDENCIES_FOLDER_NAME` is not in play anymore on CDSE

**Comment by EmileSonneveld** [comment]
This issue is a direct result of changes introduced in https://github.com/Open-EO/openeo-geopyspark-driver/issues/877
