### ISSUE TITLE
reduce bands works in sync request but raises "IndexError: list index out of range" in batch job

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#943]
Discovered in the context of https://forum.dataspace.copernicus.eu/t/nodata-in-tiff-bands/1397.

This process graph on CDSE works as expected in a sync request but fails in a batch job:

```json
{
  "process_graph": {
    "loadcollection1": {
      "process_id": "load_collection",
      "arguments": {
        "bands": [
          "B03"
        ],
        "id": "SENTINEL2_L2A",
        "spatial_extent": {
          "west": 4.906082,
          "south": 51.024594,
          "east": 4.928398,
          "north": 51.034499
        },
        "temporal_extent": [
          "2024-10-23",
          "2024-10-24"
        ]
      }
    },
    "reducedimension1": {
      "process_id": "reduce_dimension",
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "dimension": "bands",
        "reducer": {
          "process_graph": {
            "arrayelement1": {
              "process_id": "array_element",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "index": 0
              },
              "result": true
            }
          }
        }
      },
      "result": true
    }
  }
}
```

```
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 739, in start_main
    main(sys.argv)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 245, in main
    run_driver()
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 206, in run_driver
    run_job(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/utils.py", line 57, in memory_logging_wrapper
    return function(*args, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 382, in run_job
    the_assets_metadata = result.write_assets(str(output_file))
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/save_result.py", line 170, in write_assets
    return self.cube.write_assets(filename=directory, format=self.format, format_options=self.options)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/geopysparkdatacube.py", line 1986, in write_assets
    [bands[i] for i in band_indices_per_file[index]] if band_indices_per_file else bands
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/geopysparkdatacube.py", line 1986, in <listcomp>
    [bands[i] for i in band_indices_per_file[index]] if band_indices_per_file else bands
IndexError: list index out of range
```

Admittedly the call to `.band("B03")` that results in this `reduce_dimension` doesn't make much sense in this case but e.g. calculating the NDVI with `ndvi = (nir - red) / (nir + red)` and writing it to a GeoTiff fails in the same way.

**Comment by soxofaan** [comment]
indeed, that `.band("B03")` is a bit redundant here, 
but still, the process graph is valid and should not fail like that

**Comment by soxofaan** [comment]
Same problem here https://discuss.eodc.eu/t/band-calculations-problem/1012  where the user tries to do actual band math, using `array_element` with `label` argument (instead of `index`).

Python snippet to reproduce:
```python
connection = openeo.connect(
    url="openeo.dataspace.copernicus.eu"
).authenticate_oidc()

cube = connection.load_collection(
    "SENTINEL2_L2A",
    spatial_extent={"west": 4, "south": 50, "east": 4.01, "north": 50.01},
    temporal_extent=["2024-08-01", "2024-08-10"],
    bands=["B02", "B04", "B08"],
)

b04 = cube.reduce_bands(
    lambda data: data.array_element(label="B04")
)
```

Sync processing request works, but batch job fails with 
>... 'time': '2024-11-19T10:05:47.206Z', 'level': 'error', 'message': "OpenEO batch job failed: IndexError('list index out of range')"}]
 ... j-2411197640724b6c9708856b0126bf5a

**Comment by soxofaan** [comment]
at first I thought this was related to `label` support, but indeed, as originally mentioned here, the problem also occurs with classic `index` support, e.g. with
```python
b04 = cube.reduce_bands(
    lambda data: data.array_element(index=1)
)
```

> 'time': '2024-11-19T10:20:48.735Z', 'level': 'error', 'message': "OpenEO batch job failed: IndexError('list index out of range')"}]
... j-241119bdffdf427a975203a3f2a91248

**Comment by soxofaan** [comment]
Seems to only apply to GeoTIF output, switching to netCDF makes the batch job work

**Comment by soxofaan** [comment]
from the logs it seems to be happening since Nov 5th

![image](https://github.com/user-attachments/assets/a7b6968e-f377-4280-a503-f9ff15b9518d)

**Comment by soxofaan** [comment]
about graph above: luckily the volume is relatively low, probably because the problem occurs for an unpopular use case: GeoTIFF download of a timeseries

**Comment by jdries** [comment]
If you're saying geotiff timeseries output is broken, please treat this as very critical.
And also need to check how it escaped integration tests, so just add one or convert one of the existing ones to output in this format.
