### ISSUE TITLE
Include job title in job listing

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#963]
from https://github.com/Open-EO/openeo-web-editor/issues/330

job listing does not include title, which makes default job overview in web editor not user friendly (and even confusing as some jobs eventually show a title and others don't):

![image](https://github.com/user-attachments/assets/56c7439b-1a29-4fc9-82ab-1a76eefad016)

**Comment by EmileSonneveld** [comment]
Screenshot from [CDSE dev](https://editor.openeo.org/?server=https%3A%2F%2Fopeneo.dev.warsaw.openeo.dataspace.copernicus.eu%2F). It is nice to see the titles again :)
![image](https://github.com/user-attachments/assets/f8d15574-c7c8-45a1-9927-def889837a88)
