### ISSUE TITLE
NetCDF download not possible

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#97]
When trying to download any process as NetCDF I get the error `13: Permission denied` from VITO backend (synchronous job), or the following error trace from batch jobs. I would appreciate getting NetCDF download back before the summer break, anything you can do @jdries?

error trace from job `156eea58-8967-43bc-b432-90ffd262deb1`, by @m-mohr:
`
"batch_job.py", line 301, in main run_driver() File "batch_job.py", line 287, in run_driver api_version=api_version, job_dir=job_dir, dependencies=dependencies, user_id=user_id File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1626077912052_9206/container_e4943_1626077912052_9206_01_000002/venv/lib64/python3.6/site-packages/openeogeotrellis/utils.py", line 37, in memory_logging_wrapper return function(*args, **kwargs) File "batch_job.py", line 361, in run_job assets_metadata = result.write_assets(str(output_file)) File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1626077912052_9206/container_e4943_1626077912052_9206_01_000002/venv/lib64/python3.6/site-packages/openeo_driver/save_result.py", line 79, in write_assets return self.cube.write_assets(filename=directory, format=self.format, format_options=self.options) File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1626077912052_9206/container_e4943_1626077912052_9206_01_000002/venv/lib64/python3.6/site-packages/openeogeotrellis/geopysparkdatacube.py", line 1284, in write_assets dim_names, global_metadata, zlevel File "/usr/hdp/3.1.4.0-315/spark2/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__ answer, self.gateway_client, self.target_id, self.name) File "/usr/hdp/3.1.4.0-315/spark2/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value format(target_id, ".", name), value) py4j.protocol.Py4JJavaError: An error occurred while calling z:org.openeo.geotrellis.netcdf.NetCDFRDDWriter.saveSingleNetCDFSpatial. : java.lang.ClassCastException: [F cannot be cast to [D at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:3037) at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2996) at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:1066) at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:1050) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.org$openeo$geotrellis$netcdf$NetCDFRDDWriter$$writeTile(NetCDFRDDWriter.scala:171) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$$anonfun$saveSingleNetCDFSpatial$1$$anonfun$apply$1.apply$mcVI$sp(NetCDFRDDWriter.scala:94) at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$$anonfun$saveSingleNetCDFSpatial$1.apply(NetCDFRDDWriter.scala:87) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$$anonfun$saveSingleNetCDFSpatial$1.apply(NetCDFRDDWriter.scala:78) at scala.collection.Iterator$class.foreach(Iterator.scala:891) at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.saveSingleNetCDFSpatial(NetCDFRDDWriter.scala:78) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter.saveSingleNetCDFSpatial(NetCDFRDDWriter.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357) at py4j.Gateway.invoke(Gateway.java:282) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.GatewayConnection.run(GatewayConnection.java:238) at java.lang.Thread.run(Thread.java:748) 
`

**Comment by przell** [comment]
I'm experiencing the same error. The same process graph I used was working a couple of hours ago. Then it suddenly threw the `SERVER-ERROR: 13: Permission denied`. I'm logging in with the basic method.

**Comment by jdries** [comment]
Yes, I also experienced it and was looking for the problem.
There is a workaround to fall back to our previous NetCDF implementation:
`cube.download("./data/mean_sd.nc", format="netCDF",options={"stitch":True})`

setting the 'stitch' format option to True will enable that old code path, which doesn't have this issue.

**Comment by m-mohr** [comment]
@jdries The parameter does not exist in the `/file_formats` endpoint.

**Comment by jdries** [comment]
no, indeed, it's also not an official parameter.
The 2 potential fixes for this issue should now be on openeo-dev.vito.be, please try again.
These are the 2 last known issues with the new NetCDF implementation, but you can always try using that parameter if you encounter something.

**Comment by jonathom** [comment]
works, thank you!
