### ISSUE TITLE
support custom GeoTIFF file level metadata

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#970]
Follow-up ticket of https://github.com/Open-EO/openeo-geotrellis-extensions/issues/317:  get file-level metadata in GeoTIFFs.

Should be a matter of defining an API (a format option) and mimicking this:

https://github.com/Open-EO/openeo-geopyspark-driver/blob/289b6b1e64a31300958c525ba037b2ca39938d2b/openeogeotrellis/geopysparkdatacube.py#L1915

**Comment by bossie** [comment]
@JorisCod: would a `file_metadata` format option to mirror `bands_metadata` do? For example,

```json
{
  "file_metadata": {
    "product_tile": "29TNE",
    "product_type": "LSF monthly median composite for band B02"
  }
}
```

**Comment by JorisCod** [comment]
That would be perfect !
