### ISSUE TITLE
assignment of bands to rgb does not work for png download

### ISSUE THREAD

**Issue by hewag1975** [Open-EO/openeo-geopyspark-driver#99]
Hi,

I am trying to generate true color images from Sentinel2 data and download them as png. Following the description in the [cookbook](https://openeo.org/documentation/1.0/cookbook/#output-save-result) I am assigning bands to rgb colors. However, I get the same output, no matter how a switch bands. Below is the code I am using and I have also attached the images I get for reference.

```
import openeo

con = openeo.connect('https://openeo.vito.be').authenticate_oidc('egi')
ext = {"west": -112.2, "south": 43.8, "east": -112.1, "north": 43.9}

dc = con.load_collection(
    'SENTINEL2_L2A_SENTINELHUB'
    , spatial_extent = ext
    , temporal_extent = ['2021-08-03', '2021-08-03']
    , bands = ['B02', 'B03', 'B04']
)

### scale to 8 bit
dc = dc.linear_scale_range(0, 6000, 0, 255)

dc.download(
  outputfile = 'rgb_234.png'
  , format = 'PNG'
  , options = {
      "red": "B02",
      "green": "B03",
      "blue": "B04"
    }
)

dc.download(
  outputfile = 'rgb_432.png'
  , format = 'PNG'
  , options = {
      "red": "B04",
      "green": "B03",
      "blue": "B02"
    }
)
```
![rgb_234](https://user-images.githubusercontent.com/38189568/129361039-9d1db314-82be-4293-8fe8-06a40fc6a930.png)
![rgb_432](https://user-images.githubusercontent.com/38189568/129361046-67e19fb0-28e8-4739-a518-971d5e857f85.png)

**Comment by soxofaan** [comment]
The VITO backend does not (yet) support that feature shown in the cookbook to swap RGB bands. It's somewhat mentioned:
> Some back-ends may offer to pass along this desired band order as it is shown below. Check with the back-end for available options.

but it's probably not obvious how one should "check with the back-end"

If I'm correct, @jonathom  wrote that PNG download example part in the cookbook, I'm not sure which backend he was using for the example. 


Anyway, an alternative workaround is to change band order in the `con.load_collection()` call. Can you check if that works for you   @hewag1975 ?

**Comment by jonathom** [comment]
> If I'm correct, @jonathom wrote that PNG download example part in the cookbook, I'm not sure which backend he was using for the example.

I did, and I used the earthengine backend (`https://earthengine.openeo.org`) for this.

**Comment by hewag1975** [comment]
@soxofaan, changing the band order in `load_collection()`resolved the issue, thanks for the hint!
